### ISSUE TITLE
Define a review team to delegate resources decision making

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#1]
## Goal: 
Define and implement the structure of a review team to delegate decision making on program resources

## Success:
Team is defined and started to operate

## Related Issues & Links: 

* https://github.com/mozilla/participation-org/issues/344

## Roles:
* Owner: @Faisalaziz @nukeador
* Involved: @francjp @couci

## Required: 
- [x] Define a proposal and share with council (April 24th)
- [x] Gather the team together and train inform about expectations (Jul 7th)
- [x] Communicate to the Reps (Jul 7th)
- [x] The review team starts working (Jul 15th)

**Comment by nukeador** [comment]
The proposal was sent to Council.

**Comment by nukeador** [comment]
I've updated the timeline to be more realistic.

**Comment by nukeador** [comment]
Waiting for Council to take a decision.

**Comment by nukeador** [comment]
Council is voting for the people in this group, ETA (2016-05-18 13:00)

**Comment by MichaelKohler** [comment]
Voting finished: https://reps.mozilla.org/v/review-team-for-resources-track/

Next we need to get in touch with these people to see if they're available. @nukeador please update the timeline, thanks

**Comment by nukeador** [comment]
Done

**Comment by nukeador** [comment]
@Faisalaziz can we get an update here please? We need to move this before London.

**Comment by Faisalaziz** [comment]
@nukeador I have sent you a draft for sending communication to selected reps, Kindly advice

**Comment by MichaelKohler** [comment]
@Faisalaziz please update this issue according to our discussion today

**Comment by couci** [comment]
The volunteer Review Team members are:
* Dian Ina Mahendra @alamanda 
* Ankit Gadgil
* Priyanka Nag
* Flore Allemandou
Responsibilities can be found [here ](https://docs.google.com/document/d/1tbcwCKBSK5tZldR21x4H5b0KQpxy2v4UA_zD8dvckWk/edit)

**Comment by couci** [comment]
Updated the the issue with more realistic dates

**Comment by couci** [comment]
Next steps are:
* Meeting with the Review Team
* Draft of the transition plan
* Communication for the Reps

**Comment by couci** [comment]
Doodle for meeting has been sent and comms about the review team members has been made

**Comment by couci** [comment]
The Review Team has met. @rara79 is also a member of the team until we have the second staff member participating. Our transition plan can be found [here](https://docs.google.com/document/d/115eCfi7W14O9q_iNbIX3oAb9XCTybfLHFTF_-yWF05s/edit)

**Comment by couci** [comment]
the review team has officially started working yesterday, great job everybody :)
