### ISSUE TITLE
Get a new round of mentors

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#10]
## Goal: 
Get a new round of mentors aligned with the RepsNext proposal.

## Success:
New mentors are on boarded

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:
Owner: @umeshagarwal @shahidfarooqui 
Involved: @rosanardila 
Supporter: @deimidis 

## Required: 
- [x] Communicate Mentors about nomination ( @shahidfarooqui  @umeshagarwal , Due: 29th April)

**Comment by nukeador** [comment]
@umeshagarwal @shahidfarooqui do you think we can move this to end of April? 

@emmairwin and @deimidis will be helping on providing the material for getting these new mentor up to speed and be able to coach people and we feel we should have them on boarded in early May.

Also we can think about getting these mentor not involved in budget at all to focus on the new coaching needs.

**Comment by umeshagarwal** [comment]
@nukeador yes we can. i think it will be better to get them on board ASAP. I will start the draft process with Shahid and share the details with you all. 

Yes we can keep these new mentors away from Budget and let them concentrate on their coaching. Keeping in mind that they should not get re-assigned mentees.

**Comment by shahidfarooqui** [comment]
Yes, I do agree with Nuke and Umesh.

Umesh and me will start the process soon.

**Comment by nukeador** [comment]
@shahidfarooqui @umeshagarwal please update the details in this issue. Thanks! :)

**Comment by emmairwin** [comment]
@nukeador when will you launch the discovery phase for mentor content?

**Comment by nukeador** [comment]
@emmairwin what do you mean by "mentor content"?

@umeshagarwal and @rosanardila are coordinating the call for new mentors.

@umeshagarwal can you update this issue with all the steps after the call out? Thanks!

**Comment by umeshagarwal** [comment]
mail draft is ready. waiting for @rosanardila to sent out mail to mentors mailing list by end of this week.

**Comment by shahidfarooqui** [comment]
If Rosana is busy then I guess Nuke can also send the mail to all mentors.
Draft is already ready and shared with all the council members including Rosana.

**Comment by rosanardila** [comment]
Hey all,

Sorry for the delay. I can send this early tomorrow if that works out.
Otherwise Nuke can do it  :)

Rosana

**Comment by rosanardila** [comment]
done :) Many thanks Shahid and Umesh for working on this!

**Comment by MichaelKohler** [comment]
Here's the (private) nominations sheet: https://docs.google.com/spreadsheets/d/1qEXiocabau6VATaBnP0IHTnRBmnn5YUsxFtaBKGo2m8/edit

**Comment by umeshagarwal** [comment]
@MichaelKohler Can you please create a range voting for this with the 6 nomination we received ? We need onboard them soon!

**Comment by umeshagarwal** [comment]
Thanks @MichaelKohler I have just created a range poll voting which will start tomorrow.

**Comment by MichaelKohler** [comment]
@umeshagarwal will compile a full list of responsibilities together with @deimidis  and reach out to the nominated persons so they can say if they can commit to that.

**Comment by deimidis** [comment]
Sorry all, an update on the project and current status.

We begun the process with 11 future Mentors[Coachs] and @ThePhoenixBird helping being the 12 that we need. The week of July 11th was the first call, and this week we had the second one. 

Both calls were recorded and are public, the same that material that i curated from different books and resources.

Next week we will begin with the work on small groups and practice. Also I will be creating a mailing group to have all the conversations there.

**Comment by brianking** [comment]
Shouldn't we be using the existing mentors list for conversations?

**Comment by Timmaks** [comment]
Yeah use the existing list so we can learn from the new fresh mentors

**Comment by nukeador** [comment]
My understanding is that the coaching exercises requires a certain level of trust between the group, so they are sharing their own experiences coaching each other which sometimes are a bit personal. That's why they wanted to have a separate channel. As soon as existing mentors get the training they would get access.

Am I right @deimidis ?

**Comment by deimidis** [comment]
Sorry for the delay in answer. Like @nukeador said, the main goal of that specific place is have conversations based on some trust that needs to be developed in the beginning. Obviously they could participate in the other mailing list, but having a space where they could share their concerns and doubts where they feel comfortable is a need (at least is my hypothesis).

**Comment by deimidis** [comment]
**Update**: I'm still with health issues on my eye, that made everything went slower than expected. By this time, *Mentors/Coachs* had 2 big meetings and some of them begun to meet on a small team basis (we divide them in small groups so they could practice better).

We have Discourse category ready, available for this team and Council members.

Next steps:

* This week we will have our 3rd meeting, adding practice needed. 
* Next week I will have 1:1 with all of them to get feedback on their status 
* I'm preparing another website where I could add more content (based on @nukeador incredible work on Activities website)
* I will participate on tomorrow Reps Call to update everybody on this project

**Comment by nukeador** [comment]
New mentors are about to start their coaching relationships, waiting for #67

**Comment by nukeador** [comment]
New mentors where on boarded, starting their relationships this week.
