### ISSUE TITLE
Create new Reps onboarding Webinar and test it

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#101]
## Goal: 
We want to test a Webinar to onboard new Reps. This will be used in the next onboarding round coming up once we've built the content.

## Related Issues & Links: 
#94 

## Roles:

Responsible: @brianking 
Accountable: Reps Council
Supporting: @couci @deimidis 
Consulted: Reps Council
Informed: 

## Required: 
- [x] Make team to work on this
- [x] Gather content for onboarding
- [x] Create Webinar materials (docs, slide deck, ...)
- [x] Choose a date
- [x] Choose a platform (Youtube Live, Vidyo, ...)
- [ ] Run Webinar

**Comment by MichaelKohler** [comment]
@brianking could you please extend the "Required" list and set a timeline? Thx

**Comment by varadekd** [comment]
Pretty excited to be part of Mozilla Reps program

**Comment by brianking** [comment]
I updated the required.

In terms of a timeline, it is going to be tight the next couple of weeks. I wonder if we can do all the prep tasks before Hawaii, and run the webinar when we are together there?

**Comment by couci** [comment]
I agree with @brianking since we are pushing a lot on mozactivate, let's put for now informing the people and set a webminar on Hawaii

**Comment by MichaelKohler** [comment]
Sounds good to me, though we need to remember

1) we will need to send the communication to the applicants as well to have most impact
2) time in Hawaii will be limited and we have other high prio sessions to run as well

**Comment by Andriah91** [comment]
Always ready and really excited to start the new program.

**Comment by igacifuentes** [comment]
With all the energy to help in Mozilla Reps program . Regards !!!

**Comment by rajnilayam** [comment]
Looking forward to be part of Mozilla Reps.

**Comment by bozzmob** [comment]
Would find best opportunities to contribute to Mozilla and be a part of Mozilla Reps

**Comment by elidron** [comment]
I can't wait 🙋🏻

**Comment by Andriah91** [comment]
Yes

Envoyé de mon iPhone

**Comment by akshit13** [comment]
Looking forward to be a part of reps program.

**Comment by shahbaz17** [comment]
When the webinar process will start ?

**Comment by sripathroy** [comment]
Waiting for the reps program

**Comment by MichaelKohler** [comment]
We are currently working on the content for the onboarding. We have a good base, now we need to make the content easily understandable and complete.

This is what it's gonna look like in terms of process (subject to change if necessary):

![v0 1_reps_onboarding_diagram](https://cloud.githubusercontent.com/assets/330324/21903533/966412cc-d900-11e6-80a4-16974c1c36c3.png)

**Comment by brianking** [comment]
And here is the base for content Michael mentioned:

https://docs.google.com/document/d/1K62phM6jr2SfWYIF1PL5sLsD91K7_gAAwd0mVrlvJJE/edit?usp=sharing

Comments welcome.

**Comment by MichaelKohler** [comment]
I've added some things to the document, @couci @brianking please provide feedback so we can share this with Council for a final feedback round. Then we can increase the value of the script (as a real script to read from basically).

**Comment by elidron** [comment]
Any news? :O I'm so excited to start the training!

**Comment by MichaelKohler** [comment]
We have discussed several points from the webinar document in Council. Missing points:

1) We would rather do a panel conversation instead of a 1:1 interaction between two Council members. We need to adapt the script for this.
2) There are some minor information missing in the script right now
3) We want to include the mobilizer role description which is currently being drafted and explored. This piece will go in last right before we will do the first webinar.

I expect steps 1 and 2 to be done by the end of the week.

**Comment by MichaelKohler** [comment]
I've also documented the workflow and experiment for the Webinar here: https://wiki.mozilla.org/ReMo/SOPs/Joining

**Comment by MichaelKohler** [comment]
I've updated the webinar (actually needed less updates than thought), please review if you have time :) https://docs.google.com/document/d/1K62phM6jr2SfWYIF1PL5sLsD91K7_gAAwd0mVrlvJJE/edit#

**Comment by elidron** [comment]
thanks a lot Michael!!  Read it and still waiting for this to happen! 💃

**Comment by MichaelKohler** [comment]
The script is almost ready. We need to handle a few administration tasks now:

* date to run it
* invite applicants to join
* set up the YouTube live instance

**Comment by MichaelKohler** [comment]
We are currently figuring out the last logistics questions. We will soon invite all applicants for the webinar :)

**Comment by elidron** [comment]
Thanks a lot for your dedication and time with us 💃

**Comment by MichaelKohler** [comment]
We will send out a doodle in the next few days. The webinar will also be recorded, if somebody can't make the live version. We will follow up with the applicants by email and bugzilla.

**Comment by MichaelKohler** [comment]
I've just sent out an calendar invite for the first webinar to everyone from Cohort 1 (bugs that as "<country code>, Webinar". If your bug is tagged like that and you didn't get a mail, please get in touch with me. I will also update all bugs with that information right now.

**Comment by MichaelKohler** [comment]
Current status:
* Date has been set
* Invites have been sent
* We will gather feedback from the participants right after the call
* We will share an initial analysis of feedback and early evaluation if we want to do this again or if we need to find another solution will be done
* We will guide the new Reps (plans etc)
* We will run Cohort 2 once we are confident that we want to continue this

**Comment by MichaelKohler** [comment]
We are all set for the webinar, we will be live-streaming tomorrow at 13:30 UTC / 15:30 CEST at https://air.mozilla.org/reps-webinar-2017-04-04/

**Comment by MichaelKohler** [comment]
We've run the Webinar and got initial good feedback for it. You can watch the recording here: https://air.mozilla.org/reps-webinar-2017-04-04/ . Also I've documented everything on the wiki, including the next steps for you to take: https://wiki.mozilla.org/ReMo/Webinar/2017-04-04

I'm closing this one, we will keep tracking the progress. I'll also follow up with another issue in this repository to track the future webinars, as well as one for tracking this cohort.
