### ISSUE TITLE
Publish RoM for November

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#105]
## Goal:
RoM of November is published on the portal, blog and discourse.

## Related Issues & Links:
[voting]  https://reps.mozilla.org/v/rep-of-the-month-for-november-1/

## Roles:
Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @ioana-chiorean 
Consulted: -
Informed: All Reps

## Required:
- [x] Write text (@MichaelKohler, Due: November 28th)
- [x] Review text (@ioana-chiorean, Due: November 30th)
- [x] Publish on portal, blog, Discourse and reps-general (@ioana-chiorean, @MichaelKohler, Due: November 30th)

**Comment by ioana-chiorean** [comment]
Mailed and pinged twice Raj on Telegram. Still waiting..

**Comment by couci** [comment]
@ioana-chiorean should we email him instead?

**Comment by ioana-chiorean** [comment]
@couci - I also mailed him one week ago. no reply

**Comment by MichaelKohler** [comment]
@ioana-chiorean Do you think we have the resources/information to do this by our own? I think we need to get this done within the next days.

**Comment by ioana-chiorean** [comment]
I did not get a reply from Gauthraj - in mails or Telegram (he did saw the message). I pinged him on FB to - replied last night saying he is traveling,. As this si already pretty delayed we need to move it fw asap - i will try to make the text today.

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla-community.org/t/rep-of-the-month-november-2016/12715

Blog post done, @couci @nukeador @brianking please approve.
Portal done, @akatsoulas instructed to date it back to November.

**Comment by MichaelKohler** [comment]
Blog post: https://blog.mozilla.org/mozillareps/2016/12/29/rep-of-the-month-november-2016/

Date on portal is now correct as well. Thanks everyone!
