### ISSUE TITLE
Publish RepsNext Status Visualization

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#106]
## Goal: 
Our last blog post about RepsNext was some time ago. With our new knowledge from the past weeks, we are creating a visualization on the current status as well as a simple roadmap visualization. This will be published in a blog post as well as our communication channels.

## Related Issues:
#93  

## Roles:
Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @AlexLakatos 
Consulted: Reps Peers
Informed: Reps, Open Innovation Team

## Required: 
- [x] Create a draft of the visualization (@MichaelKohler, Due: Dec 24th) 
- [x] Write initial draft for explanations for the visualization (@MichaelKohler, Due: Dec 24th) 
- [x] Review by Council / Feedback round (Reps Council, Due: Dec 29th) 
- [x] Create nice visualizations out of the drafts (@AlexLakatos, Due: Dec 31st)
- [x] Publish blog post and cross-post to Discourse, pin that Discourse post to Telegram (@MichaelKohler, Due: Dec 31st)

**Comment by hmitsch** [comment]
Would it be okay to add Peers to "informed"?

**Comment by MichaelKohler** [comment]
Of course, you are now consulting ;)

**Comment by MichaelKohler** [comment]
Sent to reps-council and reps-peers for first iteration of feedback.

![jan2017_repsnext_overview](https://cloud.githubusercontent.com/assets/330324/21531163/306e6f32-cd46-11e6-917f-3946360aa6bb.png)

![jan2017_timeline](https://cloud.githubusercontent.com/assets/330324/21531182/471e1c6e-cd46-11e6-85f2-308d8bfb8b7a.jpg)

**Comment by MichaelKohler** [comment]
@AlexLakatos the feedback round is done, could you please go ahead and get us that nice visualization digitally? :)

Please note: let's do the visualization without the black hole. We will write about that in the text for it.

**Comment by MichaelKohler** [comment]
Started to draft a blog post here: https://docs.google.com/document/d/1bscJK2v8dg7QPsiLhnGu37VCiW4r6qLyXnCW7sde9dM/edit# (Council only for now)

Also I've asked Yofie if he could do a nice looking graphic from the material above.

**Comment by couci** [comment]
@MichaelKohler do you think it would be useful to have in this blogpost where we are going as a program (the mobilizers road) as an introduction?
Also where do we stand with the design?

**Comment by MichaelKohler** [comment]
Let's create a seperate blog post for the mobilizer part once we have a clear definition. For now I'd like to get the update out.

I told Yofie that end of the week would be okay, let me ask him if he can make it.

**Comment by couci** [comment]
draft is now finished, expected publication date Monday 30th

**Comment by MichaelKohler** [comment]
We've just published a blog post about the current RepsNext status: https://blog.mozilla.org/mozillareps/2017/01/30/repsnext-status-update-january-2017/

Please join the discussion here: https://discourse.mozilla-community.org/t/repsnext-status-update-january-2017/13286
