### ISSUE TITLE
Define challenges & London facilitation

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#11]
## Goal: 
Figure out how to carry the design challenges for the Reps challenges in London. 

## Success:
  [What would success look like] 

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:
Owner: @rosanardila 
Involved: 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by MichaelKohler** [comment]
Everyone, please help filling out the Problem Statements for the different areas: https://docs.google.com/document/d/1HljFYPcvTSuEeB1Flc1arBA9O4s4dqfryCuQ2VO_v5M/edit#heading=h.uxtlhyot69gs

**Comment by MichaelKohler** [comment]
@rosanardila could you please update the tasks here?

**Comment by MichaelKohler** [comment]
Since we're currently doing the sprints, this is done and therefore I'm closing this.
