### ISSUE TITLE
Publish RoM for December

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#112]
## Goal:
RoM of December is published on the portal, blog and discourse.

## Related Issues & Links:
[voting] https://reps.mozilla.org/v/rep-of-the-month-for-december-1/

## Roles:
Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @ioana-chiorean 
Consulted: -
Informed: All Reps

## Required:
- [x] Let mentor of RoM write a text (@MichaelKohler, Due: January 5th)
- [x] Review text (@ioana-chiorean, Due: January 10th)
- [x] Publish on portal, blog, Discourse and reps-general (@ioana-chiorean, @MichaelKohler, Due: January 15th)

**Comment by couci** [comment]
I am adding myself as an assignee here so it appears on my todo to write the text

**Comment by MichaelKohler** [comment]
Portal done, asked @akatsoulas to date it back to December

Blog: https://blog.mozilla.org/mozillareps/2017/01/10/rep-of-the-month-december-2016/
Discourse: https://discourse.mozilla-community.org/t/rep-of-the-month-december-2016/12913

Thanks everyone!

**Comment by MichaelKohler** [comment]
Portal is dated back, thanks! reps-general got a link to the Discourse topic. We are all done. Thanks everyone for the help!
