### ISSUE TITLE
Council elections - Spring 2017

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#114]
## Goal:
- Hold the council election in order to occupy the spots that are free after the term of one year is ending for:

🎓 Irayani Queencyputri (RaRa)	
🎓 Faisal Aziz
🎓 Umesh Agarwal / Replaced by Ioana Chiorean in Dec. 2016
🎓 Flore Allemandou (6 months term as council from  Cohort)
🆕 🎓 Adriano Cupello (who due to personal commitments will step down at midterm) 

## Success:
- The elections take place and we have _ new council members
## Related Issues & Links:
- Previous Elections #15 
## Roles:
Owner: @ioana-chiorean 
Involved: @couci, Reps Peers 
Informed: @nukeador

## Required:
- [x] Prepare the timeline and the steps (@ioana-chiorean, Due:  May 11th) 
- [x] Send out the announcement (@ioana-chiorean, Due: May 12th) 
- [x] Start gathering nominations (@ioana-chiorean, Due:  May 13th) 
- [x] Close nominations (@ioana-chiorean, Due:  May 20th) 
- [x] Prepare Q&A (@ioana-chiorean, Due:  May 20th) 
- [x] Run Q&A (@ioana-chiorean, Due:  May 21st) 
- [x] Start Voting (@ioana-chiorean, Due: May 26th)
- [x] Close voting and announce results.  (@ioana-chiorean, Due:  June 1st) 

##Updates required:
- [x] History Page [9th Council ](https://wiki.mozilla.org/ReMo/Council/History#Ninth_Council_-_.28September_2016.29)
- [x] Create [10th entry](https://wiki.mozilla.org/ReMo/Council/History#Tenth_Council_-_.28May_2017.29)
- [x] Update [requirements for council members](https://wiki.mozilla.org/ReMo/Council#Election.2FDesignation_of_Council_Members) 
- [x] Update [tasks and requirements](https://wiki.mozilla.org/ReMo/Council#Tasks_and_Responsibilities_of_Council_Members)

**Comment by ioana-chiorean** [comment]
Proposed timeline (all times in 09:00 UTC):

* April 20th - call for candidates (eligible Mozilla Reps Mentors/Cohort only)
* April 27th - call closes
* April 28th - start of campaign period
    * candidates are given 5 days to answer questions and post them on their profile page
    * candidates are given 5 days to publish a 30-120 seconds campaign video
* May 2nd - deadline for answers and videos to be published
* May 3rd - voting starts
* May 9th - voting ends - new elected members are announced 
* May 10th - the Council Onboarding begins

**Comment by Mte90** [comment]
So this time only rep that are mentors can candidate it? The last time also reps that are not mentor can candidate (like me).

**Comment by ioana-chiorean** [comment]
Updated:
* [Tasks and Responsibilities of Council Members](https://wiki.mozilla.org/ReMo/Council#Tasks_and_Responsibilities_of_Council_Members)
* [Election/Designation of Council Members](https://wiki.mozilla.org/ReMo/Council#Election.2FDesignation_of_Council_Members)

Created:
* [Council Chair Archive](https://wiki.mozilla.org/ReMo/Council/Chairs)
* [Archive of previous Eligibility and criteria based on initial meetings](https://wiki.mozilla.org/ReMo/Council/Elections/Archives)

New proposed timeline (all times in 09:00 UTC):

* [x] May 13th - call for candidates (eligible Mozilla Reps Mentors/Cohort only)
* [x] May 20 - call closes
* [x] May 21st - start of campaign period
    * candidates are given 5 days to answer questions and post them on their profile page
    * candidates are given 5 days to publish a 30-120 seconds campaign video
* [x] May 25th - deadline for answers and videos to be published
* [x] May 26th - voting starts
* [x] June 1st - voting ends - new elected members are announced 
* [x] June 2nd - the Council Onboarding begins

Pls give feedback asap if something is not ok or needs improvements/corrections 
The Deadline is end of May 12th 9 PM CEST as I want to make the announcements today.

**Comment by hmitsch** [comment]
Looks good to me. Thank you @ioana-chiorean

**Comment by ioana-chiorean** [comment]
- [x] [Discourse announcement](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-please-read/15569) posted
- [x] [Etherpad](https://public.etherpad-mozilla.org/p/remo-elections-may-2017) to gather nominations created 
- [x] Mail on reps-general sent
- [x] Post on telegram 
- [x] Updated the timeline of Required actions in description.

**Comment by ioana-chiorean** [comment]
We closed the nomination period. We have the following candidates:

- [Daniele Scasciafratte](https://reps.mozilla.org/u/Mte90/)
- [Ankit Gadgil](https://reps.mozilla.org/u/ankitgadgil/)
- [Mayur Patil](https://reps.mozilla.org/u/yomanpatil/)
- [Vaibhav Bajaj](https://reps.mozilla.org/u/vabajaj/)
- [Alex Mayorga]( https://reps.mozilla.org/u/alex_mayorga)
- [Faye Tandog](https://reps.mozilla.org/u/fayetandog)
- [Meghraj Suthar](https://reps.mozilla.org/u/Meghraj/)
- [Priyanka Nag](https://reps.mozilla.org/u/priynag/)
- [Elio Qoshi](https://reps.mozilla.org/u/elio)
- [Mariot Tsitoara](https://reps.mozilla.org/u/mariot/)
- [Amine Zaafouri]( https://reps.mozilla.org/u/ZaafouriFF/)
- [Hossain Al Ikram](https://reps.mozilla.org/u/hossainalikram/)
- [Flore Allemandou](https://reps.mozilla.org/u/flore)
- [Kristi Progri](https://reps.mozilla.org/u/kristiprogri)

Further steps:
- [x] Mail all candidates with details of the next steps
- [x] Mail Reps-general 
- [x] Post on telegram

Reminder - timeline is here: https://github.com/mozilla/Reps/issues/114#issuecomment-301062627

**Comment by ioana-chiorean** [comment]
Tasks to prepare:

- [Daniele Scasciafratte](https://reps.mozilla.org/u/Mte90/)
  - [x] confirmation of received mail
  - [x] [video](https://www.youtube.com/watch?v=56bfrhbXOzM)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/3?u=ioana)
- [Ankit Gadgil](https://reps.mozilla.org/u/ankitgadgil/)
  - [x] confirmation of received mail
  - [x] [video](https://youtu.be/IluR3pQRBZs)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/9?u=ioana)
- [Mayur Patil](https://reps.mozilla.org/u/yomanpatil/)
  - [x] confirmation of received mail
  - [x] [video](https://www.youtube.com/watch?v=CMaBFY6zDbE)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/13?u=ioana)
- [Vaibhav Bajaj](https://reps.mozilla.org/u/vabajaj/) - **retired**
  - [x] confirmation of received mail
- [Alex Mayorga]( https://reps.mozilla.org/u/alex_mayorga)
  - [x] confirmation of received mail
  - [x] [video](https://youtu.be/0Cqc8L_15NY)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/8?u=alex_mayorga)
- [Faye Tandog](https://reps.mozilla.org/u/fayetandog)
  - [x] confirmation of received mail
  - [x] [video](https://youtu.be/H_wZ0PlsYQM)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/2?u=ioana)
- [Meghraj Suthar](https://reps.mozilla.org/u/Meghraj/) - **retired**
  - [x] confirmation of received mail
- [Priyanka Nag](https://reps.mozilla.org/u/priynag/)
  - [x] confirmation of received mail
  - [x] [video](https://youtu.be/jQvp1oxaNP0)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/6?u=ioana)
- [Elio Qoshi](https://reps.mozilla.org/u/elio)
  - [x] confirmation of received mail
  - [x] [video](https://youtu.be/3IahJZoP1SQ)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/10?u=ioana)
- [Mariot Tsitoara](https://reps.mozilla.org/u/mariot/)
  - [x] confirmation of received mail
  - [x] [video](https://www.youtube.com/watch?v=HXphm3dB45A)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/7?u=ioana)
- [Amine Zaafouri]( https://reps.mozilla.org/u/ZaafouriFF/)
  - [x] confirmation of received mail
  - [x] [video](https://www.youtube.com/watch?v=WT-6lOVnfc0)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/14?u=zaafouri)
- [Hossain Al Ikram](https://reps.mozilla.org/u/hossainalikram/) 
  - [x] confirmation of received mail
  - [x] [video](https://www.youtube.com/watch?v=Casrr8tvQcE&feature=youtu.be)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/15?u=ioana)
- [Flore Allemandou](https://reps.mozilla.org/u/flore)
  - [x] confirmation of received mail
  - [x] [video](https://ngc6369.space/cloud/index.php/s/4RflUgil1CJkef2)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/11?u=ioana)
- [Kristi Progri](https://reps.mozilla.org/u/kristiprogri)
  - [x] confirmation of received mail
  - [x] [video](https://youtu.be/ss6LlGvDC5k)
  - [x] [replies on discourse questions](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736/12?u=ioana)

**Comment by couci** [comment]
Voting closed, results here: https://discourse.mozilla-community.org/t/important-council-elections-results-and-next-steps/16012

**Comment by MichaelKohler** [comment]
Onboarding will happen in https://github.com/mozilla/Reps/issues/180, therefore closing this one.
