### ISSUE TITLE
Council change Umesh ↔️ Ioana

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#115]
Replacing a Council Member

Steps 4-7 from SOP applies:
- [x] Module owner must select a former Council member to fill the available seat until the next election
- [x] Module owner updates the portal and wiki
- [x] Module owner must inform reps-mentors that the list of Council members has been updated
- [x] Module owner informs reps-general that the list of Council Members has been updated

**Comment by MichaelKohler** [comment]
@ioana-chiorean what's the status of the second task regarding the Portal and https://wiki.mozilla.org/ReMo/Council/History ?

**Comment by ioana-chiorean** [comment]
@MichaelKohler Done! 🙌 
https://wiki.mozilla.org/ReMo/Council/History#Ninth_Council_-_.28September_2016.29
