### ISSUE TITLE
Publish OKRs for Q1 2017

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#116]
## Goal: 
We have published our OKRs for Q1 2017 which are based on the Community Development Team OKRs.

## Roles:
Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @couci 
Consulted: Reps Peers
Informed: Reps, Open Innovation Team

## Required: 
- [x] Create draft of the OKRs and send to Council (@MichaelKohler, Due: Jan 10th) 
- [x] Start initial discussion in Council (@MichaelKohler, Due: Jan 10th)
- [x] Wait until the CDT OKRs are approved (@MichaelKohler, Due: Jan 19th) 
- [x] Analyze feedback from CDT OKRs and if necessary tweak the Reps goals (@MichaelKohler, Due: Jan 24nd)
- [x] Publish final OKRs for Q1 in blog (for external visibility) / Discourse (@MichaelKohler, Due: Jan 28th)

**Comment by MichaelKohler** [comment]
The OKRs have been finalized in today's Council meeting. There is currently a voting open. If everything goes well, we will be able to share our OKRs in this week's Reps call. I'm starting a blog post draft for it tomorrow. I will also create some slides (or a visualization like Nuke did) to share in the call.

**Comment by MichaelKohler** [comment]
Presented in the Reps call today.

Discourse: https://discourse.mozilla-community.org/t/reps-program-goals-q1-2017/13205
Also sent to reps-general, pinned and announced in Telegram

Blog post is ready for review, @nukeador @couci (https://blog.mozilla.org/mozillareps/wp-admin/post.php?post=476&action=edit)

**Comment by couci** [comment]
done :)

**Comment by MichaelKohler** [comment]
Then we are all set here. Thanks!
