### ISSUE TITLE
Rewrite the Rep of the month wiki page

### ISSUE THREAD

**Issue by couci** [mozilla/Reps#117]
## Goal: 
Current wiki page for Rep of the month is outdated, we need to update it and add cool ideas

## Related Issues & Links: 
https://wiki.mozilla.org/ReMo/Council/Rep_of_the_month

## Roles:

Responsible: @couci

Accountable: @ioana-chiorean 

Supporting: @MichaelKohler 

Consulted: council

Informed: Reps 

## Required: 
- [ ] create etherpad with current updated process
- [ ] add experiments/suggestions
- [ ] update the wiki
- [ ] inform the Reps

**Comment by couci** [comment]
etherpad has been created https://public.etherpad-mozilla.org/p/ROM-wiki-updates

**Comment by MichaelKohler** [comment]
@couci @ioana-chiorean please review the Etherpad, I will publish it once you both agree to this new version.

**Comment by couci** [comment]
thank you @MichaelKohler added some small corrections. Also @Mte90 check it out since you've added some initial comments

**Comment by Mte90** [comment]
And I forgotten that I written something on that etherpad XD

**Comment by MichaelKohler** [comment]
New Wiki page here: https://wiki.mozilla.org/ReMo/Rep_of_the_Month

The old one (https://wiki.mozilla.org/ReMo/Council/Rep_of_the_month) redirects to the new one.

Thanks everyone!

**Comment by ioana-chiorean** [comment]
Thanks for driving and doing this @MichaelKohler ! (I did not even get to comment the issued that I have added my comments/suggestions and they were done already!  👏 👏 👏
