### ISSUE TITLE
FAQ contain references to FSA

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#118]
## Goal: 
Remove FSA from the faq on https://reps.mozilla.org/faq/
Replace with campus club is not the right thing because they don't have roles but only the club captain that is completely different from a rep.

## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by couci** [comment]
I think this is something we need to rephrase from the start in order to include the scopus of Campus Clubs
@bacharakis how do you think we should phrase this and what is the best link we should have there?

**Comment by MichaelKohler** [comment]
I think we will need to rewrite those FAQ in terms of RepsNext anyway. A quick fix right now would be to take it out or let @bacharakis come up with something. Though I don't think this fits the scope anymore.

**Comment by MichaelKohler** [comment]
I will take a first stab at the FAQ page to update it. I think we can completely remove that section for now. We don't really have a cross-over with Campus Clubs. Once that changes we can still update it.

**Comment by MichaelKohler** [comment]
I've opened a PR here: https://github.com/mozilla/remo/pull/1306

We will probably rewrite a lot of the content of the FAQ as well as the wiki when we have a clear understanding and definition of the word "mobilizer" and how this applies to Reps.
