### ISSUE TITLE
Define the Newsletter concept

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#119]
## Goal: 
We have an at least monthly newsletter to inform Reps what is happening in the Program and within Mozilla.

## Related Issues & Links: 
#73 

## Roles:

Responsible: @AlexLakatos 
Accountable: Reps Council
Supporting: Reps Peers
Consulted: Community Development Team, Reps
Informed: Reps

## Required: 
- [x] Decide on an owner for the Newsletter (@ioana-chiorean, Due: Jan 25th) 
- [x] Crowdsources ideas about possible content/format (incl. possible Design?) (@MichaelKohler, Due: Jan 25th) 
- [x] Owner to come up with a proposal according to crowdsourced ideas (content sections, tools, cadence) (Owner, Due: Feb 15th)
- [x] Send first newsletter according to proposal and measure engagement (Owner, Due: Feb 28th)

**Comment by MichaelKohler** [comment]
Started discussion about content here: https://discourse.mozilla-community.org/t/reps-newsletter-your-ideas-required/13114

**Comment by ioana-chiorean** [comment]
Thanks @MichaelKohler I will comment there too/

**Comment by MichaelKohler** [comment]
Community Development Team issue for this: https://github.com/mozilla/community-development/issues/496

**Comment by MichaelKohler** [comment]
@AlexLakatos will bring this further as responsible person in this heartbeat

**Comment by AlexLakatos** [comment]
Shipped the first newsletter. Web version available at http://mozilla.github.io/Reps/newsletter/02-2017/ . Opening new issues for next newsletter.

**Comment by MichaelKohler** [comment]
As we will improve month by month, I'm closing this one.
