### ISSUE TITLE
Publish RoM for January

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#121]
## Goal:
RoM of January is published on the portal, blog and discourse.

## Related Issues & Links:
[voting] https://reps.mozilla.org/v/rep-of-the-month-for-january-1/

## Roles:
Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @ioana-chiorean
Consulted: -
Informed: All Reps

## Required:
- [x] Let mentor of RoM write a text (@MichaelKohler, Due: January 31st)
- [x] Review text (@ioana-chiorean, Due: February 5th)
- [x] Publish on portal, blog, Discourse and reps-general (@ioana-chiorean, @MichaelKohler, Due: February 8th)

**Comment by ioana-chiorean** [comment]
Mail sent to mentor and close collaborator of ROM. ✉️

**Comment by MichaelKohler** [comment]
Done, https://blog.mozilla.org/mozillareps/2017/02/23/rep-of-the-month-january-2017/

Thanks @ioana-chiorean and @couci 

Just remembered that we will need to backdate the portal entry. Asked tasos to do so.

**Comment by MichaelKohler** [comment]
This has been done, thanks everyone!
