### ISSUE TITLE
Create Open Letter

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#127]
## Goal: 
The Open Letter is created and sent to Leadership.

## Related Issues & Links: 
https://discourse.mozilla-community.org/t/call-for-input-open-letter-to-mozilla-leadership/13390

## Roles:

Responsible: Laka
Accountable: Reps Council
Supporting: Reps Council, Mozillians
Consulted:
Informed: Mozillians

## Required: 
- [x] Inform Lucy about level of support we need (@MichaelKohler, Due: Feb 15th) 
- [x] Identify Hot Topics (@MichaelKohler, Due: Feb 16th) 
- [x] Draft open letter and get feedback on phrasing (Council, Due: March 10th)
- [ ] Send out letter (@mte90) 
- [ ] Publish somewhere (@mte90) 
- [ ] Close thread on Discourse

**Comment by MichaelKohler** [comment]
Hot topics identified here: https://docs.google.com/document/d/1pLBbIX9ZKmJ26MlB3W8biMbX3Q75PKlD9IOLsCosOHA/edit#

**Comment by MichaelKohler** [comment]
We are currently having talks on the format we want to present this in. We are on a good track, though quite some work is still needed.

**Comment by couci** [comment]
Draft was made and sent to Lucy and George for feedback

**Comment by Mte90** [comment]
A new version revamped that require a check from all of us to speed up the publishing!
https://docs.google.com/document/d/17VDb05bRT33V0w00XZph8G4Pzu7ZuayMNAqVdF7o4TA/edit#

**Comment by Mte90** [comment]
We are waiting for the last final review so it's quite ready for publish very very soon! 🙌

**Comment by Mte90** [comment]
We are fixing the last section!

**Comment by Mte90** [comment]
Published: https://discourse.mozilla.org/t/open-conversation-to-mozilla-leadership/22414
