### ISSUE TITLE
Create a certificate for all Reps that move to alumni

### ISSUE THREAD

**Issue by couci** [mozilla/Reps#129]
## Goal: 
Send a certificate for all the Reps that move to alumni status

## Roles:

Responsible: @couci

Accountable: @nukeador 

Supporting: council

Consulted:

Informed: 

## Required: 
- [x] Create a certificate for new alumni (@couci)
- [x] Get approval and sign off ( @nukeador )
- [x] Add it on the SOP ( @couci)

**Comment by couci** [comment]
Certificate has been created along with the email for comms, @nukeador could you check and give your sign off? Both live in this folder (council view only for now)
https://drive.google.com/drive/u/1/folders/0B8afomu5khGpYUl2VEVtaUV5M3M

**Comment by MichaelKohler** [comment]
LGTM, thanks!

**Comment by nukeador** [comment]
+1 Good to go

**Comment by couci** [comment]
certificate step added https://wiki.mozilla.org/ReMo/SOPs/Leaving
@MichaelKohler and @nukeador I will follow with you too on PM on sending the emails for recent alumni

Closing this one
