### ISSUE TITLE
Draft for outreach and marketting of Rep portal Event

### ISSUE THREAD

**Issue by dvigneshwer** [mozilla/Reps#130]
## Goal: 
Document providing checklist for reps to plan their event outreach

## Roles:
Consulted: @couci 

## Contents of document 

* Listing of all resources of available for outreach and marketing of Rep event such as requesting access for Mozillagram
* Social channels to be followed for different functional areas for example tweet to rustlang about the rust event etc

**Comment by Mte90** [comment]
I shared that link with the mozilla social champions and I think that in the requests we can add:

- Mozillagram access for * photos
- Likes/share on FB
- Retweet/likes on TW
- Comments on social networks on our messages (to be more generic and not focused in one social network)
- Get in touch with specific mozilla related account (I think that is enough to mention them in the tweet)

**Comment by couci** [comment]
thank you both for working on this
@Mte90 do the mozilla social champions have a list of specific social media to follow-like-retweet?

**Comment by Mte90** [comment]
I think that we can create that, but I will ask :-)

**Comment by MichaelKohler** [comment]
@dvigneshwer what is the status here?

**Comment by Mte90** [comment]
Ok I think that I can assign to me and work on that with a proposal like with something based on event playbook or to improve it

**Comment by Mte90** [comment]
I written a first draft https://docs.google.com/document/d/1PT96LRsl9tLqSSK8LVEByLX--vZHQ5e-DcWlN_W-KR8/edit and linked on the event playbook (the tracking for it is another ticket).
I tried to be general and not specific to every technology or activity or will be a mess to keep updated and fragment the resources.

@dvigneshwer do you want to take a look?

**Comment by Mte90** [comment]
Closing and waiting for future interests
