### ISSUE TITLE
Budget Discussion Q1/Q2

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#136]
## Goal: 
Decision on our final proposal for Budget allocation for Q1/Q2.

## Related Issues & Links: 
@Council: please vote on https://reps.mozilla.org/v/budget-q1-q2-second-try/

## Roles:

Responsible: @couci 
Accountable: Reps Council
Supporting: @MichaelKohler

## Required: 
- [x] Get to a decision (Council, Due: March 4th) 
- [x] Communicate decision to Reps (@MichaelKohler/@couci, Due: March 12th)

**Comment by ioana-chiorean** [comment]
Thanks MK for tracking this!

**Comment by MichaelKohler** [comment]
Voting is closed, we are working on comms now.

**Comment by MichaelKohler** [comment]
The communication will go out next week, as we need to finish the communication piece as well as the tracking sheet to link.

**Comment by MichaelKohler** [comment]
https://discourse.mozilla-community.org/t/budget-allocation-q1-2/14650
