### ISSUE TITLE
Design Community Experimentation Launchpad sprint

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#14]
## Goal: 
[One line goal description] 

## Success:
  [What would success look like] 

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:
Owner: @rosanardila 
Involved: @MichaelKohler 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by MichaelKohler** [comment]
@rosanardila @nukeador i think this is done as far as Reps Council is concerned, right?
