### ISSUE TITLE
Screen Applications for Cohort 2 (Webinar)

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#141]
## Goal: 
Applicants for Cohort 2 are screened by a group of Council members. We currently have 11 bugs that need to be screened. As of now, we are missing a third reviewer and comments from 2 members.

For now this is Council only, but we are considering outsourcing this for the next cohort :) (reading: feel free to respond here if you are interested to take part on this in future)

## Related Issues & Links: 
https://discourse.mozilla-community.org/t/screening-round-new-reps-cohort-2/13868

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: Faisal, Adriano?

## Required: 
- [x] 3rd person in committee is identified (@MichaelKohler, Due: March 1st) 
- [x] Feedback is given in sheet (Committee, Due: March 15th) 
- [ ] Applicants are informed (@MichaelKohler, Due: March 16th)

**Comment by hossainalikram** [comment]
For the next cohort, I wish to be involved in helping the council with assessment of applicants :)

**Comment by Mte90** [comment]
I am interested to for the next cohort!

**Comment by mijanurrahman** [comment]
Hi
I am interested for the Cohort 2 :)

**Comment by MichaelKohler** [comment]
Thanks for your responses, we will consider outsourcing this for the next cohort. We will get back to you ;)

All open applications have been screened, I will write updates on the applications soon.

**Comment by MichaelKohler** [comment]
Applicants have been informed of the decisions.
