### ISSUE TITLE
Feedback: Write back to Jeff regarding strategy

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#144]
## Goal: 
We have replied to Jeff regarding strategy.

## Related Issues & Links: 
(internal thread) https://discourse.mozilla-community.org/t/first-half-of-2017-okrs-and-strategy-for-l10n/13171

## Roles:

Responsible: @Flore-mozfr @couci 
Accountable: Reps Council

## Required: 
- [ ] Answer Jeff (@Flore-mozfr, Due: March 15th)

**Comment by couci** [comment]
@Flore-mozfr let's come up with a plan on this since our budget is now approved: I think it's important to know how many events they are expecting and what is the aligned agenda that will make those events good to go from them?

**Comment by MichaelKohler** [comment]
@Flore-mozfr What's the status here?

**Comment by MichaelKohler** [comment]
Thanks for the mail, Flore!
