### ISSUE TITLE
Selection of focus area (mobilizer/functional)

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#146]
## Goal: 
Survey for mobilizer/functional doers is completed and we are able to move forward according to this result.

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @couci 
Consulted: @hmitsch 
Informed: All Reps

## Required: 
- [x] Prototype for progress tracking is done (@MichaelKohler, Due: March 21th) 
- [x] Text is written for mobilizers/doers (@couci, Due: April 6th) 
- [x] Form is created (@couci, Due: April 6th)
- [x] Everything is ready for communication towards Reps (@MichaelKohler, Due: April 8th)
- [x] Communication and ask is done for Reps (@MichaelKohler, Due: April 8th)
- [x] Initial report is done according to responses (@MichaelKohler, Due: April 15th)
- [x] Final report is done according to responses (@MichaelKohler, Due: April 30th)
- [x] Henrik has all necessary email addresses to add to an organization on MozAnalytics (@MichaelKohler, Due: April 30th)

**Comment by MichaelKohler** [comment]
Updated timeline in description to fit reality

**Comment by MichaelKohler** [comment]
Communication on Discourse has been done: https://discourse.mozilla-community.org/t/action-needed-reps-path/15539

reps-general and call for action for Mentors is pending.

**Comment by couci** [comment]
This is closing today at 22:00 UTC.
Here is the list of the additional necessary actions:
- [x] E-mail people that have replied "I have no time to contribute" to ensure it was them to added the reply
- [x] prepare alumni letters and e-mails of appreciation for alumni
- [x] Remove people from reps-general
- [x] Remove people from NDA group
- [x] Remove people from bugzilla groups
- [x] Set people as alumni in the portal
- [x] Update the list of updated Reps here: https://github.com/mozilla/participation-metrics-org/issues/98
When those steps are done we can set the group on mozilla/analytics

**Comment by couci** [comment]
email to people sent

**Comment by couci** [comment]
Alumni letters have been prepared and sent for Reps that didn't reply

**Comment by couci** [comment]
No replies were moved to alumni and from the reps general list

**Comment by couci** [comment]
"I have not time to contribute" were moved to alumni as well as unsubscribed from the reps-general list

**Comment by couci** [comment]
Everyone has been moved to alumni

**Comment by couci** [comment]
Bugzilla bug for removal have been opened, on NDA we are blocked until we get the full list of invitees

**Comment by couci** [comment]
Request for removal on bugzilla has been opened. Also portal removals have finished and list has been updated for community analytics.

**Comment by couci** [comment]
Reps Alumni were moved out of the NDA group

**Comment by MichaelKohler** [comment]
@couci is it correct that the last step to do here is to provide Henrik with the data and we're done for now?

**Comment by Mte90** [comment]
From the content of the ticket I think that the title of this ticket is wrong maybe it's better: Moving Reps to Alumni after Reps Path or something like that

**Comment by couci** [comment]
The data were sent to Henrik, the only pending thing right now is to remove the bugzilla users (opened a bug and waiting an answer)

**Comment by hmitsch** [comment]
For sake of transparency and alignment: 

When @couci says:
> data sent to Henrik

@hmitsch understands that @couci refers to https://github.com/mozilla/participation-metrics-identities/blob/master/Reps-2017-06-06.csv

Is this correct?

**Comment by couci** [comment]
Yes thanks @hmitsch for pointing out :)

**Comment by couci** [comment]
All necessary steps were completed, I think we can close this.
@MichaelKohler should we open a new issue for mentors restructure considering the many orphans now?

**Comment by MichaelKohler** [comment]
Yes, we can close this. And yes, please file a new issue for that :) Thanks!
