### ISSUE TITLE
Q2 OKRs are published

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#147]
## Goal: 
We have published the Reps Program OKRs for Q2

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: Reps Peers
Consulted: Community Development Team OKRs
Informed: All Reps

## Required: 
- [x] Initial ideas are gathered and ready for feedback (@MichaelKohler, Due: March 20th) 
- [x] We have discussed the OKRs and voting is created (@MichaelKohler, Due: March 24th)
- [x] Communication is ready to be sent out (@MichaelKohler, Due: March 28th)
- [x] Dashboard is created and included in the comms (@MichaelKohler, Due: March 29th)
- [x] OKRs are published on Discourse, reps-general, Blog (@MichaelKohler, Due: March 31st)

**Comment by MichaelKohler** [comment]
This is signed off. Adriano and Konstantina will coordinate to publish this (for CDT and Reps).

**Comment by MichaelKohler** [comment]
Konstantina has published the OKRs on Discourse and sent them through reps-general: https://discourse.mozilla-community.org/t/reps-okrs-for-q2-2017/15134

**Comment by MichaelKohler** [comment]
@couci I've submitted the blog post as well, please review, publish and then close this issue here. Thanks for your help!

**Comment by couci** [comment]
Published https://blog.mozilla.org/mozillareps/2017/04/20/reps-program-objectives-q2-2017/
I've just changed the alignment of the picture, thanks @MichaelKohler 
Closing this one
