### ISSUE TITLE
Reps Newsletter Issue March

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#148]
## Goal: 
The newsletter for March is sent.

## Roles:
Responsible: @AlexLakatos 
Accountable: Reps Council
Supporting: @MichaelKohler
Consulted: Reps Council
Informed: All Reps

## Required: 
- [x] Initial ideas have been gathered (@MichaelKohler, Due: March 25th) 
- [x] Final set of content is decided on (@MichaelKohler, Due: March 27th) 
- [x] Test newsletter is sent for verification through Council (@AlexLakatos, Due: March 29th)
- [x] Newsletter is sent out (@AlexLakatos, Due: March 31st or whatever fits best around that)
- [x] Newsletter is published on GitHub as well (@AlexLakatos, Due: April 1st or whatever fits best around that)

**Comment by MichaelKohler** [comment]
My thoughts (based on the last newsletter):

* Reps of the Month - February
* Feedback Needed
  * (if applicable) Reminder about Reps Role form to fill out
* Budget Allocation for Q2
* (if applicable, would be so nice...) OKRs for Q2
* Monthly Roundup
  * Weekly Call / Council Call Notes
  * Reminder about Activate
  * Reps Moments / RoM on Facebook

**Comment by AlexLakatos** [comment]
Sent it out to council for feedback: http://us15.campaign-archive1.com/?u=9eae060f1b81c285205560420&id=7a31014df4&e=[UNIQID]

**Comment by AlexLakatos** [comment]
Newsletter went live in email, discourse and github.
http://mozilla.github.io/Reps/newsletter/03-2017/
https://discourse.mozilla-community.org/t/issue-no-2/14751

**Comment by MichaelKohler** [comment]
Great work, thanks a lot!
