### ISSUE TITLE
Publish RoM for March

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#149]
## Goal: 
RoM of March is published on the portal, blog and discourse.

## Related Issues & Links: 
[voting] https://reps.mozilla.org/v/rep-of-the-month-for-march-2/

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @ioana-chiorean @couci 
Consulted: Reps Mentors
Informed: Reps

## Required: 
- [x] Let mentor of RoM write a text (@MichaelKohler, Due: March 30th)
- [x] Review text (@ioana-chiorean, Due: April 5th)
- [ ] Publish on portal, blog, Discourse and reps-general (@ioana-chiorean, @MichaelKohler, Due: April 10th)

**Comment by MichaelKohler** [comment]
I've reached out to the mentor again yesterday to ask if they could write a text.

**Comment by MichaelKohler** [comment]
Unfortunately my 2 mails landed in spam. The mentor has seen them now.

**Comment by ioana-chiorean** [comment]
Thanks for the follow up MK! 🎉

**Comment by MichaelKohler** [comment]
* Done on portal, asked tasos to date it back to March.
* Discourse: https://discourse.mozilla-community.org/t/rep-of-the-month-march-2017/15392
* Posted to reps-general
* Sent blog post for approval /cc @couci 
* Sent message on telegram

**Comment by couci** [comment]
blogpost is live thanks @MichaelKohler  :)

**Comment by MichaelKohler** [comment]
tasos dated back the entry as well. This is done!
