### ISSUE TITLE
Reps Newsletter Issue April

### ISSUE THREAD

**Issue by AlexLakatos** [mozilla/Reps#157]
## Goal: 
The newsletter for April is sent.

## Roles:
Responsible: @AlexLakatos 
Accountable: Reps Council
Supporting: @MichaelKohler
Consulted: Reps Council
Informed: All Reps

## Required: 
- [x] Initial ideas have been gathered (@AlexLakatos, Due: April 24th) 
- [x] Final set of content is decided on (@AlexLakatos, Due: April 26th) 
- [ ] Test newsletter is sent for verification through Council (@AlexLakatos, Due: April 28th)
- [ ] E-Mail addresses of new Reps are added to the list (@couci, Due: April 29th)
- [ ] Newsletter is sent out (@AlexLakatos, Due: April 30st or whatever fits best around that)
- [ ] Newsletter is published on GitHub as well (@AlexLakatos, Due: April 30st or whatever fits best around that)

**Comment by MichaelKohler** [comment]
Ideas:

* Reps of the Month - March (we are quite behind with that, but should work)
* Feedback Needed
  * Reminder about Reps Role form to fill out
* OKRs for Q2
* New Reps in Orientation Period (@MichaelKohler to provide something)
* Monthly Roundup
  * Weekly Call / Council Call Notes
  * Reminder about Activate
  * Reps Moments on Facebook (maybe take one nice post and link it?)

**Comment by couci** [comment]
Can we have a section what's new with Activate? And there a summary of the updates?
Also it will be good to have: projects that need your help/feedback

**Comment by MichaelKohler** [comment]
Yes, Activate is a good idea. For the "projects that need your help/feedback", would we have something there?

**Comment by couci** [comment]
Coaching project, leadership training and the fb experiment could use people's help

**Comment by MichaelKohler** [comment]
We would need communications for all of these apart from the newsletter as well. Maybe not for FB experiment, as we can simply ask "Check out the recent posts and give your feedback!"

**Comment by MichaelKohler** [comment]
**Reps of the Month - March**
please see https://discourse.mozilla-community.org/t/rep-of-the-month-march-2017/15392/1 for the text

**OKRs for Q2**
We have published the Reps Program Goals for this quarter 2 weeks ago. Make sure to [read them and have a look at the visualization](https://discourse.mozilla-community.org/t/reps-okrs-for-q2-2017/15134). We are looking forward to hear your comments and feedback in the discourse topic as well as your thoughts on how you can help us to achieve those!

**New Reps in Orientation Period**
At the beginning of April we have started our first on-boarding [Webinar](https://wiki.mozilla.org/ReMo/Webinar) for new Reps. Konstantina, Laka and Michael recorded a [Webinar](https://air.mozilla.org/reps-webinar-2017-04-04/) to on-board 22 new Reps. Until now we have heard back from 15 applicants who were eager to continue the on-boarding process. We are happy to introduce you to all new Reps who have filled out their Reps profile so far. We have [created an overview for you to see who is getting onboarded](https://mozilla.github.io/Reps/newreps/).

**Community & Contributors survey**
We invite you to participate in a research that will shape the future of open source and other collaborative practices at Mozilla. We are asking for 10 minutes of your valuable time before May 15th to complete the survey about your experience with Mozilla and/or Mozilla’s sponsored projects. [You can find the survey in 5 different languages!](https://discourse.mozilla-community.org/t/we-want-to-hear-from-you/15384). 

**Projects which need your help**
* [Coaching Training Plan](https://discourse.mozilla-community.org/t/coaching-training-your-feedback-are-needed/15291) - please provide your feedback in the doc or in the Discourse topic itself
* Check out the experiments on the [Mozilla Reps Facebook page](https://www.facebook.com/MozillaReps/) and give your feedback about these efforts in the [Discourse post](https://discourse.mozilla-community.org/t/reps-moments-are-here/14398). Be sure to add #RepsMoments to your post-event social media (Facebook and Twitter) posts!

**Improved Activate activity detail pages**
We have improved the design of the MozActivate detail pages. This is part of our effort to make the activities easier to read. Checkout the [new design](https://activate.mozilla.community/webextensions/)! Also, mobilize your community to organize an activity if you're not planning to do so already.

**Monthly Roundup**
* Read all about what we did last month in the [Weekly Reps & Council meeting notes](https://discourse.mozilla-community.org/c/reps/meetings).
* Really, check out [MozActivate](http://activate.mozilla.community/), it's even linked from the Reps Portal frontpage now!

**Comment by MichaelKohler** [comment]
The newsletter was sent out! Thanks Laka!
