### ISSUE TITLE
Define content strategy for communication channels

### ISSUE THREAD

**Issue by AlexLakatos** [mozilla/Reps#158]
## Goal:

Define content strategy for communication done by the Reps Leadership: Council, Peers and MO
## Roles:

Responsible: @alexlakatos 

Accountable: Reps Council

Supporting: @MichaelKohler

Consulted: @couci 

Informed: Reps
## Required:
- [ ] Create a draft proposal for content matching channels (@alexlakatos @MichaelKohler , Due: April 27th) 
- [ ] Present draft at the Council meeting and get it reviewed (@alexlakatos, Due: May 2nd) 
- [ ] Share draft with Reps (Reps Council, Due: May 10th)
- [ ] Gather draft reviews and generate a report (@alexlakatos @MichaelKohler , Due: May 25th)
- [ ] Test draft on channels (@alexlakatos , Due: June 5th)

**Comment by MichaelKohler** [comment]
Current ideas about improvement experiments that we could run in Q3:

* Use https://github.com/mozillach/gh-projects-content-queue/commits/master for @MozillaReps tweets (automated tweets from GitHub repository issues)
* Change timing of Reps call (was brought up some time ago from Ioana in an issue I can’t find right now)
* New idea from Nuke: we need “external visibility” within Mozilla. One idea would be to go to the Weekly Meeting and provide updates on what Reps are doing

**Comment by MichaelKohler** [comment]
All possible experiments have been documented as different issues in this repo. I'm closing this one.
