### ISSUE TITLE
We have a clear understanding of Italian extension developers persona, needs and motivations, and we have an initial commitment from some of them to mentor the community

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#162]
## Goal: 

We have a clear understanding of Italian extension developers persona, needs and motivations, and we have an initial commitment from some of them to mentor the community

## Metrics

- An appealing email is crafted to encourage people to participate in the survey (why should I care about this? What value do I get?)
- 27 people are contacted to fill the survey
- 80% people fill the survey
- A place to get devs together is decided
- A list opportunities are defined based on survey result
- 3 devs commit to help mentor the community

## Related Issues & Links: 
Public feedbacks: https://public.etherpad-mozilla.org/p/reps-mob-daniele-2017
Private report: https://docs.google.com/document/d/18cIThexNqp5y1F145hB-3vRRtr65wYWPNg4W9EKE6p4/edit#

## Roles:

Responsible: @mte90
Accountable: @nukeador 

## Required: 
- [x] Prepare an email to send the survey
- [x] Prepare the survey questions
- [x] Review the survey questions
- [x] Send the survey by Addon team to 27 people (8-12/05/2017)
- [ ] Analyze the surrvey data
- [ ] Complete the Persona
- [ ] Add other stuff to do

**Comment by nukeador** [comment]
Hey @Mte90 

Let's make sure title is the goal text and metrics are also included here :)

Thanks!

**Comment by Mte90** [comment]
Do you think that is filled right now?

**Comment by nukeador** [comment]
I edited the title ;-)

**Comment by Mte90** [comment]
Few updates, the survey is ready, the email will send in this week and I am continuing to improve the persona
