### ISSUE TITLE
Clean up Wiki pages

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#17]
## Goal:

All Wiki pages are either marked as deprecated or are up to date.
## Related Issues & Links:

[Reps Identity Working Group](https://discourse.mozilla-community.org/t/reps-identity-comms-working-group/8174/7)
## Roles:
- Owner: @MichaelKohler
- Involved: @ioana-chiorean
## Required:
- [x] Create list of all sub pages (@MichaelKohler, Due: Apr 27th) 
- [x] Classify according to topics (@MichaelKohler, Due: Apr 27th) 
- [ ] Get Review for deprecated pages (@ioana-chiorean, Due: May 7th)
- [ ] Mark all deprecated pages as such (..., Due: May 20th)
- [ ] Update all pages according to RepsNext (..., Due: May 30th)

**Comment by MichaelKohler** [comment]
Here's the list: https://wiki.mozilla.org/ReMo/Cleanup

@ioana-chiorean I put you as reviewer, do you have time to do that?

**Comment by nukeador** [comment]
Let's move this to Ready until the first action is taken :)

**Comment by nukeador** [comment]
Checking the wiki, maybe it would be easier to start some stuff from scratch. Simply listing all the things that should be present and making sure they are in a way it's easy to read (and yes most SOPs and such can be re-used)

**Comment by nukeador** [comment]
Also, raising a flag here: I feel this task should be put on hold until we finish all the RepsNext work, when we will have more clarity on what should and shouldn't be on the wiki.

Investing time now on this instead of other open tasks it's not maybe the best use of our limited time :)

**Comment by MichaelKohler** [comment]
Obviously we need to be clear on what needs to be updated and therefore we need to have final state of proposal implementations for RepsNext. Therefore this is blocked for now. This will be a good base to work on once we have that though.

**Comment by Timmaks** [comment]
don't wait to the final state of reps next but start to label pages as outdated as soon as possible so its gets clear that they are obselete

**Comment by ioana-chiorean** [comment]
I think the decision in London was to archive everything and start from scratch. 
Right - @MichaelKohler @nukeador ?

**Comment by nukeador** [comment]
@ioana-chiorean yes, also having in consideration that we can always rescue certain pages from the archive if we feel they are still relevant.

**Comment by Timmaks** [comment]
anything i can do to get this going?

**Comment by nukeador** [comment]
I've done an initial clean up of the pages that were outdated and still linked, making everyone confused:

* ReMo/Planning/Material ‎ (Cleaning. outdated)
* Template:Remoplannav ‎ (Cleaning. outdated)
* ReMo/Planning/Outreach ‎ (Cleaning. outdated)
* ReMo/Planning/Schedule ‎ (Cleaning. outdated)
* ReMo/Planning/Website ‎ (Cleaning. outdated)
* ReMo/Tools and Resources/Slide decks ‎ (Cleaning. outdated)
* ReMo/Tools and Resources/Toolkit ‎ (Cleaning. outdated)
* ReMo/Website/Meetings ‎ (Cleaning. outdated)
* ReMo/Council/History ‎ (Brian as new appointed Council)
* ReMo/Mentors ‎ (Remonav)
* ReMo ‎ (Major cleanup of obsolete content)
* Template:Remonav ‎ (Adding website)
* Template:Remonav ‎ (Logo update)
* Template:Remonav ‎ (Updated sections)
* ReMo/FAQ ‎ (People page)
* ReMo/Planning ‎ (Cleaning. outdated)
* ReMo/Website ‎ (Cleaning. outdated)
* ReMo/Tools and Resources ‎ (Cleaning. outdated)
* ReMo/SIGs ‎ (Cleaning. outdated)
* ReMo/SIGs/Communications ‎ (Cleaning. outdated)
* ReMo/SIGs/CommunityIT ‎ (Cleaning. outdated)
* ReMo/SIGs/AirMozilla ‎ (Cleaning. outdated)
* ReMo/SIGs/Webdev ‎ (Cleaning. outdated)
* ReMo/SIGs/L10n ‎ (Cleaning. outdated)
* ReMo/SIGs/QA ‎ (Cleaning. outdated)
* ReMo/SIGs/SUMO ‎ (Cleaning. outdated)
* ReMo/SIGs/Evangelism Reps ‎ (Cleaning. outdated)
* ReMo/SIGs/CommunitySysadmin ‎ (Cleaning. outdated)
* ReMo/SIGs/Documentation ‎ (Cleaning. outdated)
* ReMo/SIGs/Webmaker ‎ (Cleaning. outdated)
* ReMo/Tools and Resources ‎ (Removing a lot of obsolete content)
* ReMo/Tools and Resources/Topics and Ideas ‎ (Cleaning. outdated)

We should also request deletion on some pages listed here

https://wiki.mozilla.org/ReMo/Cleanup

**Comment by Mte90** [comment]
I was maintaining the slide decks wiki page, there is an alternative for that page where i can move that resources?

**Comment by nukeador** [comment]
@Mte90 we should probably start a new one with updated material. I need to check with @francjp and @deimidis to port over to the wiki the Events playbook they were working on.

We also had this:

https://wiki.mozilla.org/Contribute/Events/Inventory

**Comment by dyvik100** [comment]
https://wiki.mozilla.org/Marketing_Collective [Outdated,Program Shutdown]
https://wiki.mozilla.org/StudentAmbassadors/Recognition[Outdated]
https://wiki.mozilla.org/CommSquared[Outdated,Program Shutdown]

**Comment by brianking** [comment]
Dyvik,

Those pages are out of scope of this bug which only cover pages under /Remo/.

+ @emmairwin who might know how outdated pages are handled in general.

**Comment by emmairwin** [comment]
I have been adding the 'archived' heading to outdated wiki pages.

i.e.    https://wiki.mozilla.org/Participation/Lab

would this work?

**Comment by SpikeUK** [comment]
I am a tiny admin on the wiki if I can be of any help - deleting pages, creating "Awaiting Deletion" templates etc

**Comment by ioana-chiorean** [comment]
I think this should have been also under the Wiki team radar: https://wiki.mozilla.org/Category:Delete 
Some more policies: https://wiki.mozilla.org/MozillaWiki:Policies

**Comment by SpikeUK** [comment]
I agree wholeheartedly @ioana-chiorean - at the moment I think I may be the most active of the wiki team :( although MozFest did get in the way a bit :)
My offer to assist still stands until a real Wiki administrator steps forward.

**Comment by MichaelKohler** [comment]
I will take a stab at this to make sure we at least tell that it's outdated and do some minor cleanups as well. My goal is to have this finished by the end of the week so in the future we can focus on updating relevant content as we implement RepsNext.

**Comment by SpikeUK** [comment]
I have already deleted the pages that were flagged for deletion and showing on https://wiki.mozilla.org/Category:Delete.
If more pages need to go please flag them as noted on the Category page.

**Comment by ioana-chiorean** [comment]
Thanks @SpikeUK! Really appreciated!

**Comment by MichaelKohler** [comment]
@SpikeUK I've added more pages to the delete list. Please proceed :) Thanks!

After this, the only thing left is to update the pages of https://wiki.mozilla.org/ReMo/Cleanup according to RepsNext, which is done as of the current status. We will keep this going as soon as we implement new things. Once the pages marked for deletion are deleted, I think we can close this one here.

**Comment by SpikeUK** [comment]
@MichaelKohler : on it :)

**Comment by ioana-chiorean** [comment]
Thanks so much @SpikeUK for the help!

**Comment by SpikeUK** [comment]
@MichaelKohler : I have now deleted the 88 pages that you marked for deletion a couple of hours ago.
@ioana-chiorean : Not a problem, I more than happy to help :)

**Comment by MichaelKohler** [comment]
Great, thanks!
