### ISSUE TITLE
May Reps Newsletter Issue

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#170]
## Goal: 
The newsletter for May is sent. We include the "Reps Path" discourse topic with the call to action to fill out the survey. Therefore we need to send a few days before June 1st (2 or so).

## Roles:
Responsible: @AlexLakatos 
Accountable: Reps Council
Supporting: @MichaelKohler
Consulted: Reps Council
Informed: All Reps

## Required: 
- [ ] Initial ideas have been gathered (@AlexLakatos, Due: May 25th) 
- [ ] Final set of content is decided on (@AlexLakatos, Due: May 26th) 
- [ ] Test newsletter is sent for verification through Council (@AlexLakatos, Due: May 28th)
- [ ] Newsletter is sent out (@AlexLakatos, Due: May **29th**)
- [ ] Newsletter is published on GitHub as well (@AlexLakatos, Due: May 30th)

**Comment by MichaelKohler** [comment]
And as always, my suggestions in terms of content:

* Reps of the Month - May (we just need to be fast on the text)
* Reminder about Reps Role form to fill out (@MichaelKohler to provide)
* Council elections (maybe @ioana-chiorean could draft some words? Voting will be fully ongoing if we can send it 2 days before normal)
* Information about onboarding status / second cohort (@MichaelKohler to provide)
* [Mozilla Global Sprint](https://discourse.mozilla-community.org/t/mozillas-global-sprint/15680)? (probably too short-term?)
* Monthly Roundup
  * Weekly Call / Council Call Notes
  * Reminder about Activate
  * Facebook experiment call to action (@MichaelKohler to ask Srushtika for ideas on promotion)

**Comment by ioana-chiorean** [comment]
Elections should definitely be in - if it will be posted before the results - we can link the candidates, if later , we can link the results. I will prepare a text.

**Comment by MichaelKohler** [comment]
> Elections should definitely be in - if it will be posted before the results - we can link the candidates, if later , we can link the results. I will prepare a text.

I really want to send this one out before the 1st of June, so there is time for a voting reminder as well as filling out the reps path form. @AlexLakatos how do you feel about the timeline here?

**Comment by MichaelKohler** [comment]
**Placeholder for RoM**
(text started, Laka has the link to it)

**Reps Path**
[Understanding what Reps want](https://discourse.mozilla-community.org/t/action-needed-reps-path/15539) to do is crucial for the future of the program. That's why we created a form to indicate which area you want to focus your time on. Please fill the form before June 1st. After this deadline we will reach out to everyone who hasn't responded yet and transfer inactive Reps to Alumni. [Learn More.](https://discourse.mozilla-community.org/t/action-needed-reps-path/15539)

**Reps Council Elections**
Currently we have the Reps Council Elections going on. We have 12 candidates up for voting. If you haven't voted for the next 5 Council Members yet, please do so on the [Voting page](https://reps.mozilla.org/v/reps-council-elections-spring-2017-5-spots/). You can read more about all the candidates and watch their videos from the [Discourse Q&A page](https://discourse.mozilla-community.org/t/important-council-elections-spring-2017-nominee-q-a/15736). [Go Vote!](https://reps.mozilla.org/v/reps-council-elections-spring-2017-5-spots/)

**Mozilla Global Sprint**
The [Mozilla Global Sprint](https://mozilla.github.io/global-sprint/) will happen on June 1st and 2nd. This is a fast-paced, fun two-day collaborative work event where we’ll come together online and in person to work and hack on open projects that support the open web. You can either [join this sprint online](https://mozilla.github.io/global-sprint/participants/) and participate, or [host your own site](https://mozilla.github.io/global-sprint/site-hosts/) (very short term). [Learn More.](https://discourse.mozilla-community.org/t/mozillas-global-sprint/)

**Onboarding new Reps**
As you know, we have started our on-boarding Webinar experiment at the beginning of April. We are happy to have welcomed 15 new Reps in their Orientation Period so far. In the middle of May we pushed the on-boarding experiment to a new level, inviting 12 more Reps into the program. As these Reps go through the Webinar, we are confident that the Webinar is a good resource to on-board new Reps in a scaling matter. [Learn more.](https://wiki.mozilla.org/ReMo/Webinar)

**Update on MozActivate**
Thanks for all your contributions to MozActivate! These are high impact activities we encourage everyone to mobilize for. Additionally to the Impact Form on Google Forms you can also directly point your attendees to the [MozActivate website to fill out the feedback form](https://activate.mozilla.community/howwasit/). We are currently working on having a separate page where you can see your impact. This will help you to validate what type of attendees you had, your NPS score as well as the number of responses you got. [Check it out!](https://activate.mozilla.community/howwasit/)

**Monthly Round-up**
* Read all about what we did last month in the [Weekly Reps & Council meeting notes](https://discourse.mozilla-community.org/c/reps/meetings).
* Apply for the [Slack pilot](https://discourse.mozilla-community.org/t/slack-pilot-for-ndad-mozillians-looking-for-candidates/15786) to test if staff-only Slack interaction with NDA'd Mozillians is beneficial.
* Check out the [Monthly Internal Call for May](https://air.mozilla.org/login/?next=/monthly-internal-call-may-2017/
* Check out what has been going on in [Firefox improvements in Photon](https://dolske.wordpress.com/2017/05/23/photon-engineering-newsletter-2/) as well as [Quantum Flow](https://ehsanakhgari.org/blog/2017-05-19/quantum-flow-engineering-newsletter-10)

**Comment by AlexLakatos** [comment]
completely doable before the 1st. Holiday in the UK on Monday, so will aim to send for review on Monday
