### ISSUE TITLE
Initial Leadership resources are available for all Reps

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#189]
## Goal: 
An initial list of leadership resources is available for all Reps.

## Roles:

Responsible: <to be decided>
Accountable: Reps Council

## Required: 
- [x] Create initial list compilation (?, Due: June 15th) 
- [ ] Publish list compilation on Wiki (?, Due: June 20th) 
- [ ] Announce to all Reps and get initial feedback in Discourse topic (?, Due: June 24th)

**Comment by Mte90** [comment]
This kind of list is also made by books or only online resources?
I have this one about coaching/leading:

- http://deimidis.github.io/community_curriculum/
- https://docs.google.com/document/d/1PAAwLL5QjI9mkfK5YH6Hlp690JsJVLtbDaUcxXJJ4Dw/edit
- https://mte90.net/en/2016/08/recruit-and-motivate-new-volunteers/
- https://wiki.mozilla.org/Participation/Community_Playbook
- https://docs.google.com/document/d/1Me6jN1S1zqRiHNtUttX-fZibuK1-uB_XHQbG4dYhHww/edit
- http://toolkit.mozilla.org
- https://wiki.mozilla.org/Participation/Resources
- http://mte90.github.io/Talk-Coaching/
- https://mozilla.github.io/open-leadership-training-series/
- https://mozilla.teachable.com/p/mozilla-open-leadership-training-series
- https://leadership.mozilla.community/
- https://www.16personalities.com/free-personality-test

**Comment by MichaelKohler** [comment]
Thanks Daniele, I've added most links we didn't already have in there.

**Comment by couci** [comment]
thank you both
some notes:
the "motivate new contributors" is kind of outdated since it has the regional coaches initiative that got renamed, maybe we should take it out
the events playbook might not be that relevant anymore. Anything else seem good, good work you too!

**Comment by MichaelKohler** [comment]
For reference: https://docs.google.com/document/d/1Jts_6kt5r2zDo-lSyL3EP-hxhNxCRuMxC8qmeZeOXmU/edit?usp=sharing

> the "motivate new contributors" is kind of outdated since it has the regional coaches initiative that got renamed, maybe we should take it out

I don't see any mention of that in the document by Daniele, where exactly is it?

> the events playbook might not be that relevant anymore

No, but it's still a good resource. Let's keep it for now.

**Comment by MichaelKohler** [comment]
BTW, will publish it on the Wiki tonight and write a Discourse post.

**Comment by MichaelKohler** [comment]
Done: https://discourse.mozilla-community.org/t/leadership-resources/16551

Let's get feedback and improve the list through that :)
