### ISSUE TITLE
Suggestions for Monday Call

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#19]
## Goal:

We have come up with suggestions to implement for our presence in the Monday call
## Related Issues & Links:

Reps Identity & Communications WG
## Roles:
- Owner: @MichaelKohler
- Involved: WG
## Required:
- [ ] Brainstorm around possible ideas (WG, Due: May 27th) 
- [ ] Document suggestions (WG, Due: June 10th)

**Comment by Mte90** [comment]
Maybe a little recap of the WG state so we can promote our program also to Mozilla employees.
Also say something about the event organized in the last week like in our weekly call but like a fast recap ex: 3 events in europe, 4 in asia etc.

**Comment by ioana-chiorean** [comment]
@rosanardila @nukeador ^

**Comment by nukeador** [comment]
@ioana-chiorean what do you need here?

**Comment by MichaelKohler** [comment]
I like Daniele's idea regarding an update on RepsNext. We could do an update now and then another one after London when we have results from the Design sprints.

I've updated the timeline in the description to be more realistic.

**Comment by ioana-chiorean** [comment]
- [ ] Reps Next 
- [ ] Q1 and Q2 ROMs 
- [ ] Review team? cc - @couci 
- [ ] MozCommunity Spaces with more than 209 events per month?  cc @brianking

**Comment by Mte90** [comment]
I think that also this https://discourse.mozilla-community.org/t/repsnext-improvements-overview/10251/1 can be a part of the monday call.

**Comment by ioana-chiorean** [comment]
@MichaelKohler how do you want to proceed  here?

**Comment by MichaelKohler** [comment]
I would suggest having a second follow-up blog post for the one we did to answer the questions from the Discourse thread. Then we could have a slide deck with the most important changes that could be presented in the Monday call to get visibility.

**Comment by Mte90** [comment]
During the European gathering we presented the Reps program the question about it was:

- Where I can find information about the program?
- There are rep in country X?
- What is the role of a rep?

So I think that we need to do promotion about the program itself in other channels, maybe many people that watch the monday call know the program but because there is now a people change is better to promote it.

**Comment by MichaelKohler** [comment]
Let's create a slide deck with the proposed changes, what we already have implemented and what our next steps will be and present this in a Monday weekly meeting next month

**Comment by MichaelKohler** [comment]
@ioana-chiorean do you agree?

**Comment by ioana-chiorean** [comment]
Sounds good :D

**Comment by MichaelKohler** [comment]
I'd suggest to wait until after Hawaii so we can include the Resources track as well. Let's make this the following topics:

* What is RepsNext? How did we start this?
* Overview of changes we have already implemented
* Changes to come (timeline decided in Hawaii)

**Comment by ioana-chiorean** [comment]
ok

**Comment by MichaelKohler** [comment]
@ioana-chiorean thoughts on this?

**Comment by MichaelKohler** [comment]
Closing in favor of #193
