### ISSUE TITLE
June Newsletter

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#190]
## Goal: 
The newsletter for June is sent. 

## Roles:
Responsible: @AlexLakatos 
Accountable: Reps Council
Supporting: @elioqoshi
Informed: All Reps

## Required: 
- [ ] Initial ideas have been gathered (@AlexLakatos, Due: June 22th) 
- [ ] Final set of content is decided on (@AlexLakatos, Due: June 25th) 
- [ ] Test newsletter is sent for verification through Council (@AlexLakatos, Due: All Hands a problem here?)
- [ ] Add Mozilla Slack Channel email recipient to the list so the OI team gets it as well (@AlexLakatos, Due: All Hands a problem here?)
- [ ] Newsletter is sent out (@AlexLakatos, Due: All Hands a problem here?)
- [ ] Newsletter is published on GitHub as well (@AlexLakatos, Due: Work Week a problem here?)

**Comment by MichaelKohler** [comment]
And as always, my suggestions in terms of content:

* Reps of the Month - June
* Update about onboarding of new Council members (by that time they will be onboarded)
* RepsNext status update
* Summary about the Reps Path Survey (@MichaelKohler to provide content)
* Firefox Nightly Activate activity (to be released soon!)
* Quick "hi" from the All Hands (we won't be able to share anything valuable yet)
* MozFest (as suggest below, text available)
* RainOfRust (as suggested below, text available)
* Monthly Roundup
  * Weekly Call / Council Call Notes
  * Link to Town Hall (Open Innovation)

**Comment by dvigneshwer** [comment]
Consider adding the following contents,

## MozFest 

### Long Version

The eighth annual [MozFest](https://mozillafestival.org/) will take place in London from Friday October 27 - Sunday October 29. It’s the most ambitious iteration of the festival yet, and will be a key moment for the global network to convene and organise around the health of the Internet. 
 
The festival’s sessions, speakers and workshops are built to foster collaboration across disciplines, borders and continents. We’re ready to face the biggest issues of the day -- from fake news, online harassment and global cyberattacks to inclusion, innovation and web literacy  -- together, with an eye toward practical, open source solutions. 
 
This year, the festival will feature six spaces -- physical and thematic areas of learning based around broad topics related to the health of the Internet  -- delivering a variety of talks, sessions, code sprints and hands-on workshops.
 
From now until August 1, we invite you to [propose a session](https://mozillafestival.org/proposals), workshop or demo that is hands-on, educational and encourages collaboration. Your creativity, expertise, and contribution to the open web will not only benefit the MozFest community, it will enhance your leadership skills and allow you to contribute to a growing global network. 

### Short one

The world's leading festival for the open Internet movement will take place in Ravensbourne College, London on October 27-29, 2017.

MozFest CFP is open and [propose a session](https://mozillafestival.org/proposals) in the six different spaces.

## RainOfRust Initiative

Rain of Rust Campaign, a month-long global campaign which would be specifically focused on the Rust language. It is going to take place in  June 2017 in collaboration with the Rust community.

[More Information](https://blog.mozillaindia.org/1932)

Let me know if you need more details and clarifications.

cc: @couci @geroter

**Comment by MichaelKohler** [comment]
@dvigneshwer thanks for the fast feedback here! So happy to see Reps involvement in the GitHub issues! I think both of those are important topics, I've edited my post above so we have the "Table of Contents" in one place. I think we'll go for the short version though. Thanks so much!

**Comment by MichaelKohler** [comment]
@dvigneshwer do you think you will have a summary of what happened with RainOfRust by the end of June? Would be great to share that one in the Newsletter as we will be sending that one out at the end of the Month (first week of July maybe due to the All Hands)

**Comment by dvigneshwer** [comment]
Yeah, I can publish the detailed insights about the campaign metrics by the first week of July :)

**Comment by MichaelKohler** [comment]
> Yeah, I can publish the detailed insights about the campaign metrics by the first week of July :)

Let's work together on a timing for it :) (we are happy with an initial result and a promise for it to be posted in the Reps discourse channel once final)

**Comment by dvigneshwer** [comment]
> Let's work together on a timing for it :) (we are happy with an initial result and a promise for it to be posted in the Reps discourse channel once final)

Okay, will end of this month do? ( as the campaigns first iterations gets over at that time only)

You can check out the [RainOfRust readme page](https://github.com/MozillaIndia/RustIndia/tree/master/RainOfRust) for more details regarding the goals etc.

**Comment by dvigneshwer** [comment]
### About the event:

Rain of Rust Campaign is a month-long global campaign which specifically focused on the Rust language with a vision of improving community collaboration & participation with the Mozilla's Rust project.

#### Key stats of RainOfRust campaign June 2017:

*  16 offline events across 10 regions globally. [Ref](https://discourse.mozilla-community.org/t/rainofrust-campaign-trailer/15852)
*  4 online meeting which is recorded in Air Mozilla. [Ref](https://discourse.mozilla-community.org/t/rainofrust-online-events-schedule/15970)
* As part of the campaign the RainOfRust has Rust teaching kits which currently has 3 application-oriented activities 
* The Github repo has received more than 500+ views in the last 1 month

Let me know if any modification is required

**Comment by couci** [comment]
An idea is to add key stakeholders we need to send this to
@nukeador what do you have in mind

**Comment by MichaelKohler** [comment]
## Rep of the Month June
(I will sit together with Vigneshwer on Friday to draft the text, so we can publish it)

## Update about onboarding of new Council members
The new Council members have been on-boarded and are fully engaged in Council discussions. Welcome Ankit, Daniele, Elio, Faye! And welcome back Flore!

[Read more](https://blog.mozilla.org/mozillareps/2017/06/23/new-council-members-spring-2017/)

## RepsNext status update
Our "RepsNext" project is in the last steps of being implemented. The Resources track material is created and will be tested soon. We have published an initial list of Leadership resources for all Reps to study. The last few steps of the Coaching Training are being finished now and are soon to be ready to be consumed by all interested Reps. Please share your thoughts and [feedback on Discourse](https://discourse.mozilla-community.org/t/repsnext-update-june-2017/16585)!

[Read more](https://discourse.mozilla-community.org/t/repsnext-update-june-2017/16585)

## Firefox Nightly Activate activity
We just launched the "Using and Testing Firefox Nightly" activity on Activate. As Firefox 57 is coming up, all the help possible is needed!

[Check out the activity!](https://activate.mozilla.community/nightly/)

## New Reps on-boarded
In May and June we have on-boarded 10 new Reps, with 5 more being in the process of finishing the administrative tasks.

![screen shot 2017-06-30 at 03 27 00](https://user-images.githubusercontent.com/330324/27717205-04909ece-5d44-11e7-90c4-0362e3e2b506.png)

[Read more about our new Reps](https://mozilla.github.io/Reps/newreps/)

## Hi from the All Hands
<add picture here!!>

## RainOfRust Initiative

Rain of Rust Campaign, a month-long campaign in India which would be specifically focused on the Rust language. It has taken place in June 2017 in collaboration with the Rust community.

Key stats of RainOfRust campaign June 2017:
* 16 offline events across 10 regions globally. Ref
* 4 online meeting which is recorded in Air Mozilla. Ref
* As part of the campaign the RainOfRust has Rust teaching kits which currently has 3 application-oriented activities
* The Github repo has received more than 500+ views in the last 1 month

[Read More](https://blog.mozillaindia.org/1932)

## Summary about the Reps Path Survey
We recently finished the analysis of the "Reps Path" survey. In total 296 Reps (79.4%) responded to the form. This means that 77 Reps didn't respond and therefore have been moved to Alumni6. All of these Reps are welcome to come back to the Program once the have time for it again. Looking only at the Reps who either responded with "I'm a Mobilizer" or "I'm a Functional Doer", 76.2% (215) responded with "I'm a Mobilizer". 67 responded with "Functional Doer".

[Read all the statistics](https://discourse.mozilla-community.org/t/statistics-about-reps-path-responses/16206)

## Mozilla Festival is coming up!
The world's leading festival for the open Internet movement will take place in Ravensbourne College, London on October 27-29, 2017.

MozFest CFP is open and [propose a session](https://mozillafestival.org/proposals) in the six different spaces.

[Read more](https://mozillafestival.org/proposals)

## Monthly roundup
* Read all about what we did last month in the [Weekly Reps & Council meeting notes](https://discourse.mozilla-community.org/c/reps/meetings).
* All Town Halls pre-All Hands are on [Air Mozilla](https://air.mozilla.org), go check them out!
* Install [Nightly](http://nightly.mozilla.org/) to help make Firefox 57 amazing! :)

**Comment by Mte90** [comment]
I have only a point, we talk about rain of rust as global campaign but I think that will be better say also what countries joined that campaign.
There is not a list of country that joined that campaign.

**Comment by MichaelKohler** [comment]
![screen shot 2017-06-30 at 22 54 20](https://user-images.githubusercontent.com/330324/27753793-626ae0ce-5de7-11e7-8695-947c4683f782.png)

**Comment by AlexLakatos** [comment]
sent!

**Comment by MichaelKohler** [comment]
@AlexLakatos thanks! Could you also add the files to https://github.com/mozilla/Reps/tree/gh-pages/newsletter ? (same goes for the May one).

**Comment by MichaelKohler** [comment]
@AlexLakatos quick ping here

**Comment by MichaelKohler** [comment]
as discussed with Laka, he will be posting it to GitHub with the July one (https://github.com/mozilla/Reps/issues/223)
