### ISSUE TITLE
Reps Applications Screening Round - Week of June 12th

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#191]
## Goal: 
5 new applicants to the Reps programm are screened by a group of screeners and are responded back with our decision/questions that are open.

**Note:** We did a small experiment with a screening group consisting of 4 persons (Council and non-Council). As this was quite successful, we decided in today's Council meeting to do a second round like that and we will discuss about this further in Q3.

## Related Issues & Links: 
#141 
#169 
[Application Screening Sheet ](https://docs.google.com/spreadsheets/d/1xA-iopmysOLW1TFEyw6cVWAzQDhRY_lqPdL9E5Z_Bss/edit#gid=0)- private for obvious reasons

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: Experimental screening group
Informed: Applicants

## Required: 
- [ ] Screen applications (@MichaelKohler, Due: June 20th) 
- [ ] Respond back to applicants (@MichaelKohler, Due: June 21st) 
- [ ] Proceed with Webinar for those who got approved (@MichaelKohler, Due: June 21st)

**Comment by Mte90** [comment]
done my analysis :-)

**Comment by MichaelKohler** [comment]
All applicants have been informed about the decisions and next steps. Thanks to the screening team!
