### ISSUE TITLE
Update Reps Newsletter Template

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/Reps#192]
## Goal: 
Update the Reps Newsletter Template with new branding based on the new Mozilla style. Update Reps Logo and colors.

## Related Issues & Links: 
Depends on the new Reps Logo:
https://github.com/mozilla/OpenDesign/issues/113#issuecomment-308698992

Mozilla Style guide:
https://mozilla.ninja

## Roles:

Responsible:
Elio Qoshi

Accountable:
Reps Council

Supporting:
Alex Lakatos

Consulted:

Informed: 

## Required: 
- Decide on the new Reps logo:
https://github.com/mozilla/OpenDesign/issues/113#issuecomment-308698992

**Comment by couci** [comment]
We are blocked on the new logo right @elioqoshi ?

**Comment by ioana-chiorean** [comment]
@AlexLakatos is you are taking over this again can you ping @elioqoshi for input?

**Comment by yomanpatil** [comment]
We can update things on Discourse while we figure out the sending tool - ruben

**Comment by Mte90** [comment]
this is blocked/pending? right now the new logo was already defined

**Comment by MichaelKohler** [comment]
I'd suggest to close this until we have figured out the tool. As it's on Discourse for now, we don't need it.
