### ISSUE TITLE
2 new comms experiments are being identified

### ISSUE THREAD

**Issue by couci** [mozilla/Reps#193]
## Goal: 
Identify 2 new comms experiments to put on work

## Roles:

Responsible: @AlexLakatos @elioqoshi

Accountable: council

Supporting: @kelimuttu 

Consulted: FB experiments team

Informed: Reps

## Required: 
- [ ] Identify pull of experiments 
- [ ] Vote on the 2 best ones 
- [ ] Run for a month and evaluate

**Comment by MichaelKohler** [comment]
Here are the 3 possible experiments we have on our list so far:

* Use https://github.com/mozillach/gh-projects-content-queue/commits/master for @MozillaReps tweets (automated tweets from GitHub repository issues)
* Change timing of Reps call (was brought up some time ago from Ioana in an issue I can’t find right now)
* We need “external visibility” within Mozilla. One idea would be to go to the Weekly Meeting and provide updates on what Reps are doing

**Comment by MichaelKohler** [comment]
Let's go with the 3 experiments to be run in Q3. Do you agree?

**Comment by couci** [comment]
I am ok with those however it's up to @AlexLakatos and @elioqoshi if they have time to lead those.

**Comment by elioqoshi** [comment]
Let's quickly catch up on this at the All-Hands

**Comment by MichaelKohler** [comment]
I think we should go with those 3, @AlexLakatos or @elioqoshi could you create a voting if in doubt?

Next step would then be to phrase hypothesis we can test during the experiment and document them on https://wiki.mozilla.org/ReMo/Communication to move forward.

**Comment by elioqoshi** [comment]
I'd be happy to go ahead with these. How do you think should the weekly meeting involvement be like? Should we add something to the Wiki page of each meeting or should someone from us present it every week? Latter is doable, but needs some commitment

**Comment by MichaelKohler** [comment]
I think we don't need weekly engagement. Monthly presentations should be fine and we can take the content of the newsletter for this. If we want to send out an update in between those, non-verbal updates on the wiki should be fine.

**Comment by MichaelKohler** [comment]
@elioqoshi could you please create new issues for each of those experiments so we can move ahead with those? Each issue should have "phrase hypothesis and document on ReMo/Communications" as first step.

**Comment by elioqoshi** [comment]
Sorry, I missed this. Will make sure to get this done within this week.

**Comment by MichaelKohler** [comment]
Filing new issues per communication experiment is the last step here, so this issue here can be closed once this is done.

**Comment by elioqoshi** [comment]
Done.
