### ISSUE TITLE
Coaching Training is implemented

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#194]
## Goal: 
The Coaching training is available for all Reps to take.

## Related Issues & Links: 
#137 

## Roles:

Responsible: @fayetandog
Accountable: Reps Council
Supporting: @michaelkohler
Informed: All Reps

## Working Document

https://docs.google.com/document/d/12uuGrEGdd593UPDuWfH1ZPxB1ES7ywfFUyUM7XHPebE/edit?usp=sharing

## Training material

http://deimidis.github.io/community_curriculum/index.html#introduction

## Required: 
- [x] Put Training Material on Teachable (@couci, Due: July 15th) 
- [x] Review Wiki pages drafts (@fayetandog, Due: June 25th)
- [x] Write clear expectations of how narrative should look like (@fayetandog, Due: June 25th)
- [x] Publish Wiki pages (@MichaelKohler, Due: July 15th) 
- [x] Communicate new Wiki pages and process to Reps (@fayetandog, Due: June 20th)
- [ ] Clean up Mentoring Wiki pages (@MichaelKohler, Due: July 25th)
- [x] Decide on process and format of Coaching Practice Week (@fayetandog, Due: July 20th)

**Comment by MichaelKohler** [comment]
Current “Mentoring” documents to be updated to reflect Coaching
* ReMo/Mentors/SelectionProcess → to be incorporated directly in the Coaching wiki page
* ReMo/SOPs/Mentoring → maybe archive so we still have it and point to the Coaching wiki page?
* ReMo/SOPs/Mentoring/Orientation/Call → should be covered by the training material, not needed anymore for onboarding
* ReMo/SOPs/Mentoring_Training → obsolete with coaching page
* ReMo/SOPs/Mentoring/Reassigning → should be incorporated for Coaching page
* ReMo/Mentors → obsolete

**Comment by MichaelKohler** [comment]
Faye will created a voting for the draft, so we could add those pages to the Wiki. Then we can continue with the communication once the training is on teachable. Will check with Konstantina about the status there.

**Comment by MichaelKohler** [comment]
Council voting has been created: https://reps.mozilla.org/v/coaching-training-content/

**Comment by fayepal** [comment]
Updated the working document with the planning of the Coaching Practice Week

**Comment by MichaelKohler** [comment]
We have agreed on the Wiki pages content. Next steps:

* Update the pages on the wiki according to the draft
* Write the announcement
* Put everything on teachable
* Send out the announcement

I've changed the deadlines accordingly.

(See comment 0 for responsibilities)

**Comment by MichaelKohler** [comment]
Moving this to "Council Feedback Needed" for an initial brainstorming on how the Practise Week might look like.

**Comment by MichaelKohler** [comment]
Wiki pages are published (but please note, currently the training is not open yet):

https://wiki.mozilla.org/ReMo/Coaching
https://wiki.mozilla.org/ReMo/Coaching/Training

@couci for Teachable, here are the different sections to add

**Listening to others:** http://deimidis.github.io/community_curriculum/index.html#three-levels-of-listening
**Giving feedback:** http://deimidis.github.io/community_curriculum/index.html#giving-feedback
**GROW model:** http://deimidis.github.io/community_curriculum/index.html#structuring-the-coaching-session-grow and http://deimidis.github.io/community_curriculum/index.html#how-to-run-a-super-quick-coaching-session and http://deimidis.github.io/community_curriculum/index.html#the-power-of-questions

At the end of each section, please add a note about the narrative (that it can be done now or at the end of the full thing), linking to https://wiki.mozilla.org/ReMo/Coaching/Training#Write_a_narrative

**Comment by couci** [comment]
cool, quick q is there an introduction you would like to put in the beginning of the lesson?

**Comment by MichaelKohler** [comment]
Good question, what about the intro we use on the wiki page?

> With the RepsNext initiative, we decided to restructure our approach on how we do Mentorship in the Reps program. Some Coaches have already been onboarded at the end of 2016 to test and improve the training material. The goal is to have existing Mentors work as Coaches, as well as allowing non-Mentors to take the Coaching training to become a Coach.

**Comment by MichaelKohler** [comment]
@fayetandog and I will come up with a full proposal regarding the Practise Week.

In the mean time, the next step is to put this on teachable.

**Comment by couci** [comment]
@kelimuttu and I will take care of the Teachable part. Estimated delivery: August 3rd

**Comment by MichaelKohler** [comment]
@couci @fayetandog we currently have a "Coaching" subcategory in Discourse. This is currently private, and I would like to not expose the content of that. However, we will need a category for the narratives. Should we just request a new subcategory "Coaching Training"?

**Comment by MichaelKohler** [comment]
Addition: the wiki currently states to post a reply to an existing topic, but I think this might get very crowded. I think a new category would be better. Thoughts?

**Comment by couci** [comment]
I think subcategory is a good idea

**Comment by kelimuttu** [comment]
Course has been made in Teachable, but isn't public yet. @couci can you review it?

**Comment by MichaelKohler** [comment]
Thanks Kiki! I've just requested a subcategory for Discourse as well: https://bugzilla.mozilla.org/show_bug.cgi?id=1386217

**Comment by couci** [comment]
this looks great, just a note: I would advice it to change it from Coaching for Mozillians to Coaching training for Mozilla Reps Mentors so it's crystal clear what it is about

**Comment by kelimuttu** [comment]
Revised the title on Teachable

**Comment by couci** [comment]
material is now live on teachable

**Comment by MichaelKohler** [comment]
Training is open for everyone: https://discourse.mozilla.org/t/reps-coaches-training-is-now-open/18735/3

Created https://github.com/mozilla/Reps/issues/250 for the first coaching practice week as this is the next step: https://github.com/mozilla/Reps/issues/250

**Comment by MichaelKohler** [comment]
Practice Week initial draft here: https://wiki.mozilla.org/ReMo/Coaching/Practice_Week
