### ISSUE TITLE
Evaluate FB Experiment

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#196]
## Goal: 
The FB Experiment is evaluated and if successful, moved out of the "Experiment" phase and officially documented.

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: FB Experiment Team
Consulted:
Informed: All Reps

## Required: 
- [x] Ask FB Team for latest numbers and recommendation (@MichaelKohler, Due: June 23th) 
- [x] Evaluate Experiment (@MichaelKohler, Due: June 28th) 
- [x] Decide on Continuation (Council, Due: June 29th)
- [x] Update Communication Page to include outcome (and Team) (@MichaelKohler, Due: June 30th)

**Comment by MichaelKohler** [comment]
Reached out to Srushtika to get a first evaluation and recommendation from her.

**Comment by Srushtika** [comment]
Hi @MichaelKohler !
Thanks for reaching out. The FB experiment has been amazing and the numbers look great to me !

Here are a few insights:

1. Average number of people who visited the Reps FB page daily: **2300**
2. Total number of people who liked the page: **3843**
3. Maximum page engagements: **753**
4. Number of people who gave negative feedback on the page: **1**
5. The number of times the posts were seen in News Feed or ticker or on visits to the Page: **19029**

The team: @yomanpatil, @vi5halc, @yofiesetiawan, @Srushtika
Thanks to @ioana-chiorean, @couci and @kelimuttu for the tremendous support with the guidelines and approval.

**Comment by MichaelKohler** [comment]
Thanks! What is the timeframe on metric 5? Unfortunately I can't open the data you sent me right now.

Also, how do the numbers look relatively compared to before the experiment? Likes and other engagements like sharing would be quite interesting here.

Thanks again, looks very good so far!

**Comment by Srushtika** [comment]
The timeframe on metric 5 is 28 days.

Unfortunately, the initial metrics weren't tracked before the start of the experiment and FB only shows data which is the aggregate of all data till now or the data that is 28 days old. Apologies for the inconvenience !

**Comment by MichaelKohler** [comment]
Wow, I would not have expected that to be 29 days. 

I would say, let's keep this going as normal process and look back on the metrics in 3 months (would be great if we can save the data every month).

Rest of the council: please give tour thoughts here. If there are no concerns, I will update the wiki to list is as official project on the communication page indicating the responsible team. I will do so by the end of next weeks or the beginning of the week after that if I can't find 10 minutes at the all hands for it.

**Comment by MichaelKohler** [comment]
Thanks again, I've updated the https://wiki.mozilla.org/ReMo/Communication page.
