### ISSUE TITLE
Define Q3 Goals and Budget Allocation

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#197]
## Goal: 
The Goals for Q3 as well as the Budget Allocation according to it are documented and communicated.

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: Reps Council
Consulted: CDT
Informed: All Reps

## Required: 
- [x] Initial Discussion about Goals & Budget (@MichaelKohler, Due: June 30th) 
- [ ] Initial draft is communicated (@MichaelKohler, Due: July 5th) 
- [x] Rest of the OKRs are defined according to CDT goals (Ankit, Due: July 27th)
- [ ] Finalized draft with all OKRs is discussed (@MichaelKohler, Due: July 29th)
- [ ] Voting is created (@MichaelKohler, Due: July 29th)
- [ ] Goals and Budget Allocation are finalized and changes communicated (@MichaelKohler, Due: Aug 5th)

**Comment by MichaelKohler** [comment]
Draft here: https://docs.google.com/document/d/1spJ_iOLGxsDYUUp6-5E_MAAvbnrmkU576rRrhANQteY/edit# (to be discussed)

**Comment by MichaelKohler** [comment]
The initial draft is done, but we will need to define Activate and Mobilizers depending on the CDT goals. I've updated the timeline accordingly. Ankit will represent us in the CDT OKR process. Once this is done, we can adapt our OKRs and communicate them.

**Comment by MichaelKohler** [comment]
Ankit is owning this.

**Comment by ankitgadgil** [comment]
The OKRs have been shared with the Open Innovation Team via email.

**Comment by MichaelKohler** [comment]
see #241
