### ISSUE TITLE
Re-assign "orphan" mentees

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#199]
## Goal: 
"Orphaned" mentees are reassigned to new coaches.

## Related Issues & Links:
Overview: http://mentors.michaelkohler.info/

## Roles:

Responsible: @fayetandog 
Accountable: Reps Council

## Required: 
- [ ] TBD, currently not priority 1 as we want to finish the coaching training first (it's a dependency)

**Comment by MichaelKohler** [comment]
We have started to assign new Reps to new coaches. There are still a few new Reps to be assigned first before we can move on to orphaned existing Reps.

**Comment by couci** [comment]
@MichaelKohler how many "orphans" we have now?

**Comment by MichaelKohler** [comment]
https://docs.google.com/spreadsheets/d/1Fw36FDfGDMfgCWJDWZ7JDdk4FsxMaD_auSS4YzeADkg/edit#gid=0 (please do not edit!)

**Total: 60**, including:
new Reps: 6 (temp assigned to me)
temporarily assigned to somebody (either due to Portal making editor do it or request by Rep): 4

**Comment by Mte90** [comment]
There is a new interface now in the dashbaord that has better and updated numbers.

Now there are less reps without mentor and is tiem to work on reps with mentors in alumni.

**Comment by Mte90** [comment]
Just as update, I already started to cleanup reps with wrong mentors and reassinging mentors.

**Comment by Mte90** [comment]
Now I am working on assigning more reps to mentor with few and checking inactive mentors to reactivate them.

**Comment by Mte90** [comment]
we have now less of 30 reps without a mentor, this task is not still finished but we are moving on.

**Comment by Mte90** [comment]
less of 25 :-)

**Comment by Mte90** [comment]
We have right now 25 reps without a mentor  but probably with https://github.com/mozilla/Reps/issues/375 there will be less.

**Comment by ioana-chiorean** [comment]
Who is now assigned here? :S

**Comment by Timmaks** [comment]
i think this issue can be closed, all reps have a mentor at the moment
