### ISSUE TITLE
Draft for mentorship proposal

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#2]
## Goal:

Set up a draft with a proposal for mentorship
## Success:

Draft is defined and shared
## Roles:

Owner: @shahidfarooqui @deimidis
Involved: 
## Required:
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by nukeador** [comment]
@shahidfarooqui  please update the details in this issue. Thanks! :)

**Comment by nukeador** [comment]
@shahidfarooqui @deimidis please update this one. Thanks!

**Comment by shahidfarooqui** [comment]
We are working on to finalize the document. We should be able to share it with the council sometime today/tomorrow for their input/feedback.

**Comment by shahidfarooqui** [comment]
Document has been shared with the council for their input/feedback/suggestion on or before 13 May 2016.

**Comment by Mte90** [comment]
This draft is available? I have to study it for https://github.com/mozilla/Reps/issues/21

**Comment by nukeador** [comment]
@deimidis Let's update this to reflect where we are.

**Comment by MichaelKohler** [comment]
As we're currently onboarding new mentors I'd say we're on track here, but nevertheless I think we'll need to have a finalized document for this so we can put it on the Wiki in the end.

**Comment by nukeador** [comment]
Ping @deimidis

**Comment by MichaelKohler** [comment]
@nukeador @deimidis do I see this correctly that for now all we would need to do is create a wiki page with all the information on how we're currently doing coaching on it? (this is depending on how we can make it self-driving, right?) 

Is that the only thing left here apart from discussions we need to have regarding coaching in general? In that case I'd create a seperate issues for that. What do you think?

**Comment by MichaelKohler** [comment]
^ @nukeador 

Is that it for now? Of course this will be influenced by the Leadership Toolkit as well as what we come up with 2017 strategy in terms of coaching in a broader setting than just Reps.

**Comment by nukeador** [comment]
@deimidis can comment better on this.

**Comment by MichaelKohler** [comment]
Let's come up with a plan for Coaching and create a new issue here.
