### ISSUE TITLE
New description for Reps

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#20]
## Goal:

We've come up with a new description of what Reps is according to RepsNext, which will be put on the Wiki and the Reps Portal.
## Related Issues & Links:

Reps Identity & Communications WG
## Roles:
- Owner: @MichaelKohler
- Involved: WG
## Required:
- [ ] Gather ideas (WG, Due: May 15th) 
- [ ] Create 3 different texts for experimentation (WG, Due: May 22nd) 
- [ ] Write final text to agree upon in London (WG, Due: June 11th)

**Comment by ioana-chiorean** [comment]
Isn't this something we can get from the work already done on reps next?

**Comment by MichaelKohler** [comment]
> Isn't this something we can get from the work already done on reps next?

This will be a huge part of it, but still we need to come up with some decent description we can put on the Portal main page and other places where Reps is introduced.

**Comment by nukeador** [comment]
Draft idea: The Mozilla Reps program is a volunteer participation platform that aims to empower mozillians in their journey, helping them grow and unlocking their potential to empower others.

**Comment by ioana-chiorean** [comment]
"to empower mozillians ..  to empower others." hmm

**Comment by Mte90** [comment]
My idea:
```
The Mozilla Reps program is a volunteer participation platform to improve the participation on your community with many activities like event organizations or recruiting and mentor.
```

For me is this, when I have to explain what means I say that I am the reference inside and outside about everything in Mozilla for my community but I think that we have to add few example directly in the description.

**Comment by MichaelKohler** [comment]
Extending Nuke's idea and taking Ioana's feedback into account:

```
The Mozilla Reps program is a volunteer participation platform that aims to empower mozillians in their journey contributing to Mozilla, helping them grow and unlocking their potential to share their skills with others.
```

**Comment by Mte90** [comment]
Maybe replace aims with want can be a intensifier

**Comment by MichaelKohler** [comment]
Are there any other ideas / suggestions?

**Comment by nukeador** [comment]
I'm working on a vision document for RepsNext, I'm still trying to figure out all pieces and concepts, you can assign this to me and I will come with a more detailed proposal: Vision and detailed vision.

**Comment by MichaelKohler** [comment]
Sounds good! Assigning to you in that case :)

**Comment by nukeador** [comment]
I have been consolidating the vision for the program moving forward and I'll publish a blog post about it soon. Let's close this and keep working on that with Council.

**Comment by MichaelKohler** [comment]
@nukeador I don't think the blog post is the only thing to do here. Shouldn't we also update the description on the Portal?

**Comment by ioana-chiorean** [comment]
That was the plan ...

**Comment by nukeador** [comment]
Sorry, I though I commented here the iteration for the description:

"The Reps program aims to be a representation of the mozillian population and regional communities, formed and governed by core trusted mozillians that through the program grow in their leadership skills, represent Mozilla in their country, have privileged access to internal information and strategy, empower others to support Mozilla’s top initiatives in a more effective and aligned way, as well as provide local insight and needs as a key strategic advantage for the organization."

**Comment by Mte90** [comment]
uhm is very long as description, maybe we can cut something to simplify what is a Rep?

**Comment by MichaelKohler** [comment]
@nukeador do you think we could update the Main wiki page and the description on the reps portal with this?

**Comment by nukeador** [comment]
I'm working also at participation level to better shape the core mobilizer role, so I think we should wait after Hawaii work to come back with a final version here.

**Comment by couci** [comment]
@nukeador Is this still ongoing? Please leave a comment or this will be closed in 24h

**Comment by Mte90** [comment]
Maybe after leadership initiative we can define if we need a new description, we talked a lot about this point but we didn't chosen anything about it

**Comment by couci** [comment]
Let's close this since the definition will be redefined from the Mission Driven Mozillians project.
