### ISSUE TITLE
Publish RepsNext Status Update

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#200]
## Goal: 
A RepsNext status update is published before the All Hands.

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting:
Consulted:
Informed: 

## Required: 
- [x] Finish new graphic as in last blog post (@MichaelKohler, Due: June 20th) 
- [ ] Publish blog post / Discourse / reps-general / Telegram / other stakeholders (@MichaelKohler, Due: June 21st)

**Comment by MichaelKohler** [comment]
Added the updated graphic to https://docs.google.com/document/d/1-sc1H1irmH9MXF79abVYm-41XBV2iqUIfCjbJ1rOICM/edit . Council, please do a final review. I will publish tomorrow evening if there are no concerns.

**Comment by couci** [comment]
LGTM

**Comment by MichaelKohler** [comment]
Discourse placeholder: https://discourse.mozilla-community.org/t/repsnext-update-june-2017/16585

@couci please approve the blog post on WP so we can share this more broadly on Telegram and reps-general as well. I will update the discourse topic once done.

**Comment by couci** [comment]
done :)

**Comment by MichaelKohler** [comment]
https://blog.mozilla.org/mozillareps/2017/06/22/repsnext-status-update-june-2017/

Changed the topic in Discourse to include the link. Also sent  notification to reps-general and Telegram.
