### ISSUE TITLE
Leadership - Update wiki  (as last action for the goal)

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#203]
## Goal: 
The ReMo main page is updated to include a link to the Leadership resources.

## Related Issues & Links: 
#189 

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council

## Required: 
- [ ] Update Main Wiki page (@MichaelKohler, Due: July 5th)

**Comment by Mte90** [comment]
Template updated: https://wiki.mozilla.org/Template:Remonav
The other pages are not updating (https://wiki.mozilla.org/ReMo) I don't know if it is for caching or we need to updated all the pages for the template but is done.

**Comment by MichaelKohler** [comment]
Let's check this in a few days and if it still doesn't work, let's figure out how we can circumvent the cache.

**Comment by MichaelKohler** [comment]
Works for me now, seems like a cache issue. Closing this now, thanks for doing this!
