### ISSUE TITLE
Onboarding - document the criteria

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#204]
Assignee: @ankitgadgil and @Mte90 

## Goal: 
Improve the criteria list for onboarding mozillians on the program

## Related Issues & Links: 
* Criteria: https://docs.google.com/document/d/1rx-CWiziCdT3n0CzKKpmrq3Y4tr8nPf6aO4oRRwAJio/edit

## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [x] Look the actual criteria on the wiki (owner, Due: Lug 1th) 
- [x] Create a document with the new list of criteria (owner, Due: Lug 1th) 
- [ ] Review that document (owner, Due: XXX)

**Comment by Mte90** [comment]
The ideal roadmap:

* Look the actual criteria on the wiki
* Create a document with the new list of criteria
* Review that document
* For mozillians to check the description field and reminder for profiles with missing data

**Comment by Mte90** [comment]
I created a document: https://docs.google.com/document/d/1rx-CWiziCdT3n0CzKKpmrq3Y4tr8nPf6aO4oRRwAJio/edit

I already started to write few stuff to check later

**Comment by MichaelKohler** [comment]
As Daniele is busy this week, I'll publish this.

**Comment by MichaelKohler** [comment]
Published on https://wiki.mozilla.org/ReMo/Application_Process/Selection_Criteria and added a short Discourse topic: https://discourse.mozilla-community.org/t/reps-application-criteria-updated/17387
