### ISSUE TITLE
Update metrics face to the survey to be sent

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#206]
## Goal: 
[One line goal description] 

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by nukeador** [comment]
Context? I don't get what is this about, sorry.

**Comment by ioana-chiorean** [comment]
Was one of the follow up from the Goals check. I do not have any other.
