### ISSUE TITLE
Feedback elections 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#207]
## Goal: 
Find out what went well and what can be improved from these elections in order to prepare the next ones. 

## Related Issues & Links: 
* #114 

## Roles:
Responsible: @ioana-chiorean
Accountable: @ioana-chiorean
Supporting:  Peers 
Consulted: 
Informed: Reps , Council & Peers

## Required: 
- [x] Create [form](https://goo.gl/forms/ZWKblRySYjIUwLPD3) (owner, Due: Jul 1st) 
- [x] Send out the form owner, Due: Jul 1st) 
- [ ] Close the form (owner, Due Jul 18th) 
- [ ] Share the learning (owner, Due: Aug 7th)

**Comment by ioana-chiorean** [comment]
Form created and sent out! 
Added it in the newsletter too.

**Comment by Mte90** [comment]
Updates for this task?

**Comment by ioana-chiorean** [comment]
@Mte90 Will centralize the feedback and make a doc for next week's meeting - council one.

**Comment by MichaelKohler** [comment]
This is done
