### ISSUE TITLE
Council Elections - Autumn 2017

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#208]
## Goal:
- Hold the council election in order to occupy the spots that are free after the term of one year is ending for:

🎓 @AlexLakatos 
🎓 @MichaelKohler 
🎓 

## Success:
- The elections take place and we have _ new council members

## Related Issues & Links:
- Previous Elections #114, #15 
 
## Roles:
Owner: @ioana-chiorean 
Involved: @couci, Reps Peers 
Informed: @nukeador

## Required:
- [x] Prepare [the timeline](https://github.com/mozilla/Reps/issues/208#issuecomment-339637554) and the steps (@ioana-chiorean, Due: October 9th)
- [x] Send out [the announcement](https://discourse.mozilla.org/t/important-council-elections-autum-2017-please-read/20884) (@ioana-chiorean, Due: October 9th)
- [x] Start gathering nominations (@ioana-chiorean, Due: October 9th)
- [ ] Close nominations (@ioana-chiorean, Due: October 16th)
- [x] Prepare Q&A (@ioana-chiorean, Due: October 16th)
- [ ] Run Q&A (@ioana-chiorean, Due: October 17th)
- [ ] Start Voting (@ioana-chiorean, Due: October 24th)
- [ ] Close voting and announce results.  (@ioana-chiorean, Due: October 31st)

##Updates required:
- [ ] History Page [10th Council ]( )
- [ ] Create [11th entry]( )
- [ ] Update < if necessary> [requirements for council members]( ) 
- [ ] Update [tasks and requirements]( )

**Comment by Mte90** [comment]
We are a little bit late for this one?

**Comment by ioana-chiorean** [comment]
@Mte90 it was more like a place holder. Id id update it with dates starting next week - if we want to start then. 
We can also postpone it one more week to study more the feedback.

**Comment by ioana-chiorean** [comment]
@Mte90 it was more like a place holder. Id id update it with dates starting next week - if we want to start then. 
We can also postpone it one more week to study more the feedback.

**Comment by couci** [comment]
jumping in this conversation, based on what I read from the comments I don't see anything that we can't implement on the go or a huge flag.
I think we should start next week

**Comment by Mte90** [comment]
This can create issues with the november meeting in berlin?

**Comment by couci** [comment]
no, we've already discussed it with Ioana and based on the current timeline the new council members would not be fully onboarded to participate there.

**Comment by ioana-chiorean** [comment]
OK - then I will prepare things for next week !

**Comment by ioana-chiorean** [comment]
Proposed timeline (all times in 09:00 UTC):

October 27th - call for candidates
November 3rd - call closes
November 3rd - start of campaign period
* candidates are given 4 days to answer questions and post them on their profile page
* candidates are given 4 days to publish a 30-120 seconds campaign video

November 6th - deadline for answers and videos to be published
November 6th - voting starts
November 12th - voting ends - new elected members are announced
November 13th - the Council Onboarding begins

**Comment by ioana-chiorean** [comment]
Announcement is up: https://discourse.mozilla.org/t/important-council-elections-autum-2017-please-read/20884

**Comment by ioana-chiorean** [comment]
Mail for second step was sent out to the six applicants. We will be tracking their progress here. 

1. [Prathamesh Chavan](https://reps.mozilla.org/u/prathamesh/)
  - [x]  [Video](https://youtu.be/Wrb86iR3y0s)
  - [x]  Answers
2.  [Vishal Chavan](https://reps.mozilla.org/u/vi5halc/)
  - [ ]  [Video](https://youtu.be/Wrb86iR3y0s)
  - [ ]  Answers
3.  [Mayur Patil](https://reps.mozilla.org/u/yomanpatil)
  - [x]  [Video](https://youtu.be/gNXxXljslYI)
  - [ ]  Answers
4.  [Hossain Al Ikram](https://reps.mozilla.org/u/hossainalikram/)
  - [x] [ Video](https://vimeo.com/241842641)
  - [x]  Answers
5.  [Edoardo Viola](https://reps.mozilla.org/u/edovio/)
  - [x]  Video
  - [x]  Answers
6.  [Yuliana Reyna Jiménez](https://reps.mozilla.org/u/Tuxxy/)
  - [x]  Video
  - [ ]  Answers

Their replies [are tracked here](https://discourse.mozilla.org/t/important-council-elections-november-2017-nominee-q-a/21201).

Updated timeline:

- November 3rd - call closes
- November 4th - start of campaign period
  -  candidates are given 5 days to answer questions and post them on their profile page
  -  candidates are given 5 days to publish a 30-120 seconds campaign video
-  November 8th - deadline for answers and videos to be published
-  November 8th - voting starts
-  November 14th - voting ends - new elected members are announced
-  November 15th - the Council Onboarding begins

**Comment by ioana-chiorean** [comment]
This was done. Announcement was made here: https://discourse.mozilla.org/t/important-council-elections-november-2017-results-and-next-steps/21727
