### ISSUE TITLE
Set up a regional coach group

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#21]
## Goal: 
Set up a group of Reps to support regional communities

## Success:
A diverse group is set up and empowered to start supporting regional communities

## Related Issues & Links: 
Doc: https://docs.google.com/document/d/18ikGySz8Jt95AD3YyQspxDoV0remrHbpiyDNY3Ef-84/edit

## Roles:
* Owner: @Mte90 
* Involved: @ioana-chiorean @brianking @iamVP7 @MichaelKohler @nukeador @rara79 

## Required: 
- [x] Define a Council member to own this effort.
- [x] Define the list of countries in each region
- [x] Write a discourse post to share proposal for feedback [Daniele] (https://discourse.mozilla-community.org/t/reps-regional-coach-group-we-need-your-feedback/9105/ )
- [x] Form for candidate self-nomination [Daniele]
- [x] Get feedback from Council on the call out
- [x] Once we have agreement and Ok from Council, do a call out for candidates (google form) + encourage shoulder tapping to potential candidates (with the help of mentors) (July 13th)
- [x] Council + Daniele to decide on 1-2 people per region. (July 20th)
- [ ] Set up an initial call with the candidates selected (Week of July xxth)
- [ ] Provide guidance and a set of first activities to regional coaches. (End of week of July xxth)
- [ ] Define an initial set of Reps to join this group.
- [ ] Define an initial set of activities.
- [ ] Establish a communication plan for the group.
- [ ] Kick-off the group

**Comment by ioana-chiorean** [comment]
I ma interested in this but i do not recall the discussion around it.  ( is this from berlin or after?)

**Comment by nukeador** [comment]
After, basically is to mobilize a group of Reps to support regional communities on top of the support we can bring from staff, since due time constrains we can't support everyone all the time ;-)

**Comment by nukeador** [comment]
@ioana-chiorean if you are interested we can have quick chat to sync. In any case this could be a time consuming task, just checking in case you already have a lot of things on your plate ;-)

**Comment by brianking** [comment]
I want to help here as well.

**Comment by nukeador** [comment]
We need to figure out an owner here and shape this issue requirements since this is going to be probably a goal for the program in Q2.

**Comment by iamVP7** [comment]
Would love to join, and help Reps.

**Comment by ioana-chiorean** [comment]
I am a bit full till after London so i can't that main owner role now but ido want to be included in the talks if possible.

**Comment by MichaelKohler** [comment]
We need somebody to own this tasks and coordinate the efforts here. This doesn't mean to do all the necessary tasks, but to coordinate them. Since we already have 3 people interested in this here, we could start the work.

@Mte90 would you like to coordinate this since you were really involved with the working groups and did a great job? :)

**Comment by Mte90** [comment]
Well after the little mozilla meetup done ad Oscal in Tirana we need something like that because many reps don't have updated from the WGs.

Also I can see in my country direct the various FSAs with their ff club needs a group like this so I'm available.

If it is a consuming task would means that I leave other stuffs I am involved in other projects, now it is the time to improve the Reps program before that is late.

**Comment by MichaelKohler** [comment]
Thanks Daniele, since Ioana, Brian and Viswaprasath will be helping out as well, I don't think this will be too time consuming.

**Comment by Mte90** [comment]
So we have to define a set of initial activities, there are already proposal or suggestion to start?

**Comment by MichaelKohler** [comment]
> So we have to define a set of initial activities, there are already proposal or suggestion to start?

There is nothing yet.

**Comment by Mte90** [comment]
Ok in the next I start with a initial document to discuss :-)

**Comment by Mte90** [comment]
I started to write a document but I haven't understand if it is a new WG or only a group inside the Reps program that have to define some points.
https://docs.google.com/document/d/18ikGySz8Jt95AD3YyQspxDoV0remrHbpiyDNY3Ef-84/edit

**Comment by MichaelKohler** [comment]
> I started to write a document but I haven't understand if it is a new WG or only a group inside the Reps program that have to define some points.

No, this is not a new working group in terms of RepsNext. This will be a group of Reps that help support regional communities with whatever their needs might be (and figuring out those needs might actually be an activity the members of this group could do).

**Comment by mijanurrahman** [comment]
I am interested and I want to help here.

**Comment by nukeador** [comment]
@Mte90 I would start by gathering a list of Reps who want and have time to listen/empower regional communities, at least we would need one per continent (maybe 2 to cover different areas):

* North America
* Central and South America
* Europe
* North Africa and Middle East
* West Africa
* East Africa
* South West Asia and Oceania
* South East Asia
* North Asia

Maybe you can do a call out/form and then select the ones you feel have more time to be the contact person even if others are helping too. The idea is that we could rotate the contact person in each area.

In parallel I would set up a meeting with the people who have expressed their interest in shaping this group here and define initial set of activities, comms and a timeline.

The idea is to have this started before London, how does it sound?

(I will be able to be more involved helping here during the week on June 6th)

Cheers.

**Comment by iamVP7** [comment]
@nukeador  I feel, we have really a big community of Reps in India, like wise we may have in other countries too. So having contributors based on continent won't be enough I think, whats your thought is having more people based on country or countries.

**Comment by nukeador** [comment]
@iamVP7 That's why I suggested some areas instead of just continents. In any case this is a group of people to have a broad visibility of what's going on and support in the region (not working directly inside all communities), we can evaluate how many people per area is needed to cover it.

**Comment by Mte90** [comment]
Ok the idea for zones it's not bad we have to get a list of volunteer for that role.

**Comment by Mte90** [comment]
I'm working for an email to the people interested for a meeting the next week.

**Comment by dricupello** [comment]
Hi guys! I'm interested to be the person in Brazil as regional mobilizer!

**Comment by Mte90** [comment]
I sent the email but actually of all the people written in the first comments of ticket only two have chosen the date for the meeting.

**Comment by MichaelKohler** [comment]
There are now 4 people who filled it out. But seeing that we have at least two more people interested here, here's the doodle: http://doodle.com/poll/a75exncps9r664un

@Mte90 I think the time is in UTC?

**Comment by dricupello** [comment]
Done!

Adriano Cupello

celular:  21 988480481
dricupello@gmail.com

**Comment by anistuhin** [comment]
@Mte90 Is the mail open for all Reps?? I mean where did you send the email?? I didn't notice any email regarding this doodle except here :( Btw I could be a helping hand too if.

**Comment by Mte90** [comment]
I written an email only to the people written in the first comment of the
ticket. Actually I have a Internet problem so I cannot check the time of
the meeting available but I think that now we can define that.

**Comment by anistuhin** [comment]
Okay, does that mean I can join too, cause I'm not one among that four :P ??

**Comment by ShaguftaMethwani** [comment]
I would love to help out on this, just incase if I am not too late yet

**Comment by nukeador** [comment]
Also note that this meeting is just for the people that want to help create the group and activities, the group with Regional Mobilizers itself will be former later and communicated to all Reps.

**Comment by bobreyes** [comment]
@nukeador I can help out for Southeast Asia

**Comment by rowdymehul** [comment]
Would love to join and help! Hope I'm also not late yet!

**Comment by DineshMv** [comment]
I'd love to help. I'm from India. :)

**Comment by Mte90** [comment]
WOW how many people! I hope that all that reps will be involved also in the WGs :-D
The best time is this friday at 7pm UTC+0.
I want to remember to everyone what Nuke said:
```this meeting is just for the people that want to help create the group and activities, the group with Regional Mobilizers itself will be former later and communicated to all Reps.```

**Comment by MichaelKohler** [comment]
Could you send out a calendar invitation to everyone that filled out the doodle? Guess it would make sense to use the MozillaReps Vidyo room and add a link to that in the invitation as well. Thanks!

**Comment by Mte90** [comment]
Ok calendar invitation sent, I hope to invited everyone from that ticket and doodle.
Don't forget to read the links in the invitation (already shared here).

**Comment by Mte90** [comment]
Post on Discourse: https://discourse.mozilla-community.org/t/reps-regional-coach-group-we-need-your-feedback/9105
The next steps: Form candidate to candidate/
The step for this week define the countries for every region, my proposal based where there are [Reps Map](https://reps.mozilla.org/people/#/):

- North America: USA, Canada
- Central America: Mexico, El Salvador, Costa Rica, Panama, Nicaragua, Venezuela, Colombia
- South America: Ecuador, Perŭ, Bolivia, Brazil, Paraguay, Chile, Argentina
- East Europe: Portugal, Spain, Ireland, UK, France, Belgium, Nederlands, Italy, Switzerland, Germany, Czech, Austria, Slovenia
- West Europe: Poland, Hungary, Albania, Kosovo, Serbia, Romanian, Bulgaria, Macedonia, Greek, Ukraine, Lithuanian, Sweden
- North Africa and Middle East: Nigeria, Tunisia, Senegal, Ivory Coast, Ghana, Burkina Faso,
- West Africa: Nigeria, Cameroon, Ugana, Kenya, Rwanda, Madagascar, Zimbabwe, Botswana, Mauritius
- East Africa: Egypt, Jordan, Israel, Turkey, Azerbaijan, Armenia,
- North Asia: India, Nepal, Pakistan, Bangladesh, China, 
- South East Asia: Thailand, Cambodia, Taiwan, 
- Oceania: Philippines, Indonesia, Australia, Vietnam,

**Comment by bobreyes** [comment]
@Mte90 The Philippines, Indonesia and Vietnam are (politically and geographically) part of Southeast Asia (all members of the ASEAN -- http://asean.org/asean/asean-member-states/)

Taiwan, is technically not from Southeast Asia (though we would love to have them in this regional group).

**Comment by anistuhin** [comment]
Little correction:
South Asia: India, Nepal, Pakistan, Bangladesh
North Asia: China

**Comment by Mte90** [comment]
I tried to organize to have regional groups with different countries and not only one but sure we can improve the list :-)

**Comment by Mte90** [comment]
Updated:

- North America: USA, Canada
- Central America: Mexico, El Salvador, Costa Rica, Panama, Nicaragua, Venezuela, Colombia,
- South America: Ecuador, Perŭ, Bolivia, Brazil, Paraguay, Chile, Argentina,
- West Europe: Portugal, Spain, Ireland, UK, France, Belgium, Nederlands, Italy, Switzerland, Germany, Czech, Austria, Slovenia, Sweden,
- East Europe: Poland, Hungary, Albania, Kosovo, Serbia, Romanian, Bulgaria, Macedonia, Greek, Ukraine, Lithuanian,
- North Africa and Middle East: Nigeria, Tunisia, Senegal, Ivory Coast, Ghana, Burkina Faso,
- West Africa: Nigeria, Cameroon, Ugana, Kenya, Rwanda, Madagascar, Zimbabwe, Botswana, Mauritius,
- East Africa: Egypt, Jordan, Israel, Turkey, Azerbaijan, Armenia,
- North Asia: India, Nepal, Pakistan, Bangladesh, China, 
- South Asia: Thailand, Cambodia, Taiwan, Malaysia,
- Oceania: Philippines, Indonesia, Australia, Vietnam,

**Comment by DineshMv** [comment]
@Mte90 India comes under **south Asia**

**Comment by Mte90** [comment]
Done :-)

**Comment by anistuhin** [comment]
sorry, Man follow my previous comment for South Asia and North Asia. It's still need to be updated :) https://github.com/mozilla/Reps/issues/21#issuecomment-224048256

**Comment by mohamed7afezz** [comment]
@Mte90 you miss algeria and How does Senegal, Ivory Coast, Ghana in North Africa and Middle East?
See this: 
https://en.wikipedia.org/wiki/MENA 
http://www.investopedia.com/terms/m/middle-east-and-north-africa-mena.asp

And as we previously talk, we need to make the Arabic countries under one coach to be aware with all Arabic community.

**Comment by Mte90** [comment]
New Update:

- North America: USA, Canada
- Central America: Mexico, El Salvador, Costa Rica, Panama, Nicaragua, Venezuela, Colombia,
- South America: Ecuador, Perŭ, Bolivia, Brazil, Paraguay, Chile, Argentina,
- West Europe: Portugal, Spain, Ireland, UK, France, Belgium, Nederlands, Italy, Switzerland, Germany, Czech, Austria, Slovenia, Sweden,
- East Europe: Poland, Hungary, Albania, Kosovo, Serbia, Romanian, Bulgaria, Macedonia, Greek, Ukraine, Lithuanian,
- North Africa and Middle East: Algeria, Tunisia, Egypt, Jordan, Israel, Turkey, 
- West Africa: Nigeria, Burkina Faso, Senegal, Ivory Coast, Ghana, Nigeria, Cameroon, Azerbaijan, Armenia,
- Central and South Africa: Uganda, Kenya, Rwanda, Madagascar, Zimbabwe, Botswana, Mauritius,
- North Asia: Nepal, Pakistan, Bangladesh, China, 
- South Asia: India, Thailand, Cambodia, Taiwan, Malaysia,
- Oceania: Philippines, Indonesia, Australia, Vietnam,

**Comment by anistuhin** [comment]
Nepal, Pakistan, Bangladesh should not be in north Asia rather in south Asia.

**Comment by Mte90** [comment]
We cannot create a regional couch with only one country so have to change the definitions for the regional area.

**Comment by mijanurrahman** [comment]
@Mte90 
Please correction this:
- South Asia: Bangladesh,Nepal, Pakistan, India
- North Asia: China, Taiwan
- South East Asia: Thailand, Cambodia, Malaysia

**Comment by Mte90** [comment]
First of all this list is based not only on the countries but also on the number of the reps, if we have a country with an huge number of reps we have to do a little regional area else for the regional coaches is it difficult for him to do his job (also there are 1 or plus for that region). 
Also is based for languages and culture, it is not an easy to do it but actually we have to try with few of regional coaches also to understand if that organization can be the same for all the regional area. Maybe where is an huge number of reps we can do a coaches only for a country but we have to start from somewhere because this group it is in a experimental step now.

I reorganized with creating other regional areas most specific.

New List:

- North America: USA, Canada
- Central America: Mexico, El Salvador, Costa Rica, Panama, Nicaragua, Venezuela, Colombia,
- South America: Ecuador, Perŭ, Bolivia, Brazil, Paraguay, Chile, Argentina,
- North Europe: Ireland, UK, France, Belgium, Nederlands, Germany, Poland, Sweden, Ukraine, Lithuanian,
- South Europe: Portugal, Spain, Italy, Switzerland, Austria, Slovenia, Czech, Hungary, 
- South East Europe: Albania, Kosovo, Serbia, Bulgaria, Macedonia, Greek, Romanian,
- North Africa: Algeria, Tunisia, Egypt, 
- North Middle East Africa: Jordan, Israel, Turkey, Azerbaijan, Armenia,
- West Africa: Nigeria, Burkina Faso, Senegal, Ivory Coast, Ghana, Nigeria, 
- Central Africa: Cameroon, Uganda, Kenya, Rwanda,  
- South Africa: Madagascar, Mauritius, Zimbabwe, Botswana,
- North Asia: Nepal, Pakistan, China, Taiwan, Bangladesh, 
- Central Asia: India, Thailand, Cambodia, Malaysia, 
- Oceania: Philippines, Indonesia, Australia, Vietnam,

**Comment by nukeador** [comment]
@Mte90 Let's not over complicate the regions thing. Let's start with the wider approach and see if we need to split into smaller groups. I don't think we need a big group at the beginning to experiment.

My proposal is to have this 9 groups to start now:

* Region 1: North America
* Region 2: Central America, South America
* Region 3: North Europe, South Europe, South East Europe
* Region 4: North Africa, North Middle East Africa
* Region 5: West Africa
* Region 6: Central Africa, South Africa
* Region 7: North Asia
* Region 8: Central Asia
* Region 9: Oceania

I feel we are spending too much time talking about the process rather than getting the group started to operate, which is the important thing here.

Cheers.

**Comment by Mte90** [comment]
I am agree with you I have only improved the list to get the must approval of that but is the second part here.
We have to define the role itself and also what have to do.

**Comment by Mte90** [comment]
Ok I updated the first comment with the actual steps and the future.
The next step for me is start to plan the first activities for a Regional Coach to discuss.
Updates in the doc

**Comment by nukeador** [comment]
@Mte90 can you share the comms with Council so we can move forward this week? Can you also link the working doc in the issue description?

Thanks!

**Comment by Mte90** [comment]
Sure, for tomorrow the council will have an email about it :-)

**Comment by Mte90** [comment]
Added the document in the description (I missed that point), for the comms I don't understand that term :-/

**Comment by ioana-chiorean** [comment]
@Mte90 by "comms" @nukeador means communication ( the communication plan)

**Comment by nukeador** [comment]
Application form closes today.

We will provide Council the full list + a recommendation on the strongest candidates per region.

**Comment by Mte90** [comment]
The list of coaches chosen is on https://discourse.mozilla-community.org/t/new-reps-regional-coaches-august-2016/10104

**Comment by MichaelKohler** [comment]
Since this is ongoing and working well so far from what I can see, I'll close this one. Let's reopen a new one if there is something more to do, but the initial goals here are done.
