### ISSUE TITLE
Document Peers Role 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#211]
## Goal: 
[One line goal description] 

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by couci** [comment]
@ioana-chiorean Is this still ongoing? Please leave a comment or this will be closed in 24h

**Comment by ioana-chiorean** [comment]
it was - we worked on this in Austin. will do it till end of month.

**Comment by MichaelKohler** [comment]
I have started a document about this with the following topics:

1) Reps Council Accountability
2) Peers interaction with Council
3) Peers-internal 

All of these will eventually build up to the Reps Peer role documentation.

**Comment by MichaelKohler** [comment]
Peers role has been documented here: https://wiki.mozilla.org/Reps/Peers#Peers_Role
