### ISSUE TITLE
Update Peers body and wiki 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#212]
## Goal: 
[One line goal description] 

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by couci** [comment]
@ioana-chiorean Is this still ongoing? Please leave a comment or this will be closed in 24h

**Comment by ioana-chiorean** [comment]
yeah. ETA EOM

**Comment by ioana-chiorean** [comment]
Wiki updated https://wiki.mozilla.org/Modules/Mozilla_Reps
