### ISSUE TITLE
Write Summary for All Hands

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#214]
## Goal: 
A summary for Council is written and (public) parts of this is communicated to Reps.

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @ioana-chiorean 

## Required: 
- [x] Create initial draft for review and additions (@MichaelKohler, Due: July 8th) 
- [x] Review and add things to draft (Council, Due: Aug 7th) 
- [x] Create public version of this summary and publish it (@MichaelKohler, Due: July 14th)

**Comment by Mte90** [comment]
Doc in progress: https://docs.google.com/document/d/19k0jXJa1mopz2rTVmFNEurcv5zk3n5okFD9w58UbFw0/edit

**Comment by Mte90** [comment]
Actually is closed because we need to see what is under NDA etc.
Contain few points that I remember and we need to aggregate the notes that we written and a write a blogpost style.

**Comment by Mte90** [comment]
Slides recap of today https://docs.google.com/presentation/d/1ERRvcwQDENLX0NybDL4Ytu-Vt7pNiDmCLYU9Y1724Ho/edit#slide=id.p

**Comment by couci** [comment]
Should we also write a small blog about this?

**Comment by MichaelKohler** [comment]
> Should we also write a small blog about this?

I think that would be a good idea.

**Comment by Mte90** [comment]
The idea of the doc in progress was to write a report with all the stuff we added.
I am not sure if I can work on that this days.

**Comment by MichaelKohler** [comment]
Let's gather all the info, split it up in different topics, write sentences and then break it down to public/not-public and we can publish the result ;)

**Comment by Mte90** [comment]
We already gather the info. I will try to start write in the same document the blogpost

**Comment by Mte90** [comment]
I written a first version but is not very long

**Comment by ioana-chiorean** [comment]
@MichaelKohler which is the best place to share the pictures and the docs?

**Comment by MichaelKohler** [comment]
> @MichaelKohler which is the best place to share the pictures and the docs?

I'd say https://drive.google.com/drive/u/0/folders/0B7SARrfAaErwRXdNNDUzMWxVaEU (this is within the Council folder, therefore not public).

**Comment by ioana-chiorean** [comment]
Done - Thanks!

**Comment by MichaelKohler** [comment]
I've changed a few things, formatted it and added pictures. @Mte90 could you have another look? Also, could another person from Council do a review as well so we can publish by the beginning of next week?

Draft: https://docs.google.com/document/d/19k0jXJa1mopz2rTVmFNEurcv5zk3n5okFD9w58UbFw0/edit# (not public, as this recap document also includes confidential info)

**Comment by Mte90** [comment]
For me it's fine!

**Comment by MichaelKohler** [comment]
* Published on Discourse https://discourse.mozilla-community.org/t/council-at-the-san-francisco-all-hands/17358 and sent to reps-general and Telegram
* Submitted blog post on the blog for review

@couci once you have approved this blog post, you can close this issue. Thanks!

**Comment by couci** [comment]
Published @MichaelKohler https://blog.mozilla.org/mozillareps/2017/07/25/council-at-the-all-hands-in-san-francisco/

**Comment by MichaelKohler** [comment]
Thank you!
