### ISSUE TITLE
Clean up Mentorship Bugzilla component

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#215]
## Goal: 
Clean the queue from old tickets from ticket without actions, close application of reps already joined in the program etc.

## Related Issues & Links: 
All the pending requests: https://bugzilla.mozilla.org/buglist.cgi?product=Mozilla%20Reps&component=Mentorship&resolution=---&list_id=13668340
The pending requests not assigned to @MichaelKohler and not in pending: https://bugzilla.mozilla.org/buglist.cgi?component=Mentorship&email1=me%40michaelkohler.info%20&emailassigned_to1=1&emailtype1=notsubstring&product=Mozilla%20Reps&query_format=advanced&resolution=---&status_whiteboard=%28Pending%20References%29%7C%28next%20screening%20round%29&status_whiteboard_type=notregexp&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cshort_desc%2Cchangeddate%2Cstatus_whiteboard&list_id=13671949

## Roles:

Responsible: @mte90

Accountable:

Supporting: @MichaelKohler 

Consulted:

Informed: 

## Required: 
- [ ] Work on ticket with last update 2015
- [ ] Work on ticket with last update 2016 
- [ ] Work on ticket with last update 2017

**Comment by MichaelKohler** [comment]
Following actions are being taken:

1) Applicant is an active Rep for at least 6 months -> close application bug if there is nothing indicating that the Orientation Period was extended
2) Applicant is active Rep is in Orientation Period (less than 6 months) -> write and ask for update on bug
3) Applicants that joined in the Webinar groups -> leave up to @MichaelKohler
4) Applicants that are now Reps Alumni -> close
5) Applicants that were assigned to a Mentor but there was no action taken -> close and kindly remind to file a new request if still interested
6) Applicants that were never assigned a mentor for screening and request is less than 1 year old -> change status to "NEW" and ask if the applicant is still interested in program
7) Applicants that were never assigned a mentor for screening and request is *more* than 1 year old -> say sorry and kindly ask to file new request with updated info


Slightly better query for this: https://bugzilla.mozilla.org/buglist.cgi?list_id=13672045&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_status%2Cresolution%2Cshort_desc%2Cchangeddate%2Cstatus_whiteboard&resolution=---&emailtype1=notsubstring&status_whiteboard_type=notregexp&query_format=advanced&emailassigned_to1=1&status_whiteboard=%28Pending%20References%29%7C%28next%20screening%20round%29%7C%28Webinar%24%29%7C%28Alumni%29&email1=me%40michaelkohler.info%20&component=Mentorship&product=Mozilla%20Reps

**Comment by MichaelKohler** [comment]
Done!
