### ISSUE TITLE
Add stakeholders to the Newsletter

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#217]
## Goal: 
Major stakeholders to the Reps program are added to the Newsletter recipients. 

## Roles:

Responsible: @couci 
Accountable: Reps Council
Supporting: @elioqoshi @AlexLakatos 

## Required: 
- [ ] List of stakeholders to add is created (@couci, Due: July 25th) 
- [ ] New recipients get the newsletter (@AlexLakatos, Due: July 30th)

**Comment by Mte90** [comment]
Probably is better to do it after the Autumn election

**Comment by couci** [comment]
The newsletter owner needs to be redefined, I am closing this one for now
