### ISSUE TITLE
Submit your "Reps group picture" for the fb cover !

### ISSUE THREAD

**Issue by Srushtika** [mozilla/Reps#218]
## Goal: 
To pick a new cover picture for the Reps fb page. The current one is four years old !

## Related Issues & Links: 
 [Reps FB Page](https://www.facebook.com/MozillaReps/)

## Roles:

Responsible: @Srushtika
Consulted: @couci 

## Details: 
If you have any pictures of a group of reps and you think it would look great as the cover picture of the Facebook page, please submit them on this issue ! The more diverse, the better ;)

**Comment by MichaelKohler** [comment]
Great idea! I think it would make sense to post a Discourse topic for this? Not sure how many people actually see these GitHub issues ;)

**Comment by Srushtika** [comment]
Done @MichaelKohler ! Discourse post link, [here](https://discourse.mozilla-community.org/t/submit-your-reps-group-picture-for-the-fb-cover/17167) !

**Comment by elioqoshi** [comment]
Did we do any Reps photos at the last All-Hands? Anything from this year or past year?

**Comment by MikkCZ** [comment]
There were some pictures of (mostly) Reps groups from the May '16 European gathering in Berlin, but I am no longer in the Telegram group and no idea, where it ended. @brianking, @deimidis or @KaiRo-at may know or have it.

**Comment by ioana-chiorean** [comment]
MozFest and the Gatherings should have nice group pictures.

**Comment by MichaelKohler** [comment]
@Srushtika what is the status here?

**Comment by Srushtika** [comment]
Hi @MichaelKohler ! I'm sorry I haven't been active here - on a small break from participating at Mozilla  due to personal reasons - my very supportive mentor is well informed about the situation. 

However, regarding the issue I haven't received any suggestions about the picture - neither here nor via a separate channel! If we have a generic picture (maybe suggested by the council) - we could upload that. Otherwise, we could close this issue for now!

Thanks!
cc: @Mte90

**Comment by Mte90** [comment]
Thanks for the updates, I think that we can try to promote again in our channels or in case maybe use a photo of the council because I don't think that we have group photo of reps.

**Comment by Mte90** [comment]
We can use a mozilla festival group photo or someone from the all hands, check with Ioana.

**Comment by Mte90** [comment]
We have http://ffp4g1ylyit3jdyti1hqcvtb-wpengine.netdna-ssl.com/mozillareps/files/2018/01/austin.jpg but is vertical.

**Comment by MichaelKohler** [comment]
We also did one at the stage at MozFest. @bacharakis any idea where we could get it?

**Comment by Mte90** [comment]
At the end at fosdem we didn't taken a photo.
We have to evaluate what to do, if close waiting for a new photo in the meantime, seems that there is no pressure on this task.

**Comment by couci** [comment]
No comment so closing
