### ISSUE TITLE
Send out July Newsletter

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#223]
## Goal: 
The newsletter for July is sent. 

## Roles:
Responsible: @AlexLakatos 
Accountable: Reps Council
Supporting: @elioqoshi
Informed: All Reps

## Required: 
- [x] Initial ideas have been gathered (@AlexLakatos, Due: July 25th) 
- [x] Final set of content is decided on (@AlexLakatos, Due: July 27th) 
- [x] Test newsletter is sent for verification through Council (@AlexLakatos, Due: July 29th)
- [x] Newsletter is sent out (@AlexLakatos, Due: August 1st)
- [ ] May Newsletter is published on GitHub (@AlexLakatos, Due: August 1st)
- [ ] June Newsletter is published on GitHub (@AlexLakatos, Due: August 1st)
- [ ] July Newsletter is published on GitHub (@AlexLakatos, Due: August 1st)

**Comment by MichaelKohler** [comment]
As always, some ideas:


* Reps of the Month - July
* Announce new Reps that joined recently
* Status on [Reps Resources track](https://discourse.mozilla-community.org/t/reps-resources-first-training/17208)
* Facebook cover picture - [request for ideas](https://discourse.mozilla-community.org/t/reps-resources-first-training/17208)
* Monthly Roundup
  * Weekly Call / Council Call Notes

Do we have anything else?

**Comment by ioana-chiorean** [comment]
Reminder of call to actions:
- apply to MozFest 
- #RepsMoment cc @Srushtika

**Comment by Srushtika** [comment]
Thanks @ioana-chiorean !
Others- For the context, I'm linking the [initial post](https://discourse.mozilla-community.org/t/reps-moments-are-here/14398) about #RepsMoments. It would be great if you could include a reminder to use the hashtag, in the next issue of the newsletter !

Thanks.

**Comment by MichaelKohler** [comment]
**Reps of the Month - July**
see https://blog.mozilla.org/mozillareps/2017/07/28/rep-of-the-month-july-2017/

**New Reps who joined in June/July**
We are happy to announce 10 new Reps and 2 Reps coming back from Alumni! Welcome!

![screen shot 2017-08-02 at 18 04 32](https://user-images.githubusercontent.com/330324/28882945-14523bb4-77ad-11e7-8545-baa238efc41a.png)

[Read more](http://mozilla.github.io/Reps/newreps/)

**Reps Resources track**
We are currently testing the Reps Resources Track training material. We selected 6 Reps to test the training material while going through it as a normal training. Once the training material is tested and improved we will open up the Resources track for applications. [Read more](https://discourse.mozilla-community.org/t/reps-resources-first-training/17208/3)

**Social Media - Facebook cover ideas & #RepsMoments**
The Reps Facebook page needs a new cover image. The current image is about four years old. If you have a good suggestion, please tell us! [Read more on Discourse](https://discourse.mozilla-community.org/t/submit-your-reps-group-picture-for-the-fb-cover/17167).

Also, we are still running the #RepsMoment initiative. Tag your social posts with that hashtag! [Read more](https://discourse.mozilla-community.org/t/reps-moments-are-here/14398)

 **Monthly Roundup**
* Read all about what we did last month in the [Weekly Reps & Council meeting notes](https://discourse.mozilla-community.org/c/reps/meetings).



------

Is there anything else we would need? @couci @AlexLakatos

**Comment by AlexLakatos** [comment]
Sent out now.

**Comment by MichaelKohler** [comment]
This can be closed once the May/June/July Newsletter are archived on GitHub/Discourse.
