### ISSUE TITLE
Add new Reps to "New Reps" website

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#224]
## Goal: 
All newly on-boarded Reps are listed on http://mozilla.github.io/Reps/newreps/ .

## Related Issues & Links: 
http://mozilla.github.io/Reps/newreps/

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council

## Required: 
- [x] New Reps are added to the website (@MichaelKohler, Due: July 27th) 
- [x] Screenshot for Newsletter is done (@MichaelKohler, Due: July 28th) 
- [x] All missing pictures/bio text are gathered (@MichaelKohler, Due: July 29th)

**Comment by MichaelKohler** [comment]
I've added all new Reps and contacted those with missing information

**Comment by MichaelKohler** [comment]
This is almost ready, I'm just waiting for a profile picture update from one new Rep.

**Comment by MichaelKohler** [comment]
This is done!

**Comment by satvikmaker** [comment]
All new reps are here? From the earlier batch? I find few of us missing, including me :)

**Comment by MichaelKohler** [comment]
Who is missing apart from you? This should include everyone.

You are missing as you don't have a profile yet. For that, refer to our mail thread ;)

**Comment by satvikmaker** [comment]
Yes Michael, got it. Have updated the status. I'm waiting for it.

**Comment by satvikmaker** [comment]
Now, will I be a part of this website? :)

**Comment by MichaelKohler** [comment]
> Now, will I be a part of this website? :)

As you just created your profile, you will be part of this yes. But it might look nicer if you provide a little bit longer biography text ;)

**Comment by satvikmaker** [comment]
Done! Added a decent biography for now :) 
And thanks a lot for being throughout the process.
