### ISSUE TITLE
Reps resources feedback are gathered and improvement are made based on it

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/Reps#226]
## Goal: 
Gather feedback from resources rep training. And actions are taken based on the feedback.

## Related Issues & Links: 
#168 

## Roles:
Responsible: @kelimutu
Accountable: Reps Review team
Supporting: @couci 

## Required: 
- [x] Gather feedback in a doc (@kelimuttu)
- [x] Action items are defined based on the feedback (@kelimuttu)
- [x] Improvement are made based on the action item (@kelimuttu, @couci )

**Comment by kelimuttu** [comment]
The doc is ready [here](https://docs.google.com/document/d/17lgOU6x7-j5HPZ9dIOnFDP9L6HIxX6-fi7D2IXTTmmY/edit?usp=sharing)

**Comment by kelimuttu** [comment]
## Action items:
- [x] Check email notification setting in Teachable
- [x] guidelines on what is accepted or not for receipts
- [x] Other option in case of video call is not possible: telegram discussion
- [x] Send final email for the first training participants

**Comment by couci** [comment]
I think on the last item about vidyo we can ask people in advance: Are you able to participate via vidyo? If not you please let us know, you will then have to join the telegram group discussion (add link)

**Comment by kelimuttu** [comment]
Yeah, just want to take notes here cause we haven't tried it yet. Another note is including not to separate them into group if the participants are less than 5.

**Comment by couci** [comment]
I agree on the idea of not separating if they are less than 5. In that way we keep the conversation going and and we don't spend time changing rooms

**Comment by kelimuttu** [comment]
Email notification was fixed and the wiki for receipt guidance is up in https://wiki.mozilla.org/ReMo/Receipts_guide
