### ISSUE TITLE
Check Onboarding Period status for end of July

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#227]
## Goal: 
Evaluate the reports and activities of 9 Reps whose Orientation Period finishes at the end of July.

## Links:
Webinar Tracking Sheet: https://docs.google.com/spreadsheets/d/16nAeQ8Sr0Zx7FHKl1gjmtddVvZxaAJGLb_4YuHMpvsQ/edit#gid=1047320467 (private to Council as this contains information about applicants)

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @Mte90 
Informed: Onboarding Reps

## Required: 
- [ ] All Orientation Periods expiring are evaluated (owner, Due: Aug 2nd) 
- [ ] Decisions (go, extend, abort) are communicated (@MichaelKohler, Due: Aug 4th)

**Comment by Mte90** [comment]
there is a link for that list of reps?

**Comment by MichaelKohler** [comment]
> there is a link for that list of reps?

This is in our cohort tracking sheet. Added the link in the description.

**Comment by MichaelKohler** [comment]
This is done! There are two applications left, but those are assigned to "real" mentors already, so it's their responsibility to finish the orientation period. I've left a comment on the bug as a reminder for those.

@Mte90 I didn't have any questions, so I didn't contact you. :)
