### ISSUE TITLE
Publish RoM for July

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#228]
## Goal: 
The RoM for July is published.

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @couci @ioana-chiorean 

## Required: 
- [x] Let Mentor write a text about RoM (@MichaelKohler, Due: July 26th) 
- [x] Finalize text (@MichaelKohler, Due: July 29th) 
- [x] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler, Due: July 31st)

**Comment by MichaelKohler** [comment]
Published on the Portal, Discourse (https://discourse.mozilla-community.org/t/rep-of-the-month-july-2017/17474), reps-general and Telegram.

@couci blog post is submitted for review and publication

**Comment by couci** [comment]
done: https://blog.mozilla.org/mozillareps/2017/07/28/rep-of-the-month-july-2017/

**Comment by MichaelKohler** [comment]
Thanks!
