### ISSUE TITLE
[Experiment] implement automated tweets from GitHub repository issues

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/Reps#230]
## Goal: 
Use https://github.com/mozillach/gh-projects-content-queue/commits/master for @mozillareps tweets (automated tweets from GitHub repository issues)

## Related Issues & Links: 
[Reference meta issues and past issues] #193 

## Roles:

Responsible: Elio Qoshi

Accountable: Reps Council

Supporting: Michael Kohler

Consulted:

Informed: 

## Required: 
- [ ] Phrase hypothesis and document experiment on Wiki

**Comment by MichaelKohler** [comment]
As I'm supporting this on the technical level, I've created a [test repository ](https://github.com/MichaelKohler/content-queue-test)and [twitter account](https://twitter.com/reps_cq_test) for initial testing from Council. Council is informed and we will test this within the next few days. Then we will do a quick check with other interested Reps to make sure we don't have major bugs in it. After that, the experiment will start and everybody can propose related content to be tweeted.

**Comment by MichaelKohler** [comment]
@elioqoshi could you please add this experiment to https://wiki.mozilla.org/ReMo/Communication#Experiments (linking to this issue here) and with a hypothesis?

A possible hypothesis could be:
"With a public tool and a streamlined review process for suggested Tweets we can increase the number of authors of MozillaReps tweets to 10 persons."

**Comment by MichaelKohler** [comment]
Next step here: Implement it with the Mozilla Reps account

**Comment by MichaelKohler** [comment]
I will work on this next week.

**Comment by MichaelKohler** [comment]
The Docker container works perfectly well. This means we have the following next steps:

- [x] Create repository for tweets (@MichaelKohler)
- [x] Get Twitter crendentials (@couci)
- [x] Create bug for ParSys to host container
- [ ] Send config to Yousef
- [ ] Send out comms that we are live now

**Comment by MichaelKohler** [comment]
This is currently running on my server. Announcement will go out broadly once we feel confident that this works and has solid infrastructure.

Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1411021 for hosting.

**Comment by MichaelKohler** [comment]
Also documented on https://wiki.mozilla.org/ReMo/Communication#Tweets_by_Reps

**Comment by MichaelKohler** [comment]
This has been announced here: https://discourse.mozilla.org/t/create-tweets-for-the-reps-twitter-account/21047 .
