### ISSUE TITLE
[Experiment] Include Reps update in the Weekly Project Meeting

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/Reps#231]
## Goal: 
Have updates ready to include in the Weekly Project Call. Compile the updates at the Reps Council meeting the week before.

## Related Issues & Links: 
[Reference meta issues and past issues] #193

## Roles:

Responsible: Elio Qoshi

Accountable: Reps Council

Supporting:

Consulted:

Informed: 

## Required: 
- [ ] Phrase hypothesis and document experiment on Wiki

**Comment by Mte90** [comment]
Actually I was doing by myself because I was the person that was representing the council during the call, so maybe we can do that the guy that represent the council in the call have to do that. 
For that I was checking the ticket closed here during the last week, the most recent threads on discourse and something from the council meeting

**Comment by Mte90** [comment]
The best idea is to define a protocol, like the Reps Council Chair after the meeting or during the meeting itself prepare the notes for discourse in that way for the weekly call is done.
I am already doing this and require only to change the wiki page about the role and hope that the council chair publish the notes :-)

I will add that ticket on the next council meeting

**Comment by Mte90** [comment]
The idea from the Reps Council meeting of today is to use the monthly newsletter and share that on the monday call on the first week of every month.
The best idea can be to add the newsletter on the weekly update of the next month (or publish before that)

**Comment by Mte90** [comment]
We will publish soon the new newsletter so we can try with the first one: https://github.com/mozilla/Reps/issues/262

**Comment by couci** [comment]
Is this still ongoing? Please leave a comment or this will be closed in 24h

**Comment by Mte90** [comment]
I think that now is outdated also because the Newsletter proposal will be defined soon also about the content.
