### ISSUE TITLE
[Experiment] Determine best timing for Reps call and change if necessary

### ISSUE THREAD

**Issue by elioqoshi** [mozilla/Reps#232]
## Goal: 
Currently the time of the Reps call is problematic for some reps in various regions who are rarely able to join. We should determine a best timing for the Reps call and change it if necessary.

## Related Issues & Links: 
[Reference meta issues and past issues] #193

## Roles:

Responsible: Elio Qoshi

Accountable: Reps Council

Supporting:

Consulted:

Informed: 

## Required: 
- [ ] Phrase hypothesis and document experiment on Wiki

**Comment by elioqoshi** [comment]
We can create a big Doodle and ask Reps when it's most suitable for them so we can see what would work best. We might also come to the conclusion that we can have 2 different times for the Reps call alternating maybe?

**Comment by Mte90** [comment]
Uhm in other community I saw that they do like for a month in a specific time and the next change.
Maybe for us is not the best option but we can do as example 1st and 3rd week of the month at 16 utc and 2nd and 4nd week at 20 utc in that way we can have periodic reps call for different timezones

**Comment by couci** [comment]
Is this still ongoing? Please leave a comment or this will be closed in 24h

**Comment by Mte90** [comment]
I keep to think about my old comment but seems that @elioqoshi is the owner, so is better to ask him.

**Comment by gaby2300** [comment]
Hello,

I think maybe 20 UTC would be better for non European Reps


Gabriela
QA Mozilla Hispano Team Responsible


http://www.mozilla-hispano.org

**Comment by couci** [comment]
@elioqoshi @gaby2300  can we any of you open a discourse topic with a doodle asking people's opinion?

**Comment by ioana-chiorean** [comment]
Hey @elioqoshi  @gaby2300 - any updates here?

**Comment by Mte90** [comment]
I got a feedback about the timing that is not comfortable and people is missing also the recording and not marking them on the reps portal.

**Comment by gaby2300** [comment]
Hello,

I'm very sorry for the delay but I've been having family issues, actually I
still have....

Should the doodle include only a different time on Thursdays or some other
weekday and time as well?

​Regards,

Gabriela​

**Comment by Mte90** [comment]
I think that is better to keep Thursday because in the other days there are different meetings.
Also evaluate different timing on the day can be helpful to experiment that and see if they works or it is better to do it in another day.

**Comment by irvin** [comment]
Let me take this and add a thread on discourse to make sure there is really issue here besides discuss on Telegram.

**Comment by MichaelKohler** [comment]
I'm closing this as we have a pilot in #359. We can create new issues coming out of that.
