### ISSUE TITLE
[Experiment] Weekly post top topics from Reps discourse to reps-general (and maybe others)

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#234]
## Goal: 
Make sure that people that just read reps-general is aware of the latest conversations on Reps discourse

## Related Issues & Links: 
 * [Link to json with the top topics of the last week](https://discourse.mozilla-community.org/c/reps/l/top/weekly.json)
* Matching pattern is ``https://discourse.mozilla-community.org/t/ + SLUG + /ID/``

## Roles:

* Responsible:
* Accountable:
* Supporting:
* Consulted:
* Informed: 

## Required: 
TBD

**Comment by couci** [comment]
@nukeador Is this still ongoing? Please leave a comment or this will be closed in 24h
