### ISSUE TITLE
Decision on budget allocation for Q3 and Q4

### ISSUE THREAD

**Issue by couci** [mozilla/Reps#241]
## Goal: 
Publish the budget allocation for Q3 and Q4

## Roles:

Responsible: @couci @kelimuttu 

Accountable: council

Supporting: review team

Consulted: @LucyeoH 

Informed: Reps

## Required: 
- [x] Create draft budget allocation
- [x] Vote on budget allocation
- [x] Publish budget allocation and graph for Reps
- [x] Create council view tracking spreadsheet

**Comment by MichaelKohler** [comment]
@kelimuttu what is the status on the graphs/sheets? Then we could communicate that in Discourse and reps-general as well. Also document it on the Allocation wiki page. AFAIK this only has been briefly mentioned in one of the last Reps calls.

**Comment by kelimuttu** [comment]
@MichaelKohler sorry for late notice. The sheet and graph have been updated. You can check them out [here](https://datastudio.google.com/u/0/org//reporting/0B8afomu5khGpMVB6QnV4X2hoaU0/page/4jpH). I think we don't need to create another document for this.

**Comment by kelimuttu** [comment]
Council member can announce it in the next reps call then I guess we're good here.

**Comment by couci** [comment]
Apologies, I've drafted the announcement here: https://docs.google.com/document/d/1cs9e-MJAo8aHMVt8by2ZXw6ljOULpphC3tIaPnRqcwU/edit#

If there are any objections I will post tonight

**Comment by couci** [comment]
published: https://discourse.mozilla.org/t/reps-budget-allocation-for-q3-q4/19328
