### ISSUE TITLE
Reps Council and Peers meeting 

### ISSUE THREAD

**Issue by couci** [mozilla/Reps#242]
## Goal: 
Decide on the date, place, scope and agenda for the Reps council meeting

## Roles:

Responsible: @couci @nukeador 

Accountable: council and peers

Supporting: @LucyeoH @francjp 

Consulted: community development team

Informed: Reps

## Required: 
- [ ] Decide on a date
- [ ] Decide on a location
- [ ] Decide if there is need for joint sessions with the community development team
- [ ] Write scope and goals doc
- [ ] Write agenda

**Comment by couci** [comment]
Possible place is Berlin, possible dates are 29/9 - 10/1 and 6/10 - 8/10

**Comment by ioana-chiorean** [comment]
Is this something we are considering still?

**Comment by Mte90** [comment]
In the last meeting Konstantina said that we are waiting an approval of a document that we have to discuss and without that is impossible to define a date

**Comment by ioana-chiorean** [comment]
Thanks @Mte90 saw that also @elioqoshi asked yesterday in the telegram group and w got some clarifications from @nukeador .

**Comment by MichaelKohler** [comment]
Done, followup will be published soon
