### ISSUE TITLE
Send out August Newsletter

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#245]
## Goal: 
The newsletter for August is sent. 

## Roles:
Responsible: @AlexLakatos 
Accountable: Reps Council
Supporting: @elioqoshi
Informed: All Reps

## Required: 
- [x] Initial ideas have been gathered (@AlexLakatos, Due: August 25th) 
- [x] Final set of content is decided on (@AlexLakatos, Due: August 27th) 
- [x] Test newsletter is sent for verification through Council (@AlexLakatos, Due: August 29th)
- [x] Newsletter is sent out (@AlexLakatos, Due: September 1st)
- [ ] Newsletter is published on GitHub/Discourse (@AlexLakatos, Due: September 1st)

**Comment by MichaelKohler** [comment]
* Reps of the Month?
* Announce new Reps that joined recently
* Reminder: Facebook cover picture - request for ideas
* Monthly Roundup
  * Weekly Call / Council Call Notes

**Comment by MichaelKohler** [comment]
**On-boarding new Reps**
We are happy to announce 8 new Reps. Welcome!

![screen shot 2017-08-28 at 13 00 00](https://user-images.githubusercontent.com/330324/29771269-3c163722-8bf3-11e7-988d-39d923dfa93a.png)


**Reps Resources Track**
We launched the application for the Reps Resources track. Reps in the Resources track are specialized on guiding other Reps for impactful events and well defined budget and swag requests. If you are interested in applying to this track, do so until August 30th. If you are in Europe or LATAM, we highly encourage you to apply to make sure we can service all upcoming requests. [Read more.](https://discourse.mozilla.org/t/resources-track-applications-are-now-open/18367)

**Comment by Mte90** [comment]
To close this one we have to publish the newsletter on discourse/github, the date is expired @AlexLakatos do you need help for that?

**Comment by Mte90** [comment]
Newsletter loaded on github
