### ISSUE TITLE
Train the trainers initiative 

### ISSUE THREAD

**Issue by dvigneshwer** [mozilla/Reps#248]
## Goal: 

To globally train and facilitate active mobilizers across various verticals with best resource materials and latest project information.

## Roles:

Supporting: @vigneshwerd 

Consulted: @couci 

## Required: 
- [x] Draft a workflow for the initiative 
- [ ] Run a pilot project with Rust mobilizers 

## Inspiration of the idea:  

**Scope:**

In order to scale up activate events to impactful Mozilla project contributions from the community members, we need to better support our regional mobilizer driving a particular project vertical with proper resource materials, continuous guidance, and dedicated staff support. 

We can start off by hosting monthly meetings with project experts where the topic of the meeting enables mobilizers from different regions to learn in depth about the project and evangelize their learnings to rest of community members. Ideal presenters for these meetings can be active mobilizers, Mozilla Tech speakers, and staff members. 

**Artifacts produced:**

* Video recording of all the presentation
* Produce better FAQ's & event kits for MozActivate
* Collect global feedbacks on the topic

**Comment by MichaelKohler** [comment]
Nice!

**Comment by ranjithrajv** [comment]
@MichaelKohler add me as a Assignee too! I was planning of the same and had a discussion with @vigneshwerd about a month ago to work collaboratively.

**Comment by Mte90** [comment]
What are the updates of this task? Just be aligned :-)

**Comment by dvigneshwer** [comment]
Team, sorry for the delayed response here. I have come up with a small plan to test this idea/program: 

- [ ] Produce better FAQ's & event kits for MozActivate (@vigneshwerd, 7th Nov 2017)
* Collate all the Rust resource materials curated and publish it as a kit
* Design a new event flow pipeline for Rust Activate events 

- [ ] Better support regional Rust mobilizers (@vigneshwerd, 30th Nov 2017)
* Identify a group of regional Rust mobilizers, 5 - 10 people 
* Encourage enthusiastic participants to participate in Rust LibzBlitz program and take up a library, 5 - 10 crates
* Contribute to Rustcookbook Kits by creating a small project on the library selected and create materials for reproducing learning

**Comment by couci** [comment]
Is this still ongoing? Please leave a comment or this will be closed in 24h
