### ISSUE TITLE
Create a learning sharing template

### ISSUE THREAD

**Issue by bacharakis** [mozilla/Reps#25]
Build a template which will help us understand and identify the impact of new and innovative ideas around Reps activities.

**Comment by nukeador** [comment]
@bacharakis can we use the template for issues on this? Thanks! :)

**Comment by nukeador** [comment]
Moving to backlog until description is completed.

**Comment by nukeador** [comment]
Ping @bacharakis to update this, thanks! :)

**Comment by couci** [comment]
This is around for more than a year. Closing. Feel free to open if there is any update.
