### ISSUE TITLE
Change council chair

### ISSUE THREAD

**Issue by couci** [mozilla/Reps#251]
## Goal: 
Council chair for September-October 2017 should be announced

## Roles:

Responsible: @Flore-mozfr 

Accountable: Council

Supporting: @couci 

Consulted: @nukeador 

Informed: Reps

## Required: 
- [x] Announcement on discourse
- [x] Announcement on Reps-general
- [x] Check on outstanding responsibilities
- [x] Change on council chair alias

**Comment by Mte90** [comment]
There is also to publish all the old meeting notes, so if @Flore-mozfr cannot do I can do it to speed up this task :-)

**Comment by Mte90** [comment]
Old meetings notes published, we have to publish the news

**Comment by couci** [comment]
Discourse has been announced: https://discourse.mozilla.org/t/council-chair-september-october-2017/19544

**Comment by couci** [comment]
Alias ownership has been changed

**Comment by couci** [comment]
Announcement on reps general made, wiki changes made and no outstanding notes are out.

Everything is good, welcome @Mte90 :)
