### ISSUE TITLE
Rep Resources training for India Reps runs well

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/Reps#252]
## Goal: 
The special training for India Reps has been run and the final list has been announced

## Roles:

Responsible: @kelimuttu @couci 

Accountable: @kelimuttu

Supporting: @couci 

Consulted: Review Team, Reps Council

Informed: 

## Required: 
- [x] First weekly training has been run (@kelimuttu, Due: September 16)
- [x] Second weekly training has been run (@kelimuttu, Due: September 23)
- [x] Third weekly training has been run (@kelimuttu, Due: September 30)
- [x] Final list of accepted Reps has been announced (@kelimuttu, Due: Oct 4)

**Comment by MichaelKohler** [comment]
I guess this can be closed now? Do we want to open a new one for the rest of the trainees?

**Comment by kelimuttu** [comment]
Yes, I will open a new one for the second phase.
