### ISSUE TITLE
Firefox Quantum Sprint website - Prishtina, Kosovo fix

### ISSUE THREAD

**Issue by altinukshini** [mozilla/Reps#256]
## Goal: 
Can anyone try to fix this on the fx quantum sprint website?
https://twitter.com/AltinUkshini/status/914847912575856640

## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed:

**Comment by Mte90** [comment]
The right repo is https://github.com/mozilla/firefox57-sprint :-)
