### ISSUE TITLE
Call for Mobilizer Expertise / Call for interest in learning about area

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#258]
## Goal: 
The Call for Mobilizer Expertise documentation is done. Reps have been reached out to and been reminded to document their mobilizing expertise. We have identified Reps who are looking to mobilize an area and looking for the required skills to acquire to do this.

## Related Issues & Links: 
#209 

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @couci
Consulted:
Informed: 

## Required: 
- [x] We know how we want to document the skills (Mozillians?) (@MichaelKohler, Due: Oct 10th) 
- [x] Necessary tools/forms are ready to be used (@MichaelKohler, Due: Oct 12th)
- [x] Communication towards Reps is sent (@couci, Due: Oct 12th) 
- [ ] Reps are reminded to complete the documentation (@couci, Due: Oct 18th)

**Comment by MichaelKohler** [comment]
PR created to put this on the Reps Portal as profile fields (and also make it possible to search for this through the search): https://github.com/mozilla/remo/pull/1398

**Comment by MichaelKohler** [comment]
Next steps required here:

* Get PR merged and put to production so we can use the Reps Portal
* Add all necessary areas to the portal (list of areas we want people to mobilise in)
* Send out communication including "why" and "what to do"

Communication skeleton:

* Current status of mobilizer project
* Why do we need to know who is doing what and who is interested in which topics
* Ask: fill out the two new fields with your currently skills / interest areas you would like to learn more about
* Deadline

**Comment by nukeador** [comment]
Just a quick suggestion: Can we use "Mobilizer" instead of "Mobiliser" for consistency with wording everywhere else?

Thanks!

**Comment by MichaelKohler** [comment]
> Just a quick suggestion: Can we use "Mobilizer" instead of "Mobiliser" for consistency with wording everywhere else?

Sure, will adopt my PR.

**Comment by couci** [comment]
@MichaelKohler do we have an estimation when this is going to be ready in order to start comms?

**Comment by MichaelKohler** [comment]
The initial functionality is on production. I just filed a new PR to make this optional, as not everyone will need to fill out the mobilising parts: https://github.com/mozilla/remo/pull/1403

In terms of next steps:

- [ ] Get this PR merged and in production
- [ ] Ask Nuke to fill out all areas we want in the settings (I think we miss a few skills/interests)
- [ ] I'm gonna make a PR to allow Council to edit the list
- [x] Send out the communication with "why" and "how"

@couci @nukeador is that ok for you?

**Comment by nukeador** [comment]
Looks good for me

**Comment by couci** [comment]
comms ready and shared

**Comment by MichaelKohler** [comment]
Hopefully last PR done: https://github.com/mozilla/remo/pull/1411

Comms are ready (apart from the new screenshots), and will be sent out after the change is in production.

**Comment by MichaelKohler** [comment]
This is done: https://discourse.mozilla.org/t/mark-your-mobilizing-expertises-and-learning-interests-in-reps-portal/21173/1
