### ISSUE TITLE
Informative sessions with functional teams

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#260]
## Goal: 
Organize informative sessions with the main functional teams and Reps to learn about vision, goals and opportunities to mobilize.

## Roles:

Responsible: @nukeador @couci 

Accountable: Reps Council

Supporting: Functional teams

Consulted: Reps Council

Informed: Reps Council

## Required: 
- [x] Initial comms with funcional teams
- [x] Localization session scheduled
- [x] SUMO session scheduled
- [ ] Marketing session scheduled
- [ ] Rust session scheduled
- [ ] WebVR session scheduled
- [x] Addons session scheduled

**Comment by couci** [comment]
This work is done
