### ISSUE TITLE
Send out October Newsletter

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#262]
## Goal: 
The newsletter for October is sent. 

## Roles:
Responsible: @AlexLakatos 
Accountable: Reps Council
Supporting: @MichaelKohler
Informed: All Reps

## Required: 
- [x] Initial ideas have been gathered (@AlexLakatos, Due: October 25th) 
- [x] Final set of content is decided on (@AlexLakatos, Due: October 27th) 
- [ ] New Reps emails are added (@AlexLakatos, Due: October 29th)
- [ ] Test newsletter is sent for verification through Council (@AlexLakatos, Due: October 29th)
- [ ] Newsletter is sent out (@AlexLakatos, Due: November 1st)
- [ ] Newsletter is published on GitHub/Discourse (@AlexLakatos, Due: November 1st)

**Comment by MichaelKohler** [comment]
# Rep of the Month
There were no nominations for Reps of the Month for October. Keep on rocking, Reps!

# Firefox Quantum Sprint
The Firefox Quantum Sprint happened! Konstantina has presented the learnings in the [Monday call](https://air.mozilla.org/mozilla-weekly-project-meeting-20171023/) as well as written a [post](https://discourse.mozilla.org/t/how-to-test-5000-websites-in-7-days-recapping-the-firefox-quantum-sprint/20565) about it. Go check it out and tell us your learnings! [Read more](https://discourse.mozilla.org/t/how-to-test-5000-websites-in-7-days-recapping-the-firefox-quantum-sprint/20565)

# Special Calls about 2018 OKRs
In the past weeks we've hold special calls to inform Reps about functional area's focus for 2018. If you are involved in any of these functional areas, we highly encourage you to watch the recordings of the calls.

* Add-ons: https://discourse.mozilla.org/t/weekly-call-19-10-2017-special-edition-add-ons/20608
* SUMO: https://discourse.mozilla.org/t/25-10-2017-meeting-special-edition-sumo/20796

We will organize more of these calls for other functional areas as well, keep an eye on the Reps Discourse category!

# Suggest your own tweets for the MozillaReps Twitter account
You can now suggest your own tweets for the @MozillaReps Twitter account. All you need to do is filing a GItHub issue in the repository. [Learn more on how to suggest a tweet](https://discourse.mozilla.org/t/create-tweets-for-the-reps-twitter-account/21047)

# Reps Resources Training
The Resources Training for the second group is currently ongoing. The last training has happened and soon we will announce the new badge of Resources Reps. With this initiative we can train Reps on effectively guiding Reps in all Resources matter by guiding them on how to set up an impactful event and requesting budget for them. Please reach out to the already graduated Reps for any help you need for Resources.
[Read more](https://discourse.mozilla.org/t/resources-track-applications-are-now-open/18367)

# Reps Coaching Training
Don't forget that all Reps can take the [Reps Coaching training](https://wiki.mozilla.org/ReMo/Coaching/Training) on their own pace. We encourage all Reps with interest in coaching to go through the training and to write their narrative on Discourse. The first few Coaching Practice meetings are scheduled. This will act as final step of the training. If you haven't already, head over to the training and get started.
[Read more](https://wiki.mozilla.org/ReMo/Coaching/Training)

# Onboarding new Reps
We are happy to announce 2 new Reps this month. Welcome! 🎉  🎉 

![screen shot 2017-10-24 at 21 25 05](https://user-images.githubusercontent.com/330324/31963678-d5843cf2-b901-11e7-818e-d3a407de4e33.png)


# Monthly round-up
same as last month

**Comment by MichaelKohler** [comment]
@AlexLakatos this is ready for publication if there are no objections until you see this

**Comment by Mte90** [comment]
As written on https://github.com/mozilla/Reps/issues/231 we need to upload on github the newsletter and add the link on the weekly updates so we can try with this new experiment

**Comment by couci** [comment]
Adding suggestions as per @AlexLakatos request:
# Firefox Quantum Sprint
The Firefox Quantum Sprint happened! Konstantina has presented the learnings in the [Monday call](https://air.mozilla.org/mozilla-weekly-project-meeting-20171023/) as well as written a [post](https://discourse.mozilla.org/t/how-to-test-5000-websites-in-7-days-recapping-the-firefox-quantum-sprint/20565) about it. Go check it out and tell us your learnings! [Read more](https://discourse.mozilla.org/t/how-to-test-5000-websites-in-7-days-recapping-the-firefox-quantum-sprint/20565)
![screen shot 2017-11-02 at 15 56 46](https://user-images.githubusercontent.com/7702955/32332722-82808150-bfe6-11e7-846d-ab9c98ff38f4.png)

## Reps Resources Training
The Reps Resources Training is officially over, congrats to all the people that graduated. You can find the full list of participants [here](https://reps.mozilla.org/people/#/group/resources/). You can also read the [blogpost](https://blog.mozilla.org/mozillareps/2017/11/01/resources-reps-whats-next/) by Kiki to learn more about the procedure and the learnings from the training

**Comment by Mte90** [comment]
Files loaded also on github :-)
