### ISSUE TITLE
Plan for train-the-trainers for mobilizers is in place

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#264]
## Goal: 
Define this plan and review with the council

## Related Issues & Links: 
#258 

## Roles:

Responsible: @couci, @mte90

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by Mte90** [comment]
The document: https://docs.google.com/document/d/1GejYvx99pOckQP8ycOQ04WAPHwJoBxnvWTyfBJef-6M/edit#

**Comment by couci** [comment]
@Mte90 I'll close this until we define the changes for the program. Feel free to re-open afterwards
