### ISSUE TITLE
Draft proposal for the Reps Regional Coaches

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#265]
## Goal: 
We need a draft about that initiative for the and of Q4

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:

Responsible: @nukeador 

Accountable: 

Supporting:@ruben

Consulted:

Informed: 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by Mte90** [comment]
I think that I will try to work on that after Open Conversation, I will probably busy with the Reps Mobilizers but I don't think that write a draft in the next months will be a problem

**Comment by couci** [comment]
@Mte90 what is the update on this one?

**Comment by Mte90** [comment]
No updates for that because I was busy with other things.
I think that after the MDM stuff we can start to think about it.

**Comment by couci** [comment]
ok, let's close this and we can reopen once we have something new
