### ISSUE TITLE
Reps Applications Screening Round - First Week of November

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#266]
## Goal: 
All open and ready applications are screened and informed.

## Related Issues & Links: 
#141 
#169 
[Application Screening Sheet ](https://docs.google.com/spreadsheets/d/1xA-iopmysOLW1TFEyw6cVWAzQDhRY_lqPdL9E5Z_Bss/edit#gid=789757527) - private for obvious reasons

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: Screening group
Informed: Applicants

## Required: 
- [x] Add applicants to the screening sheet (@MichaelKohler, Due: November 3rd)
- [x] Reach out to rest of screening group and ask them to screen (@MichaelKohler, Due: November 3rd)
- [x] Screen applications (@Mte90, Due: November 9th) 
- [x] Respond back to applicants (@MichaelKohler, Due: November 9th) 
- [x] Proceed with Webinar for those who got approved (@MichaelKohler, Due: November 9th)

**Comment by DineshMv** [comment]
I'm interested to help with screening of applicants. 

Please let me know if you need any helping hand ;)

**Comment by MichaelKohler** [comment]
This is done, thanks everyone
