### ISSUE TITLE
Initial group for market research training with OI

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#267]
## Goal: 
Define the first part of the comms with OI

## Related Issues & Links: 
https://github.com/mozilla/Reps/issues/258

## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by Mte90** [comment]
Email sent to start to working on

**Comment by emmairwin** [comment]
Can you share more about this   we ran a 4 week course a couple of years ago teaching contributors how to conduct market research, perhaps we can reuse some ofthat. Thanks!

**Comment by Mte90** [comment]
Yes of course, this is part of https://github.com/mozilla/Reps/issues/258 Mobilizer roadmap and after https://discourse.mozilla.org/t/mark-your-mobilizing-expertises-and-learning-interests-in-reps-portal/21173 we need to work on a training about how to do a market research of this skills to volunteers that are mobilizer to improve a functional area

**Comment by ioana-chiorean** [comment]
Seems like a great initiative - will follow along

**Comment by Mte90** [comment]
Actually we need how will handle that part to be more autonomous as council on this step.

**Comment by couci** [comment]
This got blocked and eventually abandoned. I am closing for now, feel free to reopen if there any new updates.

**Comment by Mte90** [comment]
Yes also this was part of the mobilizer initiative and never complete because of realign, so yes is better to see what will happen in the future.
