### ISSUE TITLE
Council members onbording - Autumn 2017

### ISSUE THREAD

**Issue by couci** [mozilla/Reps#268]
## Goal: 
Onboard successfully the new council members  

## Related Issues & Links: 
#https://github.com/mozilla/Reps/issues/180
https://wiki.mozilla.org/ReMo/SOPs/Council_onboarding
## Roles:

Responsible: @couci

Accountable: @nukeador 

Supporting: @mozilla/reps-council 

Consulted: @reps-peers

Informed: Reps

## Required: 
- [x] E-mail new council members for onboarding meeting (owner @couci , Due: November 24th) 
- [x] Pair new council members with council buddies (owner @couci, Due: November 23rd) 
- [x] E-mail new council members to introduce their buddies (owner @couci, November 24th)
- [x] Have onboarding call (owner: council, Due: November 30th)
- [x] Add new council members to mailing list and alias (owner: @couci, Due:  December 4th)
- [x] Add new council members to telegram group (owner: @couci, Due:  December 4th)
- [x] Add new council members on the portal and take out the old ones (owner: couci, Due:  December 11th)
- [x] Write blogpost/announcement on the Reps blog (owner: couci, @ioana-chiorean , Due: December 15th)
- [x] Former council members are being removed from the mailing list, alias and telegram group (owner: couci, Due: December 15th)
- [x] Council chair announces to former council members that their duties are over as Council members (owner: couci, Due: December 15th)
- [x] Council chair emails new members and reps-general announcing the new ones start their duties (owner: couci, Due: December 15th)

**Comment by couci** [comment]
Council buddies have been defined:
* Prathamesh - Faye
* Mayur - Ankit

**Comment by couci** [comment]
E-mail for onboarding asking meeting time sent

**Comment by couci** [comment]
introduction emails for buddies has been sent

**Comment by couci** [comment]
Onboarding call happened

**Comment by couci** [comment]
Blog is out: https://blog.mozilla.org/mozillareps/2017/12/13/new-council-members-autumn-2017/

**Comment by Mte90** [comment]
email to mailing list sent
