### ISSUE TITLE
Reps OKR Q2 / 2016

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#27]
## Goal: 
The Reps program OKRs are decided and published.

## Related Issues & Links: 
(WIP for Council, private for now) https://docs.google.com/document/d/1aRnTQQ5oLi8kbotRduXNd_EJsKQQ9G8kMBLmBr2a9zE/edit

## Roles:
* Owner: @MichaelKohler
* Involved: all Council members

## Required: 
- [x] Send reminder to Alias (@MichaelKohler, Due: May 12th) 
- [x] Finish phrasing the Key Results (all, Due: May 13th) 
- [x] Agree on the OKRs (@MichaelKohler, Due: May 25th)
- [x] Add small explanation regarding scope of RepsNext & Publish them on the Wiki/create Discourse topic for questions/discussions (@MichaelKohler, Due: May 26th)

**Comment by MichaelKohler** [comment]
I've rephrased some goals, @all please review :)

https://docs.google.com/document/d/1aRnTQQ5oLi8kbotRduXNd_EJsKQQ9G8kMBLmBr2a9zE/edit

**Comment by MichaelKohler** [comment]
I've extended the voting since we only had 2 votes until now. Please vote!

**Comment by MichaelKohler** [comment]
We have agreed on the OKRs, I just need to add a small addition on what we mean with "RepsNext" for now on there. Will publish and announce tomorrow (timeline is updated in the initial post).

**Comment by MichaelKohler** [comment]
I've updated which parts of RepsNext are important for the goal. I will communicate this tomorrow.

**Comment by hmitsch** [comment]
For documentation purposes: Unanimous vote, as seen in screenshot.
![remo okr q2-16 voting](https://cloud.githubusercontent.com/assets/869692/15691542/b910d41e-2789-11e6-9468-57f6c9879970.png)

**Comment by MichaelKohler** [comment]
https://wiki.mozilla.org/ReMo/Goals
https://discourse.mozilla-community.org/t/reps-program-okrs-for-q2-2016/9012
