### ISSUE TITLE
Migrate mailing list reps-general to discourse

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#272]
## Goal: 
Keep mailing lists and discourse require a lot of time, switch all our reps to the reps category on discourse and use that for the mailing lists can improve our tasks queue.

## Related Issues & Links: 
Docs with complete explanation: https://docs.google.com/document/d/143_qA2Ezq9B04Nne6VbfHsvRoaXQhO2UcZG0ou-nqz8/edit
#29 - Create a mozillian group of reps
#281 - For the reps list

## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [x] Review by @LeoMcA done (owner, Due: Jan 5th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by Mte90** [comment]
I think that for the reps-council mailing list instead can be removed because now we are using Discourse for that purpose

**Comment by Mte90** [comment]
Actually we don't have a mozillian group with all the reps, exist https://mozillians.org/it/group/reps/ but is not used.
Without that we cannot check if the user is a reps from the AIM system.
Later there will be the issue of coding but we need that before to do anything.

**Comment by Mte90** [comment]
Until https://github.com/mozilla/discourse/issues/28 is not done we cannot work on that

**Comment by Mte90** [comment]
It is possible right now block the permission to create new thread (reply will be allowed) in specific category in Discourse based on mozillians group.
We can plan to work on the reps group on mozillian in the meantime for this purpose.

**Comment by Mte90** [comment]
We chosen to suggest to the Reps to follow the category on Discourse manually also during the onboarding.
I think that we need to know how many people subscribed the category to evaluate when to do the switch.

**Comment by nukeador** [comment]
Leo can generate a query to know how many people is watching and how many is tracking.

**Comment by Mte90** [comment]
Already written to him to see if it is possible, I am wondering if every user registered on Discourse is automatically subscribed to this category or not and with numbers we can see in case.

**Comment by Mte90** [comment]
```
reps:
 notification_level  | count 
---------------------+-------
 tracking            |    23
 watching            |    83
 muted               |    11
 watching first post |     1
 
 
reps/coaching-training:
 notification_level | count 
--------------------+-------
 muted              |     3
 watching           |     5
 
reps/events:
 notification_level  | count 
---------------------+-------
 tracking            |     5
 watching            |    20
 watching first post |     1
 muted               |     1
 
reps/regional-coaches:
 notification_level | count 
--------------------+-------
 tracking           |     1
 watching           |     6
 
reps/coaching:
 notification_level | count 
--------------------+-------
 watching           |     3
 tracking           |     1
```

**Comment by Mte90** [comment]
We need to plan the removal of the Reps-Mentor mailing list now that a discourse category exist :-)

**Comment by Mte90** [comment]
With the experience on Reps Mentor we need to find a guide that explain that they have to update their mozillians profile.
Also to wait their approval of the invite on the mozillian group.
Is required also to help them for support on login/access by a group and not me (as example for these cases).

**Comment by Mte90** [comment]
as for #348 a lot of reps was reached to update their profile and add also 2FA so this task seems more easy to do now :-)

**Comment by Mte90** [comment]
It is funny just over 2 years for this task and now we have the ignration in discourse that we was needed https://github.com/mozilla/discourse/issues/28#issuecomment-537888975

**Comment by hmitsch** [comment]
@Mte90 thanks for the heads-up. I commented on the issue. Let's keep that ball moving.

**Comment by Timmaks** [comment]
I think this issue can be closed

**Comment by Mte90** [comment]
Just to understand, the mailing list was migrated to discourse? Because I didn't saw any announcement.
