### ISSUE TITLE
[Reps Weekly Call] Ideas for speakers and topics

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#274]
## Ideas January: 
- [x] Firefox available on Fire TV
- [x] New episodes in IRL - here we an ask someone to join and explain what meant the season 1 in terms on audience etc
- [?] Fluent - http://projectfluent.org/ - how is this used in Firefox https://diary.braniecki.net/2018/01/08/multilingual-gecko-in-2017/
- [x] Spectree and Meldown - fixes pushed in one day
- [x] new RUST community manager - invite Ashley to talk more
- [x] Open Leaders - https://mozilla.github.io/leadership-training/round-5/projects/

Read only:
- [x] The Ford-Mozilla Open Web Fellowship program is seeking host organizations: like-minded groups working on the front lines of internet health https://blog.mozilla.org/netpolicy/2018/01/16/host-open-internet-activist/
- [x] Mozilla and Sundance Film Festival Present: VR the People https://blog.mozilla.org/blog/2018/01/16/mozilla-sundance-film-festival-present-vr-people/
- [x] Mozilla Files Suit Against FCC to Protect Net Neutrality https://blog.mozilla.org/blog/2018/01/16/mozilla-files-suit-fcc-protect-net-neutrality/

**Comment by prathameshchavan** [comment]
I am myself handling the Spectree and Meldown vulnerability queries as a part of Red Hat Support. A bug fix pushed in one day is truly awesome!

**Comment by ioana-chiorean** [comment]
* Contacted:
   * Firefox available on Fire TV
   * New episodes in IRL 
   * New RUST community manager
* Added read only section

**Comment by couci** [comment]
@ioana-chiorean as far as I know we have the IRL Rust and Fire TV coming right? Are we planning for anything else?

**Comment by ioana-chiorean** [comment]
All these were in the call - looking now for other opportunities

**Comment by Mte90** [comment]
Maybe we can add a section in the weekly call etherpad where people can suggest topics for the next calls and later we open a ticket about the proposals.

**Comment by ioana-chiorean** [comment]
@Mte90 -yes we can - we did it before ( like in the intro part but not so many arose) 
But I will add it.
