### ISSUE TITLE
Reps Applications Screening Round - Week of January 3rd

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#276]
## Goal: 
All open and ready applications are screened and informed.

## Related Issues & Links: 
[Application Screening Sheet ](https://docs.google.com/spreadsheets/d/1WcQJCo38pwEIktErFm8KQDhA4eFSM6T5AYDS-6Oz1Tg/edit#gid=997767683) - private for obvious reasons

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: Experimental screening group
Informed: Applicants

## Required: 
- [x] Add applicants to the screening sheet (@MichaelKohler, Due: January 14)
- [x] Reach out to rest of screening group and ask them to screen (@mte90, Due: January 15)
- [x] Screen applications (@Mte90, Due: January 20)
- [x] Respond back to applicants (@MichaelKohler, Due: January 21)
- [x] Proceed with Webinar for those who got approved (@MichaelKohler, Due: January 21)

**Comment by MichaelKohler** [comment]
@Mte90 as discussed yesterday in the Telegram group I will need better and more detailed explanations to give valuable information on how to improve to the applications that got rejected.

**Comment by Mte90** [comment]
Written on telegram now :-)

**Comment by MichaelKohler** [comment]
Thanks, responded to all applicants.
