### ISSUE TITLE
Onboarding Screening Team 2018-1 applications

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#277]
## Goal: 
As explained on https://discourse.mozilla.org/t/do-you-want-join-the-onboarding-screening-team/24497 we want to have a team that evaluate new applications.
If you want to join leave your name here but not forget to read the Discourse thread and the wiki (https://wiki.mozilla.org/ReMo/Webinar/Screening) about it.

## Related Issues & Links: 
https://github.com/mozilla/Reps/issues/271

## Roles:

Responsible: @mte90

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [x] Gather applications (@mte90, Due: Jan 30th) 
- [x] Discuss with Council about the applications (@Mte90, Due: Jan 30th) 
- [x] Published new team members (@Mte90, Due: Feb 15th) 
- [x] Publish blogpost about previous and new team (owner, Due: Feb 16th)

**Comment by DineshMv** [comment]
Dear Council, 

I'm interested to be a part of the screening team. 

Thanks,
Dinesh

**Comment by decode-dev** [comment]
Interested to be a part of screening team.

Cheers,
Kalyan Dikshit

**Comment by jayeshkattar** [comment]
I'm interested. 👍 

Thanks,
Jay

**Comment by abhiaecs** [comment]
I'm interested to be a part of the screening team.

Thanks,
Abhilash

**Comment by gaby2300** [comment]
Dear Council,

I'm very interested to be a part of the screening team.

Thanks!
Best regards,
Gabriela

**Comment by balapandu222-zz** [comment]
Council Board,

I'm interested and wanna be a part of screening team.

Thanks and Regards,
Bala Subramaniyan

**Comment by robinkoshy** [comment]
Hey there !

I'm interested being the part of the screening team .

Thanks
Robin

**Comment by gaby2300** [comment]
Dear Council,

I'm very interested to be a part of the screening team.

Thanks!
Best regards,
Gabriela

**Comment by vi5halc** [comment]
Hello Council,

I am interested in being a part of this screening team. :)

Thanks and regards,
Vishal Chavan

**Comment by roshangm1** [comment]
Hi, 
I am interested in being a part of the screening team. 

Thanks,
Roshan

**Comment by edovio** [comment]
Hello, 
I'm interested to being part of this team! :) 
Thanks,
Edoardo

**Comment by hossainalikram** [comment]
Hello Council,

I am interested on continuing to become a part of the team :)

Regards
Ikram

**Comment by akjogawath** [comment]
Hi Team, 

I am interested to be a part of this amazing team.

Best Regards,
Ajay

**Comment by Timmaks** [comment]
Hi Council,

i am interested in becoming a member of this team!

Greetings

Tim Maks

**Comment by codecaiine** [comment]
Hi , 
I am interested in being a part of the screening team.
Regards, 
Aka

**Comment by SandeepKapalawai** [comment]
Hey There,

I am interested to be a part of Onboarding Screening Team.

Thank you :)
Sandeep

**Comment by Ruwan-Ranganath** [comment]
Hi Counsil , 

I'd be like to part of screening team. 

Thank you.

**Comment by anknite** [comment]
Council is now voting for selection of the applicants.

**Comment by Mte90** [comment]
New team members published https://discourse.mozilla.org/t/welcome-to-the-new-onboarding-screening-team-2018-1/25665
Soon there will be a blog post about it to say thanks also to the previous team

**Comment by Mte90** [comment]
Blogpost https://blog.mozilla.org/mozillareps/2018/02/15/reps-on-boarding-team/
