### ISSUE TITLE
Communication Council Chair May/June 16

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#28]
## Goal: 
Communicate the new Council chair and update the relevant wiki pages.

## Roles:
* Owner: @Faisalaziz 
* Involved: @MichaelKohler

## Required: 
- [ ] Announce the new Council chair (@Faisalaziz  , Due: May 14th) 
- [x] Update the Wiki pages (@MichaelKohler, Due: May 14th)

**Comment by MichaelKohler** [comment]
Wiki page is updated here: https://wiki.mozilla.org/ReMo/Council

**Comment by nukeador** [comment]
Ping @Faisalaziz

**Comment by Faisalaziz** [comment]
Communication sent
https://discourse.mozilla-community.org/t/council-chair-may-june-2016/9070
