### ISSUE TITLE
List of active Reps

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#281]
## Goal: 
As https://github.com/mozilla/Reps/issues/272 we need a list with links to mozillian profile.
Later we will see if we can use that with a script to import automatically or do it manually

## Related Issues & Links: 
[Reference meta issues and past issues] #272 

## Roles:

Responsible: @MichaelKohler 

Accountable:

Supporting: @mte90, @prathameshchavan 

Consulted:

Informed: 

## Required: 
- [ ] Ask tasos if we can get this output from the db (@MichaelKohler, Due: January 27th) 
- [ ] If not, write quick script to extract from the API (@MichaelKohler, Due: January 30th)

**Comment by MichaelKohler** [comment]
@akatsoulas could we get the list of all mozillians profile URLs from Reps profiles from the db splitted by active / alumni?

I imagine something like the following two pseudo queries:

```
SELECT mozillians_profile_url FROM reps WHERE rep != alumni
```

```
SELECT mozillians_profile_url FROM reps WHERE rep == alumni
```

Would be great to have this directory from the DB, instead of going through the API. A simple TXT file with all urls would be enough.

**Comment by MichaelKohler** [comment]
@akatsoulas quick ping here agian, thanks!

**Comment by Mte90** [comment]
Maybe we can implement something in the portal?
Like in the dashboard different buttons for export only for Admin and Council.

**Comment by Mte90** [comment]
About this ticket there are different things moving on like https://github.com/mozilla/remo/pull/1476 but doesn't cover the export.
Maybe for the moment we don't need the export until rules to move automatically inactive people to be moved to alumni are not deployed.

**Comment by MichaelKohler** [comment]
For #272 we only need the active Reps. Can you remind me why we need Alumni as well?

**Comment by Mte90** [comment]
I don't remember too why...

**Comment by MichaelKohler** [comment]
Then let's simplify this :)

**Comment by MichaelKohler** [comment]
Sent to Daniele
