### ISSUE TITLE
Council Elections - Spring 2018

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#284]
## Goal:
- Hold the council election in order to occupy the spots that are free after the term of one year is ending for:

🎓 @fayetandog 
🎓 @Mte90 
🎓 @elioqoshi 
🎓 @ankitgadgil 
🎓 @Flore-mozfr 

## Success:
- The elections take place and we have _ new council members

## Related Issues & Links:
- Previous Elections #208, #114, #15
 
## Roles:
Owner: @ioana-chiorean 
Involved: @couci, Reps Peers 
Informed: @nukeador

## Required:
- [x] Prepare [the timeline](https://github.com/mozilla/Reps/issues/208#issuecomment-339637554) and the steps (@ioana-chiorean, Due: March 20th 2018)
- [x] Send out [the announcement](https://discourse.mozilla.org/t/important-council-elections-spring-2018-please-read/27001) (@ioana-chiorean, Due: March 26th 2018)
- [x] Start gathering nominations (@ioana-chiorean, Due: March 26th 2018)
- [x] Close nominations (@ioana-chiorean, Due: March 2018)
- [x] Prepare Q&A (@ioana-chiorean, Due: March 2018)
- [x] Run Q&A (@ioana-chiorean, Due: March 2018)
- [x] Start Voting (@ioana-chiorean, Due: March 2018)
- [x] Close voting and announce results.  (@ioana-chiorean, Due: March 2018)

## Updates required:
- [ ] History Page [10th Council ]( )
- [ ] Create [11th entry]( )
- [ ] Update < if necessary> [requirements for council members]( ) 
- [ ] Update [tasks and requirements]( )

**Comment by ioana-chiorean** [comment]
Proposed timeline (all times in 09:00 UTC):

* [x] March 22nd -  Present the timeline in Reps Call
* [x] March 26th - call for candidates/nominees open
* [x] April 3rd - call closes
* [x] April 3rd - start of campaign period
* candidates are given 5 days to answer questions and post them on their profile page
* candidates are given 5 days to publish a 30-120 seconds campaign video

* [x] April 8th - deadline for answers and videos to be published
* [x] April 9th - voting starts
* [ ] April 15th - voting ends - new elected members are announced
* [ ] April 16th - the Council Onboarding begins

**Comment by ioana-chiorean** [comment]
Announcement published: https://discourse.mozilla.org/t/important-council-elections-spring-2018-please-read/27001

**Comment by ioana-chiorean** [comment]
Mail for second step was sent out to the 11 applicants. We will be tracking their progress here. 

1. [Daniele Scasciafratte](https://reps.mozilla.org/u/Mte90/)
  - [x]  [Video](https://www.youtube.com/watch?v=aktfSXItrxk)
  - [x]  [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2018-nominee-q-a/27331/2?u=ioana))
2.  [Pushpita Dey](https://reps.mozilla.org/u/pushpita_dey/)
  - [x]  [Video](https://youtu.be/isnLo3yURwo)
  - [x]  [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2018-nominee-q-a/27331/6?u=ioana)
3.  [Edoardo Viola](https://reps.mozilla.org/u/edovio)
  - [x] [Video](https://youtu.be/EVsaZSKn13M)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2018-nominee-q-a/27331/3?u=ioana)
4.  [Faisal Aziz](https://reps.mozilla.org/u/FaisalAziz/)
  - [x] [Video](https://youtu.be/d_v0AXlb800)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2018-nominee-q-a/27331/8?u=ioana) 
5.  [Umesh Agarwal](https://reps.mozilla.org/u/umesh/)
  - [x] [Video](https://youtu.be/Q9aNBAN4ld0)
  - [x]  [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2018-nominee-q-a/27331/7?u=ioana)
6.  [Mehul Patel](https://reps.mozilla.org/u/rowdymehul/              )
  - [x] [Video](https://youtu.be/OdpPZTu-S5Q)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2018-nominee-q-a/27331/9?u=ioana)
7. [Oarabile Mudongo](https://reps.mozilla.org/u/omudongo/)
  - [x] [Video](https://www.youtube.com/watch?v=omJCQFw6NLA)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2018-nominee-q-a/27331/10?u=ioana)
8. [Irvin](https://reps.mozilla.org/u/irvin)
  - [x] [Video](https://www.youtube.com/watch?v=ZkBL3K6gDHo)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2018-nominee-q-a/27331/4?u=ioana)
9. [Hossain Al Ikram](https://reps.mozilla.org/u/hossainalikram/)
  - withdraw 
10. [David Ross](https://reps.mozilla.org/u/sw1ayfe/)
  - [x] [Video](https://www.youtube.com/watch?v=dMQoKQHlsK8)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2018-nominee-q-a/27331/11?u=ioana)
11. [Manel Rhaiem](https://reps.mozilla.org/u/manel_rhaiem92/)
  - [x] [Video](https://youtu.be/Xp-zMwZ_-6s)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2018-nominee-q-a/27331/12?u=ioana)

Their replies [are tracked here](https://discourse.mozilla.org/t/important-council-elections-spring-2018-nominee-q-a/27331).

**Comment by ioana-chiorean** [comment]
Voting will start at (almost) 9 PM UTC: https://reps.mozilla.org/v/reps-council-elections-spring-2018-5-spots/

**Comment by Mte90** [comment]
I think that we can close this task because the new council already onboarded

**Comment by MichaelKohler** [comment]
The following things are left to be done here:

* Update https://wiki.mozilla.org/ReMo/Council/History
* Discourse / Blog post with official announcement for new Council members + thanking outgoing members

**Comment by ioana-chiorean** [comment]
Updated the first one - https://wiki.mozilla.org/ReMo/Council/History#12th_Council_-_.28April_2018.29
@MichaelKohler discourse was posted -https://discourse.mozilla.org/t/important-council-elections-spring-2018-results-and-next-steps/27804 do you envision smtg else?
Blog post can we copy/pasted and edited from there ( i do not have access)
