### ISSUE TITLE
NO MEETING -  Reps Weekly Call - March 1st, 2018

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#293]
## Goal:
- Organize the weekly reps call. 

## Success:
- The call is held and more than 15 reps/mozillians attend
- We have ready new topics 

## Related Issues & Links: 
⬅️ #292 
➡️ #294

## Roles:
Responsible: @ioana-chiorean,@couci 
Accountable: @ioana-chiorean,@couci 
Supporting: 
Consulted: @nukeador, 
Informed: Reps and Mozillians

## Agenda Work:
- [x] Shout outs - Call for nominations (@ioana-chiorean, @couci, [small, medium, large], Due: date )
- [x] Council updates - (@mte90 [medium], Due: date )
- [x] Help me with my project - call for entries (@ioana-chiorean, @couci, [small, medium, large], Due: date )
- [ ] TOPIC 1  - 
- [ ] TOPIC 2 
- [ ] TOPIC 3

Read only:
- [Podcast] In the latest episode of IRL, SoSadToday’s Melissa Broder talks about the impact of anonymity for women and self-care. https://irlpodcast.org/episode11 

Status
🔜  - we can present next week
🔃 - we need to see when we can present
✅ - topic will be presented in the call
❔ -  topic needs to be confirmed for the call. 
❌ - not gonna be presented in the call. 

## Pre-call checklist:
- [x] [Etherpad agenda](https://public.etherpad-mozilla.org/p/remo-call-01-03-2018) (@ioana-chiorean, [small], Due:  h, 2018 )
- [x] [Discourse post](https://discourse.mozilla.org/t/no-call-today-weekly-call-03-01-2018/26178/1) (@ioana-chiorean, @couci, [small], Due: date )
- [x] mail on reps- general (@ioana-chiorean, @couci, [small], Due: date )
- [x] telegam and Social Media - FB and TW  (@ioana-chiorean, @couci, [small], Due: date )
- [x] Send invites to speakers (@ioana-chiorean, @couci, [small], Due: date )
- [x] [Reps Event created](https://reps.mozilla.org/e/remo-call-01-03-18/) 

## Post meeting to dos:
- [x] Separate topics to different discussion threads on Discourse for further discussion (-> Reply as linked topic from the Meeting notes' top topic)  (@ioana-chiorean, @couci, [small], Due: date )
- [x] [Post meeting notes] ( ) (@ioana-chiorean, @couci, [small], Due: date )
- [x] Mail Shout-Outs to be shared on SM (@ioana-chiorean, @couci, [small], Due: date ) #

**Comment by SoSadToday** [comment]
What is this bull? Why am I mentioned here?

**Comment by ioana-chiorean** [comment]
hey @SoSadToday i just added the tweet that went out for the IRL newest episode about your story. I did not realize it is your github handle also. The section is a read only section in Mozilla reps call and its goals is to promote short things happening in the last 7 days. I will untag you.

**Comment by SoSadToday** [comment]
What story? I never did any story with you guys. Why are you falsifying information?

**Comment by ioana-chiorean** [comment]
@SoSadToday again - i just copy the text from this tweet (https://twitter.com/mozilla/status/968209674146283520) here without realizing the tag will go though and i never checked you handle here. 

No one is falsifying any information.
