### ISSUE TITLE
 Publish RoM for February 2018  

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#298]
## Goal: 
The RoM for February 2018 is published.

## Roles:

Responsible: @ioana-chiorean 
Accountable: Reps Council
Supporting: @MichaelKohler

## Required: 
- [x] Let Mentor write a text about RoM (@ioana-chiorean, Due: March 10th) 
- [x] Finalize text (@ioana-chiorean, Due: March 13th) 
- [x] Publish blog post, discourse, reps-general and Telegram (@ioana-chiorean, Due: March 15th)

**Comment by ioana-chiorean** [comment]
Results: https://reps.mozilla.org/v/rep-of-the-month-for-february-3/

**Comment by Mte90** [comment]
We are very late because also the rom of march voting is already closed

**Comment by ioana-chiorean** [comment]
The text was written a couple of weeks before - but i don't have the rights to post it.

**Comment by Mte90** [comment]
Very strange maybe the Peer doesn't have permission on featuredrep, @MichaelKohler we have to check that

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/reps-of-the-month-february-2018/27260/2
Blog submitted - @couci please approve once you have time
Telegram and reps-general is done as well

**Comment by MichaelKohler** [comment]
Blog post: https://blog.mozilla.org/mozillareps/2018/04/01/reps-of-the-month-february-2018/

**Comment by ioana-chiorean** [comment]
Thanks so much everyone! 🙌🏼  🎉
