### ISSUE TITLE
Posts about Berlin and RepsNext

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#3]
## Goal: 
Share a post with experiences around the Reps Leadership meetup Berlin

## Success:
All Council and Peers members have shared a post about their experience

## Roles:
Owner: @brianking
Involved: Council and Peers

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by MichaelKohler** [comment]
my blog post: https://michaelkohler.info/2016/reps-council-working-days-berlin-2016

**Comment by nukeador** [comment]
@brianking  please update the details in this issue. Thanks! :)

**Comment by nukeador** [comment]
@brianking ping

**Comment by brianking** [comment]
What is the goal here? To have all Council members post, or something else?

**Comment by MichaelKohler** [comment]
> What is the goal here? To have all Council members post, or something else?

Yes!

**Comment by MichaelKohler** [comment]
Do we have any other blog posts that are not mentioned here? Maybe we could then consolidate them into one for the Reps blog?

**Comment by nukeador** [comment]
Related: #9 #35

**Comment by nukeador** [comment]
@brianking did you push people to publish something before London? Do you need help? Thanks! :)

**Comment by brianking** [comment]
Just pinged council on Telegram about this. Yes, feel free to help @nukeador if you think this is important.

**Comment by umeshagarwal** [comment]
I will try to complete my blog post before All hands! @brianking :)

**Comment by MichaelKohler** [comment]
Is the goal still to share those blog posts? I'd suggest to focus on the future blog posts we want to get out to inform about the current status.

**Comment by MichaelKohler** [comment]
Let's close this and focus on the normal communication we should be doing now.
