### ISSUE TITLE
Publish RoM for March 2018

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#302]
## Goal: 
RoM for March 2018 is published.

## Related Issues & Links: 
https://reps.mozilla.org/v/rep-of-the-month-for-march-3/

## Roles:

Responsible: @MichaelKohler
Accountable: @ioana-chiorean 
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@MichaelKohler, Due: April 1st) 
- [x] Finalize text (@MichaelKohler, Due: April 7th) 
- [ ] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due: April 8th)

**Comment by MichaelKohler** [comment]
[done] Discourse: https://discourse.mozilla.org/t/rep-of-the-month-march-2018/27532
[done] reps-general / discourse
[pending] Blog post submitted for review
[pending] Henrik asked to put the date on the Portal back to March

**Comment by ioana-chiorean** [comment]
I think all points were done.

**Comment by MichaelKohler** [comment]
nope, blog post needs to be approved ;)

**Comment by couci** [comment]
published :)

**Comment by MichaelKohler** [comment]
Thanks!
