### ISSUE TITLE
Guidelines for Reps in order to start conversations with their communities about the Agreements

### ISSUE THREAD

**Issue by AlexLakatos** [mozilla/Reps#311]
## Goal: 
The Reps Council has delivered a set of guidelines for Reps in order to start conversations with their communities about the Agreements - Alex

## Related Issues & Links: 
#310 

## Roles:

Responsible: @AlexLakatos

Accountable: Reps Council

Supporting: @couci 

Consulted: Reps Council

Informed:  Reps

## Required: 

- [x] Review agreements
- [x] Create draft guidelines
- [ ] Coordination with Flore on guildelines that will go out to mentors
- [ ] get Council feedback on guidelines
- [ ] Publish guidelines

**Comment by Mte90** [comment]
https://docs.google.com/document/d/1ehX5T0a5fsyHI9ktyW5EN-D3ij0dPHO0rYI0OSvQOmQ/edit?hl=en the document
