### ISSUE TITLE
Housekeeping Telegramgroup remo mentors

### ISSUE THREAD

**Issue by Timmaks** [mozilla/Reps#312]
## Goal: 
make sure there are only mentors in the group

## Roles:

Responsible: @Timmaks

Accountable: @Timmaks

Consulted: Arturo

Informed: members of the group

## Required: 
- [x] pull a list of actual mentors from the portal  
- [x] pull a list of members from telegram
- [x] cross reference the lists
- [ ] remove old mentors
- [x] add new mentors if they have telegram

**Comment by Timmaks** [comment]
list: https://docs.google.com/spreadsheets/d/1PUAcPrTVoTwc2eWyhPz17K_aPYYmm5eD_EuioB8PhJs/edit?usp=sharing

**Comment by Timmaks** [comment]
i can not find the telegram account for 10 mentors, 6 mentors are added
send a message to 9 former mentors, 2 are removed all ready, the other 7 will be removed later this week

**Comment by Timmaks** [comment]
All the former mentors are removed or have left. Closing this issue

**Comment by ioana-chiorean** [comment]
Thanks s much for this work,  @Timmaks !
