### ISSUE TITLE
Mozilla Reps logo and branding

### ISSUE THREAD

**Issue by prathameshchavan** [mozilla/Reps#313]
## Goal: 
To create a new Mozilla Reps logo

## Roles:

Responsible: @prathameshchavan

Supporting: Mozilla Reps Council

## Required: 
- [x] Create a design 
- [x] Get it approved from the Branding and Marketing Team 
- [x] Announce

**Comment by kelimuttu** [comment]
Yaaaay! Finally, Reps official rebranding!!
Just wanted to add myself here so I get the latest update on this. Thanks for driving this, @prathameshchavan . I hope we'll get to hear great news very soon.

**Comment by kelimuttu** [comment]
Hey @prathameshchavan is there any link where I can track the design work? Who's working on it right now? And how's the progress?

**Comment by prathameshchavan** [comment]
Currently, there is no public tracking pad available. However, I am expecting this to be done during the San Francisco All-Hands 2018.

**Comment by yomanpatil** [comment]
@prathameshchavan please update the team on the updates that you got yesterday at Allhands.

**Comment by prathameshchavan** [comment]
![mozrep-final-outline](https://user-images.githubusercontent.com/10761249/42280302-f98eb69e-7fbd-11e8-9fb8-8adc867115ef.png)

![photo_2018-07-04_19-07-36](https://user-images.githubusercontent.com/10761249/42280303-f9fd6922-7fbd-11e8-8aab-77c32a18df9b.jpg)

**Comment by prathameshchavan** [comment]
Done! 

[](https://discourse.mozilla.org/t/announcement-mozilla-reps-logo/30210)

**Comment by prathameshchavan** [comment]
https://discourse.mozilla.org/t/announcement-mozilla-reps-logo/30210
