### ISSUE TITLE
Publish RoM for April

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#315]
## Goal: 
The RoM for April 2018 is published.

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@ioana-chiorean, Due: April 27th) 
- [ ] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due: April 29th)

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/rep-of-the-month-april-2018/28330
Telegram/reps-general: done
Portal: @Mte90 to do
Blog post: @couci please approve

Also I've asked tasos to date it back to April. Will close the issue once the blog post is live and the RoM entry has been back-dated.

**Comment by ioana-chiorean** [comment]
Thanks so much Michael!

**Comment by Mte90** [comment]
Yesterday I done the post in the portal :-)
