### ISSUE TITLE
Research before London Design Sprints

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#32]
## Goal: 
We have data spanning events, budget, activities and general feeling of Reps to work with in London.

## Related Issues & Links: 
https://github.com/mozilla/Reps/issues/11

## Roles:

Responsible: @nukeador 

Accountable: Reps Council

Supporting: @MichaelKohler @couci @akatsoulas Council

Consulted:

Informed: 

## Required: 
- [x] We agree on the proposed research activities we need to do (@MichaelKohler, Due: May 23th) 
- [ ] Gather data from budgets (@couci, Due: June11th) 
- [ ] Gather data from portal, activities (R: @couci S: @akatsoulas Due: June 11th) 
- [ ] 1:1s with Reps (council, Due: June 11th)

**Comment by nukeador** [comment]
I can own this one.

**Comment by nukeador** [comment]
* Council is getting ready for 1:1s with Reps.
* @couci is gathering data from budgets and getting support from @akatsoulas for portal

**Comment by MichaelKohler** [comment]
@nukeador are we going to share some feedback we got through that?

**Comment by MichaelKohler** [comment]
Research is done, we'll create a new one to share learnings
