### ISSUE TITLE
Publish RoM for May 2018

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#324]
## Goal: 
The RoM for May 2018 is published.

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@MichaelKohler, Due: June 15th) 
- [x] Review text (@MichaelKohler, Due: June 17th)
- [x] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due: June 17th)

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/rep-of-the-month-may-2018/29547
Telegram, reps-general are done. @couci blog post is submitted for review, thanks!

**Comment by couci** [comment]
published https://blog.mozilla.org/mozillareps/2018/06/22/rep-of-the-month-may-2018/

**Comment by ioana-chiorean** [comment]
Thanks @MichaelKohler  and @couci !
