### ISSUE TITLE
Clarity and document the support that the Reps program provides to Mentors

### ISSUE THREAD

**Issue by irvin** [mozilla/Reps#325]
## Related Issues & Links: 
This is in the Q2 OKRs 
https://docs.google.com/document/d/1B3dP-XlJHZV2M06vKEz36Iy3GOGpz37zVtcCJ5etoQo/edit#

And following the coaching draft 
https://docs.google.com/document/d/15bHJ3ZHtQfzf5hHlHEZu_iSLHx8Ra0U0aJignsBskVU/edit#heading=h.23i6yta63ux1

## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by irvin** [comment]
I'm reviewing the resources we have for mentor on WikiMo (as well as SOPs of mentoring), not finished yet. 
https://docs.google.com/document/d/1YgLv4eFF7SUyqY9oHrTLDemagjBD5V6ffV1_kr2NVwc/edit#

**Comment by MichaelKohler** [comment]
@irvin can this be closed as this is about a Q2 OKR, and not Q3?

**Comment by irvin** [comment]
yes sure

**Comment by irvin** [comment]
Actually it's not done so I'll label it as `any other business` and reopen it.

**Comment by irvin** [comment]
I'm not working on this for many months so I'm going to close this task.
