### ISSUE TITLE
 Council Elections - Autumn 2018 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#327]
## Goal:
- Hold the council election in order to occupy the spots that are free after the term of one year is ending for:

🎓 Prathamesh
🎓 Mayur

## Success:
- The elections take place and we have 2 new council members

## Related Issues & Links:
- Previous Elections #284, #208, #114, #15
 
## Roles:
Owner: @ioana-chiorean 
Involved: @couci, Reps Peers 
Informed: @nukeador

## Required:
- [x] 10.09.2018 - Plan Town Halls (@MichaelKohler)
- [x] 20.09.2018 - Timeline presentation and announcement in Reps Call / Discourse / Mailing list (@ioana-chiorean)
- [x] 23.09.2018 - Call for Nominees starts (1 week) (@ioana-chiorean) [DISCOURSE POST HERE.](https://discourse.mozilla.org/t/important-council-elections-autumn-2018-please-read/32036)
- [x] 29.09.2018 - Call for Nominees closes (@ioana-chiorean)
- [x] 01.10.2018 - Q&A starts on Discourse (1 week) (@ioana-chiorean)
- [x] 02.10.2018 - Nominees Q&A Town Hall Timezone 1 (@ioana-chiorean)
- [x] 04.10.2018 - Nominees Q&A Town Hall Timezone 2 (@ioana-chiorean)
- [x] 07.10.2018 - Deadline for answers in Discourse Q&A (@ioana-chiorean)
- [x] 08.10.2018 - Voting starts (1 week) (@ioana-chiorean)
- [x] 15.10.2018 - Voting closes (@ioana-chiorean)
- [x] 16.10.2018 - Voting Analysis is published (@MichaelKohler)
- [x] 16.10.2018 - Wiki Pages are updated (@MichaelKohler)
- [x] 20.10.2018 - New Council members have write access to GitHub Reps repo (@MichaelKohler)
- [x] 20.10.2018 - New Council members are in the OI Mozillians group (@MichaelKohler)
- [x] 22.10.2018 - Onboarding begins (@couci)
- [x] 27.10.2018 - New Council members are in the Council Mozillians group (@couci)
- [x] 27.10.2018 - New Council members are in the Telegram group (@couci)
- [x] 27.10.2018 - New Council members are in the reps-council alias (@couci)
- [x] 27.10.2018 - New Council members have access to Slack / #oi-team channel (@MichaelKohler)
- [x] 13.11.2018 - Onboarding is done and new Council is operational - new council members have confirmed they all have access to everything (@couci)
- [x] 13.11.2018 - Old Council members are removed from Telegram group (@couci)
- [x] 13.11.2018 - Old Council members are removed from OI Mozillians group (@MichaelKohler)
- [x] 13.11.2018 - Old Council members are removed from Council Mozillians group (@couci)
- [x] 13.11.2018 - Old Council members are removed from Reps GitHub collaborators (@MichaelKohler)
- [x] 13.11.2018 - Reps Portal is updated with new Council members in Council group (@couci)
- [x] 13.11.2018 - Blog announcement for new members + outgoing members is published (@couci)
- [x] 15.11.2018 - Mozilla Leadership Page is updated (@MichaelKohler)

## Updates required:
- [x] Create [13th entry](https://wiki.mozilla.org/ReMo/Council/History)
- [x] Update < if necessary> [requirements for council members](https://wiki.mozilla.org/ReMo/Council/Elections#Candidates)

**Comment by MichaelKohler** [comment]
Here’s a draft timeline I came up with just now. This will need to be discussed though.

**Edit: removed timeline as timeline above is adapted!**

We will be gathering additional feedback which might need to be incorporated here. So this is very drafty right now.

**Comment by ioana-chiorean** [comment]
Call for nominations was 
* posted
* mailed 
* promoted
https://discourse.mozilla.org/t/important-council-elections-autumn-2018-please-read/32036

**Comment by ioana-chiorean** [comment]
Mail for second step was sent out to the 6 applicants. We will be tracking their progress here. 
Discourse Thread: https://discourse.mozilla.org/t/important-council-elections-autum-2018-nominee-q-a/32246/3

1. [Vaibhav Bajaj](https://reps.mozilla.org/u/vabajaj/)
Mandatory:
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-autum-2018-nominee-q-a/32246/6?u=ioana)
Optional:
  - [ ] Video
  - [ ] Townhall 1 
  - [x] Townhall 2 
2. [Monica Bonilla](https://reps.mozilla.org/u/MonicaBonilla/)
Mandatory:
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-autum-2018-nominee-q-a/32246/7?u=ioana)
Optional:
  - [ ] Video
  - [x] Townhall 1 
  - [x] Townhall 2 
3. [Prathamesh Chavan](https://reps.mozilla.org/u/prathamesh/)
Mandatory:
  - [ ] [Answers](https://discourse.mozilla.org/t/important-council-elections-autum-2018-nominee-q-a/32246/2?u=ioana)
Optional:
  - [ ] Video
  - [x] Townhall 1 
  - [ ] Townhall 2 
4. [Mehul Patel](https://reps.mozilla.org/u/rowdymehul/)
Mandatory:
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-autum-2018-nominee-q-a/32246/4?u=ioana)
Optional:
  - [ ] Video
  - [ ] Townhall 1 
  - [x] Townhall 2 
5. [Mayur Patil](https://reps.mozilla.org/u/yomanpatil/)
Mandatory:
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-autum-2018-nominee-q-a/32246/5?u=ioana)
Optional:
  - [x] Video
  - [x] Townhall 1 
  - [x] Townhall 2 
6. [Yofie Setiawan](https://reps.mozilla.org/u/yofiesetiawan/)
Mandatory:
  - [x]  [Answers](https://discourse.mozilla.org/t/important-council-elections-autum-2018-nominee-q-a/32246/3?u=ioana)
Optional:
  - [ ] Video
  - [x] Townhall 1 
  - [x] Townhall 2

**Comment by ioana-chiorean** [comment]
Townhall 1: 
* Recording: https://onlinexperiences.com/Launch/Event.htm?ShowKey=44908&DisplayItem=E303748 2
* Etherpad: https://public.etherpad-mozilla.org/p/reps-elections-town-hall-1-2018-10-01

**Comment by MichaelKohler** [comment]
Town Hall 2:

* Recording: https://onlinexperiences.com/Launch/Event.htm?ShowKey=44908&DisplayItem=E305969
* Etherpad: https://public.etherpad-mozilla.org/p/reps-elections-town-hall-2-2018-10-04

**Comment by MichaelKohler** [comment]
* Asked the new members for their github usernames so I can add them with write access
* Asked Henrik to invite them to the OI team and slack-access / #oi-team slack channel if not done so yet

For @couci :
* Start the onboarding
* Add them to the Telegram group
* Add them to the Reps Council Mozillians group

**Comment by MichaelKohler** [comment]
Statistics posted: https://discourse.mozilla.org/t/council-elections-autumn-2018-statistics/32595

**Comment by MichaelKohler** [comment]
PR for leadership page on mozilla.org opened: https://github.com/mozilla/bedrock/pull/6362

**Comment by MichaelKohler** [comment]
The Leadership page is updated: https://www.mozilla.org/en-US/about/leadership/

**Comment by MichaelKohler** [comment]
All done!
