### ISSUE TITLE
Publish Reps of the Month for the past months

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#33]
## Goal: 
We are up to date with the publication of "Reps of the Month" again and we don't have a backlog and can focus on the upcoming months.

## Roles:

Responsible: @MichaelKohler

Accountable: @MichaelKohler

Supporting: @ioana-chiorean , @akatsoulas (to set the date back on the portal)

## Required: 
- [x] Publish RoM for January 2016 on Portal/Blog (@MichaelKohler / @ioana-chiorean, Due: May 23th) 
- [x] Publish RoM for February 2016 on Portal/Blog (@MichaelKohler / @ioana-chiorean, Due: May 26th) 
- [x] Publish RoM for March 2016 on Portal/Blog (@MichaelKohler / @ioana-chiorean, Due: May 30th) 
- [x] Publish RoM for April 2016 on Portal/Blog (@MichaelKohler / @ioana-chiorean, Due: June 3th)

**Comment by MichaelKohler** [comment]
Published through Discourse (https://discourse.mozilla-community.org/t/rep-of-the-month-january-2016/8849), reps-general and Portal. Tasos will date it back on the portal once he has time for it. Blog post is in review for @nukeador

**Comment by MichaelKohler** [comment]
Published RoM for February on blog (https://blog.mozilla.org/mozillareps/2016/05/26/rep-of-the-month-february-2016/), Discourse (https://discourse.mozilla-community.org/t/rep-of-the-month-february-2016/8913), Portal and reps-general.

**Comment by MichaelKohler** [comment]
Published on Portal (needs backdate by @akatsoulas), published on [Discourse](https://discourse.mozilla-community.org/t/reps-of-the-month-march-2016/8970) and blog post is waiting for approval (maybe @rosanardila could help here?). Mail to reps-general is sent.

**Comment by hmitsch** [comment]
@michaelkohler, is there a link to that draft blog post? What kind of approval are you looking for? Maybe a Peer could help?

**Comment by MichaelKohler** [comment]
> @michaelkohler, is there a link to that draft blog post? What kind of approval are you looking for? Maybe a Peer could help?

There is, but you probably can't see it without being logged in. The text is already peer-reviewed, therefore should be fine. The kind of approval I'm looking for is built into the blog system. I only have permission to submit new blog posts for review. Then somebody who has reviewer-privileges on the blog can approve it and then it's being published. Rosana unfortunately can't reset her password and Nuke is out until Thursday. Could somebody think of an easy way to actually figure out who has these privileges on the blog?

**Comment by MichaelKohler** [comment]
Published April on Discourse (https://discourse.mozilla-community.org/t/rep-of-the-month-april-2016/9121), Portal and reps-general. Blog post needs review, Nuke is gonna do that in a few minutes. As well as the one for March.

**Comment by MichaelKohler** [comment]
@nukeador I've corrected the layout, please approve it ASAP on the blog. Then we can close this issue.

**Comment by nukeador** [comment]
Done

**Comment by MichaelKohler** [comment]
https://blog.mozilla.org/mozillareps/2016/06/07/rep-of-the-month-april-2016/ and https://blog.mozilla.org/mozillareps/2016/05/30/rep-of-the-month-march-2016/

**Comment by brianking** [comment]
Epic job getting caught up on these Michael, thank you.
