### ISSUE TITLE
Onboarding Screening Team 2018-2 applications

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#333]
## Goal: 
As explained on https://discourse.mozilla.org/t/do-you-want-join-the-onboarding-screening-team-for-2018-2/29713.
If you want to join leave your name here but not forget to read the Discourse thread and the wiki (https://wiki.mozilla.org/ReMo/Webinar/Screening) about it.

## Roles:

Responsible: @mte90

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [x] Gather applications (@mte90, Due: Jul 12th) 
- [x] Discuss with Council about the applications (@Mte90, Due: Jul 12th) 
- [ ] Published new team members (@Mte90, Due: Jul 20th) 
- [ ] Publish blogpost about previous and new team (owner, Due: Jul 22th)

**Comment by hellokarthic** [comment]
Count me in. I'd love to be part of the team.

**Comment by Ruwan-Ranganath** [comment]
I'm definitely available for this. 

Thank you.

**Comment by bunnybooboo** [comment]
Please consider me for this people focused role. During the next 6 months I will also be busy curating the Mozilla Festival, but feel the selection of active fellow Reps as a hugely important alignment with my local onboarding activities.

**Comment by gurumukhi** [comment]
I would like to take this opportunity to be part of this team and take the responsibilities :-) 👍

**Comment by gaby2300** [comment]
Count me in please!

Best regards,
Gabriela

**Comment by smsnobin77** [comment]
I'm available for these six months. You can count me.

Cheers!
Sarwar

**Comment by ranjithrajv** [comment]
I'm available for next 6 months, count me in.

**Comment by rtsayles** [comment]
Please count me in (smiles)

**Comment by balapandu222-zz** [comment]
Please, Count me in. I'm available for next 6+ months.
Regards,
Bala

**Comment by Timmaks** [comment]
I am available for the next 6 months:-)

**Comment by nomadicmehul** [comment]
Count me in. I'd love to be part of the team.

**Comment by rabimba** [comment]
Interested.
Though not entirely sure if I am eligible. But interested nevertheless.

**Comment by roshangm1** [comment]
I am available for next 6 months. Interested very much. :)

**Comment by Mte90** [comment]
The council started voting and discuss the applications. I will let you know when it's finished.

**Comment by Mte90** [comment]
The council voted but I am waiting to publish the blogpost to publish the names :-)

**Comment by Mte90** [comment]
Names published: https://blog.mozilla.org/mozillareps/2018/08/08/onboarding-team-for-2nd-half-of-2018/

Thanks to everyone!
