### ISSUE TITLE
Change Mozilla Reps logo on online platforms

### ISSUE THREAD

**Issue by yomanpatil** [mozilla/Reps#335]
## Goal: 
We will need to change the logo on all our existing platforms.

## Platforms:

- [x] 1. [Reps portal](https://reps.mozilla.org) - Owner: @MichaelKohler
- [x] 2. [Facebook page](https://www.facebook.com/MozillaReps/) - Owner: @couci 
- [x] 3. [Twitter account](https://twitter.com/mozillareps) - Owner: @couci 
- [x] 4. [Reps Wiki](https://wiki.mozilla.org/Websites/ReMo_Mozilla_Reps) and [Reps Banner Template](https://wiki.mozilla.org/Template:Remonav) - Owner: @MichaelKohler
- [x] 5. [Wikipedia page](https://en.wikipedia.org/wiki/Mozilla#Mozilla_Reps) - Owner: @yomanpatil 
- [x] 6. Telegram group - Owner: @MichaelKohler 
- [x] 7. Telegram channel - Owner: @yomanpatil 
- [x] 8.  [New reps link](http://mozilla.github.io/Reps/newreps/) - Owner: @MichaelKohler 
- [x] 9. Air Mozilla should have the new Logo in thumbnails etc - Owner: @MichaelKohler
- [x] 10. Upload Logos etc to Reps repo - Owner: @MichaelKohler
- [x] 11. Update Blog - Owner: @MichaelKohler

Please help me find the right person for each platform.

**Comment by yomanpatil** [comment]
@couci I think you can help me with social media accounts
@MichaelKohler I think you can help me with reps portal and reps wiki

**Comment by MichaelKohler** [comment]
Yes, I can help with the Wiki and the Portal.

Do we really want to change the icon in the Telegram channel? I don't think the new logo looks good in that setting - would probably be cut off, and we are not going away from the icon itself.

**Comment by yomanpatil** [comment]
we can only put the new icon on the telegram channel. Most of the reps are active on that channel

**Comment by MichaelKohler** [comment]
Ah, you mean as in "This is the new one" as announcement and not replacing the logo of the group?

**Comment by yomanpatil** [comment]
ok no issues

**Comment by ioana-chiorean** [comment]
I've added - [ ]  to each entry. Can you pls check which is done and by who? 
Do you still need help with any of these? 

Thanks! 🙇‍♀️

**Comment by MichaelKohler** [comment]
I'm waiting until @yomanpatil gives me the go to start it. But I suppose we want to do everything in more or less the same timeframe. The Portal will come after the rest though, as I'll need to do a PR and then we might not super fast get a deployment.

**Comment by yom** [comment]
Hi folks, I think there's a typo in your 6th entry. Cheers !

**Comment by MichaelKohler** [comment]
Hah, correct. Sorry about the ping @yom :)

**Comment by yomanpatil** [comment]
Here is the link to the new logo file

https://drive.google.com/open?id=1M80zSrx640Ve7chhrmwn08RO0s6HnN5n

The logo which is on top is the approved. Kindly ignore the one in the bottom

**Comment by yomanpatil** [comment]
How do we proceed? Can we do this by Friday ie 6th ?

**Comment by MichaelKohler** [comment]
I can do it either *until* or *on* Friday for the wiki. I can also create the PR for the portal, but I can't guarantee we will get a deployment. 

I think it would be nice to do everything in approximately the same time frame on Friday, what do you think?

**Comment by MichaelKohler** [comment]
Looking at the file, we still need the export to png/svg for the top logo, otherwise we can't replace it on any of the necessary platforms.  @yomanpatil

**Comment by MichaelKohler** [comment]
I've uploaded a png we can use for the Reps telegram channel

**Comment by yomanpatil** [comment]
@MichaelKohler we also need to change the logo here
[new reps link](http://mozilla.github.io/Reps/newreps/)

**Comment by MichaelKohler** [comment]
Reps Portal will be deployed tomorrow. Will report back once done.

**Comment by MichaelKohler** [comment]
Wiki done: https://wiki.mozilla.org/ReMo

**Comment by MichaelKohler** [comment]
@yomanpatil from what I see the following is open:

1) Wikipedia
2) Air Mozilla (assigned task to me)
3) Make resources available on GitHub repo (assigned task to me)

Can you do Wikipedia?

Also, I've left of http://planet.mozillareps.org/ as it's heavily outdated and I'll follow up with a general discussion soon.

**Comment by MichaelKohler** [comment]
Bug for AirMo filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1477480

**Comment by MichaelKohler** [comment]
Bug for Reps Blog filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1477481

**Comment by MichaelKohler** [comment]
@yomanpatil any news about wikipedia? I've pinged in my bugs to get those moving forward as well.

**Comment by yomanpatil** [comment]
Oh that thing is pending. 
On it will update you tomorrow!

**Comment by MichaelKohler** [comment]
Reps blog and AirMo is done! @yomanpatil feel free to close this issue once Wikipedia is done as well.

**Comment by MichaelKohler** [comment]
@yomanpatil ping here ;)

**Comment by TannerFilip** [comment]
> @yomanpatil ping here ;)

I've done this - https://en.wikipedia.org/w/index.php?title=Mozilla&diff=861768980&oldid=861137297

**Comment by MichaelKohler** [comment]
Thanks a lot Tanner!

**Comment by yomanpatil** [comment]
thank you for your help @TannerFilip :) :)
