### ISSUE TITLE
Reps Council Elections (04-2018) Feedback Form

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#336]
## Goal: 
We have sent out a feedback form to gather feedback about the recent (04-2018) Reps Council Elections.

## Related Issues & Links: 
Very drafty - please do NOT fill out yet: https://docs.google.com/forms/d/e/1FAIpQLSf91X-v0oNiRjWFkR_BckWhr3dVOxpt6wtM1-hfopiKwqz6Pw/viewform

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Peers
Supporting: @ioana-chiorean @hmitsch 

## Required: 
- [x] Create initial draft according to discussed points (@MichaelKohler, Due: July 10th) 
- [x] Initial review (@ioana-chiorean , Due: July 15th) 
- [x] Get feedback from Megan/Rina on last question (@hmitsch , Due: July 17th) 
- [x] Write communication for Reps (@MichaelKohler, Due: July 17th) 
- [x] Incorporate Megan/Rina feedback (@MichaelKohler, Due: July 19th) 
- [x] Send out form (@MichaelKohler, Due: July 19th) 
- [x] Regular reminders (@MichaelKohler, Due: August 2nd) 
- [x] Close feedback form (@MichaelKohler, Due: August 7th) 
- [x] Analyze responses (@anknite, Due: August 15th) 
- [x] Add recommendations (@anknite, Due: August 27th)

**Comment by mbransn** [comment]
Hi @MichaelKohler,

I would suggest making these copy updates:

>Do you feel the questions on Discourse did bring value to you?

Suggestion: `Did you find the questions on Discourse valuable?`

>Do you feel the candidate videos did bring value to you?

Suggestion: `Did you find the candidate videos valuable?`

>Do you have any suggestion for improvement for the next elections?

Suggestion: `How would you improve the next elections?`

For section 3, perhaps add this in addition to the current question (if you find it valuable):

`Please tell us why you weren't able to vote`

**Comment by MichaelKohler** [comment]
Thanks for the fast feedback, @m-branson! I did the copy updates, these are way better understandable. For the additional question I see value of having it, I will double check with the other Peers.

Thanks again!

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/feedback-for-reps-council-spring-elections/30241
Also posted on reps-general as well as the Reps Telegram group.

**Comment by MichaelKohler** [comment]
@anknite will create a summary of the responses with recommendations here: https://docs.google.com/document/d/1pIAxm15RLoT0TdSw1XgxRZsKxoIvxNF2HJfsTHAwK3A/edit#

**Comment by MichaelKohler** [comment]
This is done, we have some improvements we will implement in the upcoming elections. The first one being the recently announced Town Halls.
