### ISSUE TITLE
Addition to Mozilla Reps Peers - Ankit Gadgil 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#338]
## Goal: 
In our efforts to diversify the Reps Peers governance body, we are proposing Ankit Gadgil from Pune, India to be added to the Reps Peers. 

## Roles:
Responsible: @ioana-chiorean 
Accountable: Reps Module Ownership
Supporting: @MichaelKohler
Consulted: mozilla.governance
Informed: Reps

## Required: 
- [x] Announce on mozilla.governance list and wait a bit to make sure there is no show-stopper  (Ioana Due: July 25th) 
- [x] Gather feedback from  mozilla.governance list  (Ioana Due: July 30th) 
- [x] Add to module page on Wiki (@ioana-chiorean)
- [x] Announce to all Reps through Discourse (@ioana-chiorean)
- [x] Add to reps-peers email alias
- [x] Add to Discourse reps_leadership group
- [x] Add to https://mozillians.org/en-US/group/open-innovation-reps-council (gives access to the shared folder we use for the meeting notes for example) (@MichaelKohler via George)
- [x] Add group on Reps Portal to profile of new Peer (@ioana-chiorean)
- [x] Add to Council/Peers telegram group (@ioana-chiorean)

**Comment by ioana-chiorean** [comment]
- Mail sent to confirm on governance 
- Wiki changed https://wiki.mozilla.org/Modules/Mozilla_Reps
- Posted on Discourse too https://discourse.mozilla.org/t/addition-to-mozilla-reps-peers-ankit-gadgil/30868
- Mail the list too
- added him to telegram

**Comment by MichaelKohler** [comment]
Mailed @couci and George for the other two tasks. @ioana-chiorean can you also take the profile edit one?

**Comment by MichaelKohler** [comment]
@anknite Leo has added you to the reps_leadership Discourse group. This should allow you to see the Discourse Council alias emails as well as the inbox at https://discourse.mozilla.org/u/AnkitG/messages/group/reps_leadership. Could you please verify and if ok close this issue? Thanks!

**Comment by MichaelKohler** [comment]
All tasks done! yay!
