### ISSUE TITLE
Publish RoM for July 2018

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#339]
## Goal: 
The RoM for July 2018 is published.

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@MichaelKohler, Due: Aug 8th) 
- [x] Review text (@MichaelKohler, Due: August 15th)
- [ ] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due: August 17th)

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/rep-of-the-month-july-2018/30819
reps-general: done
Telegram: done

Blog post: @couci  please approve :)

Also asked tasos to date the Portal entry back to July.

**Comment by MichaelKohler** [comment]
Date on the Portal is fixed. @couci please close this issue once the blog post is published. Thanks!

**Comment by couci** [comment]
published https://blog.mozilla.org/mozillareps/2018/08/10/rep-of-the-month-july-2018/
