### ISSUE TITLE
List of Reps without NDA access group

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#340]
## Goal: 
We have a list of Reps that have an account on the Reps Portal but are not part of the NDA access group on mozillians.org anymore.

Bonus: have a list of Reps that are not part of the slack-access access group (just for fun for now..)

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council

## Required: 
- [x] Best solution identified (@MichaelKohler, Due: Aug 20th) 
- [x] Lists created (ParSys, Due: Aug 28th)

**Comment by Mte90** [comment]
I am thinking if add something also about if they configured the google identity provider

**Comment by MichaelKohler** [comment]
> I am thinking if add something also about if they configured the google identity provider

That would be useful for you to see who from the Mentors group hasn't yet configured a google provider, correct?

**Comment by Mte90** [comment]
Yes and to avoid to support all of them privately but will help also for access the NDA folder on drive.

**Comment by hmitsch** [comment]
Hi @Mte90 and @MichaelKohler, we will add the following scope item to our **Sprint Epsilon** scope (tomorrow):


> **ParSys KTLO: Reps Queries preparing Discourse access management**
> 
> - Question 1: Which of the currently active 284 Reps have a Mozillians.org profile linked on their ReMo profile?
> - Question 2: Of the Question 1 Results who is part of the NDA Group?
> - Question 3a: Of the Question 2 Results who is also part of Slack Access Group?
> - Question 3b: Of the Question 2 Results who has a Google IDP?


If we misunderstood, please let us know in the next 24 hours. :-)

-Henrik & @johngian

**Comment by MichaelKohler** [comment]
Thanks Henrik. Can we adapt to the following?

> **ParSys KTLO: Reps Queries preparing Discourse access management**
> 
> * Question 1: Which of the currently active 284 Reps have a Mozillians.org profile linked on their ReMo profile?
> * Question 2: Of the Question 1 Results who is **not** part of the NDA Group?
> * Question 3a: Of the Question **1** Results who is **not** part of Slack Access Group?
> * Question 3b: Of the Question **1** Results who has **not** a Google IDP?
> * Question 4: Who has an invalid Mozillians.org account link in their Reps profile and therefore are not counted in any questions?

**Comment by Mte90** [comment]
Yes a check is amazing :-D
I am wondering if add also one about 2FA enabled on mozillians, because I received/supported few reps with issues on enabling that or that they didn't know about this change.

**Comment by hmitsch** [comment]
@Mte90 excellent, I add another question:
> - Question 5: Of the _Question 1 Results_ who does not have MFA enabled?

**Comment by Mte90** [comment]
Perfect :-D

**Comment by hmitsch** [comment]
I changed our Sprint Goal according to feedback in Comments https://github.com/mozilla/Reps/issues/340#issuecomment-414312614 and https://github.com/mozilla/Reps/issues/340#issuecomment-414317714 .

**Comment by hmitsch** [comment]
As usual, thank you @Mte90 and @MichaelKohler !

**Comment by johngian** [comment]
I've already send the data to @MichaelKohler.

**Comment by MichaelKohler** [comment]
Thanks @johngian ! :)
