### ISSUE TITLE
 Publish RoM for August 2018

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#344]
## Goal: 
The RoM for August 2018 is published.

## Roles:

Responsible: @MichaelKohler, @ioana-chiorean
Accountable: Reps Council
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@ioana-chiorean, Due: Sept 1st) 
- [x] Review text (@MichaelKohler, Due: September 5th)
- [ ] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due: August 17th)

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/rep-of-the-month-august-2018/31269
Reps Portal, reps-general and Telegram are done!

@nukeador pinged to review the blog post and approve it.

**Comment by MichaelKohler** [comment]
This had been done, thanks Nuke!
