### ISSUE TITLE
Follow-up with Reps with unsigned NDA

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#345]
There are some Reps that haven't accepted the NDA invitation

https://discourse.mozilla.org/t/reps-not-in-nda-group-and-other-numbers/31313

We need to check them an figure out if they are employees, inactive or active. If active, reach out to make sure NDA is accepted.

**Comment by Mte90** [comment]
The question is again how we define who is inactive? 
And what to do when they are inactive?

**Comment by irvin** [comment]
duplicate with #348
