### ISSUE TITLE
KRK2.2 : 70% of the Reps are contributing at the success of the campaigns 

### ISSUE THREAD

**Issue by edovio** [mozilla/Reps#347]
## Goal: 
70% of the Reps are contributing at the success of the campaigns by either engaging other contributors to participate or contributing themselves. 

## Related Issues & Links: 
This is a part of the OKR3 
* Plan Doc: https://docs.google.com/document/d/1Qr1UwtkamKI5cWJcSJBmhQZtb14EpKM9gusoZWExbYI

## Roles:
@edovio - Take action and plan
@irvin - Review and informed person

Responsible:
@edovio 

Accountable:
@couci 
@nukeador 

Supporting:
@irvin 

Consulted:
Reps Council

Informed: 
Reps Council

## Required: 
- [X] G1: Publish a discourse post to introduce all the campaigns  (@edovio, Due: Sept 19th) 
- [x] G2: Create a Post to ask at the reps share the result of the new campaign with all the info (@edovio, Due: Sept 30th) 
- [x]  G3: Create a file with all the info from the Reps Portal of the events done for the campaign (@edovio, Due: Oct 7th)
- [ ] G4:  Create a thread for rep to suggest next campaign ideas (@edovio, Due: Oct 14th)
- [x] G5:  Collect the list of rep who had hosted a campaign event (@edovio Due: Oct 30th)

All the Due are updated after the delay of 2 weeks to revise the First Discourse post.
Another Delay that depend of the low participation in the discussion
Last Update: 23/10/2018

**Comment by edovio** [comment]
G1: Final Document: https://docs.google.com/document/d/1N_PvGbZH9IF5RQ5AWsA0XMu7PtAQ9PMBeXVHfme5-sA/edit?hl=en#

**Comment by edovio** [comment]
G2: Final Document: https://docs.google.com/document/d/1XE7RQpMEc6vYPmlVzjDL2mPbZ-4WIdt2bGVyxVbL52o/edit

**Comment by irvin** [comment]
G1 published, https://discourse.mozilla.org/t/we-want-you-for-the-new-campaign/31887
G2 published, https://discourse.mozilla.org/t/thank-you-for-participating-at-the-dark-funnel-campaign/32103/3

**Comment by edovio** [comment]
G3 & G5: Create a Spreadsheet with all the infos of the event made by reps: https://docs.google.com/spreadsheets/d/1PxThgspG4UoIE4q2l7LlF-_8Gvkst42MS0SukEtvH1A/edit?usp=sharing

**Comment by edovio** [comment]
Prepared a Message for the Vouch: https://docs.google.com/document/d/1q7j9qwQBeShA3G7O2m7FywK84zmD9NJjatuaGT5rRcc/edit

**Comment by edovio** [comment]
Made a Vouch at all the Reps/mozillians that have partecipated at the Dark Funnel Campaign and have less than three more information is on this SpreadSheet: https://docs.google.com/spreadsheets/d/1PxThgspG4UoIE4q2l7LlF-_8Gvkst42MS0SukEtvH1A/edit?usp=sharing

**Comment by edovio** [comment]
We will move with that on the new one Issue here on GitHub

**Comment by irvin** [comment]
We're done with this issue and not workin on it anymore, close.
