### ISSUE TITLE
Reps not in NDA group or not have a valid Mozillians url on portal

### ISSUE THREAD

**Issue by irvin** [mozilla/Reps#348]
## Goal: 
@MichaelKohler had found 25 reps without a valid Mozillians account link in rep profile, 
and 41 reps who is not in Mozillians NDA group. We need to fix it.

## Related Issues & Links: 
- https://discourse.mozilla.org/t/reps-not-in-nda-group-and-other-numbers/31313
- https://docs.google.com/spreadsheets/d/1x5YfxZSINc6pUuJTJSJ3A8EiZwsxYxXGW6850jYCvlQ/edit#gid=1542576045

## Roles:

Responsible: @irvin 

Accountable:

Supporting: @couci 

Consulted: @MichaelKohler 

Informed: 

## Required: 
- [x] Pinged reps without valid Mozillian URL to update the url (Irvin, Due: Oct 6th) 
- [x] Updated Mozillians link of all reps without valid one 
- [x] Get a list of active reps who is not in NDA group to Konstantina (Irvin, Due: Oct 6th) 
- [x] Add all active reps to the NDA group (Konstantina, Due: Oct 6th) 
- [x] Ping all active rep to accept NDA group invite (Irvin, Due: Oct 19th)

**Comment by irvin** [comment]
For those who don’t have valid Mozillians link, I had ping most on Telegram and updated 13 of them.

**Comment by irvin** [comment]
look also: #345

**Comment by irvin** [comment]
updated all mozillian accounts except one

**Comment by irvin** [comment]
update the list of active / inactive reps who are not in NDA group

**Comment by irvin** [comment]
Already pinned all of the Rep without NDA, and don't have 2fa enable for Mozillians.

**Comment by irvin** [comment]
fixed 42 reps, only 6 left to add to NDA group.

**Comment by irvin** [comment]
only 4 left to join NDA, who are

- Fauzia Ismail
- Frederick Villaluna
- Mubiru Jonathan
- Shinta Setiawan

**Comment by irvin** [comment]
I currently left two open bugzilla issue on changing login email on Mozillians and Reps portal regards this issue.

https://bugzilla.mozilla.org/show_bug.cgi?id=1519832
https://bugzilla.mozilla.org/show_bug.cgi?id=1520212

**Comment by irvin** [comment]
other reps who has not response would be fix on #362

**Comment by MichaelKohler** [comment]
closing this as we now have #370
