### ISSUE TITLE
Reps Applications Screening Round - Week of October 1st 

### ISSUE THREAD

**Issue by mermi** [mozilla/Reps#349]
## Goal: 
All open and ready applications are screened and informed. 

## Related Issues & Links: 
[Screening Sheet of Applicants](https://docs.google.com/spreadsheets/d/1WcQJCo38pwEIktErFm8KQDhA4eFSM6T5AYDS-6Oz1Tg/edit?usp=sharing)
 it's a private document as the decision concerns certain people.
## Roles:

Responsible: @mermi

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [x] Add applicants to the screening sheet (@mermi, Due: Oct 2nd) 
- [x] Reach out to rest of screening group and ask them to screen (@mermi, Due: Oct 2nd) 
- [x] Screen applications (@mermi, Due: Oct 10th)
- [x] Respond back to applicants (@mermi, Due: Oct 10th)
- [x] Proceed with Webinar for those who got approved (@mermi, Due: Oct 10th)

**Comment by ryanwarsaw** [comment]
Can we get an update on the deliverables here? I see they range from October 2nd, to 10th seeing as we're on the 15th wasn't sure if this wasn't updated or progress has been delayed.

**Comment by mermi** [comment]
it's blocked by the voting system - we (as council memebers) we need to talk about something related to the voting system before making the final decision.

**Comment by mermi** [comment]
We have one case of candidate we are waiting for more resources to send to be able to finalize the vote. Due date if that is Wednesday 7th. so I am keeping this issue open until that time.
