### ISSUE TITLE
Publish initial blog post about RepsNext with video

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#35]
## Goal: 
We want to publish an initial blog post about RepsNext with initial overall strategy information, the amazing video from Berlin, a transcript thereof, the currently decided parts and our next steps with an invitation to get involved.

## Related Issues & Links: 
related to: https://github.com/mozilla/Reps/issues/9
dependency: https://github.com/mozilla/Community-Design/issues/67

## Roles:
Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: Reps Council
Consulted: Reps Peers
Informed: Reps Peers

## Required: 
- [x] Draft outline for blog post (@MichaelKohler, Due: May 30th) 
- [x] Overview the finalization of the video (@MichaelKohler, Due: May 29th) 
- [x] Request review and feedback for the outline (@MichaelKohler, Due: May 30th)
- [x] Draft missing parts of the blog post together with Council members and Peers (@MichaelKohler, Due: June 7th)
- [x] Review from Council and Peers (@hmitsch, Due: June 10rd)
- [x] Integrate obtained feedback (if there was any) (@MichaelKohler, Due: June 11th)
- [x] Publish blog post (@MichaelKohler, Due: June 12th) 
- [ ] Open discourse topic for general feedback (@MichaelKohler, Due: June 12th) 
- [ ] Send mail to reps-general and link Discourse discussion and blog post (@MichaelKohler, Due: June 12th)

**Comment by nukeador** [comment]
Check with @rosanardila since she was already drafting something for #9

**Comment by hmitsch** [comment]
Bläh, I feel so old ... what do I need to do to be able to edit this post, @michaelkohler?

**Comment by hmitsch** [comment]
Suggested changes:
- add "Reps Peers" to Consulted and Informed
- change "get feedback and review on draft" to:
"Request review and feedback (@MichaelKohler)"
- add new items immediately below the above mentioned line:
"Review, due date XXX (@ Council and Peers)"
"Integrate obtained feedback (if there was any) (@MichaelKohler)"

The reason I'd change the wording is to avoid being blocked by the review. You move from pushing others to empower them to pull from the backlog.

**Comment by MichaelKohler** [comment]
> Bläh, I feel so old ... what do I need to do to be able to edit this post, @michaelkohler?

There should be an edit button on the top right of the post's header. But this is only if you're marked as collaborator on the repository which you are currently not. You might want to reach out to Nuke to get added as well.

> The reason I'd change the wording is to avoid being blocked by the review. You move from pushing others to empower them to pull from the backlog. 

Will edit in a second, thanks for the feedback!

**Comment by MichaelKohler** [comment]
Hi everyone, I'm sorry I let this slip. I update the timeline to be more realistic. I will create an outline we can discuss in a few minutes and after some initial feedback we can start drafting the blog post together. I don't think we'll need a lot apart from the video, but we nevertheless need to have some introduction, what it's about and next steps.

**Comment by MichaelKohler** [comment]
Hi everyone, I'm sorry I let this slip. I update the timeline to be more realistic. I will create an outline we can discuss in a few minutes and after some initial feedback we can start drafting the blog post together. I don't think we'll need a lot apart from the video, but we nevertheless need to have some introduction, what it's about and next steps.

**Comment by MichaelKohler** [comment]
I've started the outline here: https://docs.google.com/document/d/1FbDIuGUWllVVcAKSqfD0t_h66peO8D6SfAfmIUpGSNI/edit?usp=sharing

Since I already talked to @rosanardila and @hmitsch about reviewing the outline, could you please give your thoughts on it? I think that should capture the most essential parts we then can later follow up on.

I've also included the link to the video and wrote a transcript for accessibility and searching purposes.

Would be great to have all your feedback regarding the outline so we can start drafting the necessary parts and then publish this.

**Comment by hmitsch** [comment]
Hi @MichaelKohler, thanks for the transcript. Amazing work!

Not sure I fully understood your request. Moving ahead, I added a draft for the blog post. Hope this is what you expected?

In my opinion the blog post still needs the "Get Involved" links and the text I added needs to be reviewed/approved. Following that it would be ready to go.

**Comment by MichaelKohler** [comment]
Hi Henrik, I was looking for feedback for the outline (is that the topics we want to include in the blog post?). Thanks for adding the draft, that's already really good. I'd add something more about the working groups (for example that we mostly have implemented the Alignment proposal for example). What do you think? Then also our next steps for London.

I will add the "Get involved" links later today.

**Comment by MichaelKohler** [comment]
I'll add a few things tomorrow and send out a review request.

**Comment by MichaelKohler** [comment]
I've added some more text and links to the draft on https://docs.google.com/document/d/1FbDIuGUWllVVcAKSqfD0t_h66peO8D6SfAfmIUpGSNI/edit . Could you please review this so we can publish it early next week?

**Comment by hmitsch** [comment]
I added a section "**Moving beyond RepsNext**" to the draft post.
@MichaelKohler can you please review. Not sure the wording fits well?

**Comment by MichaelKohler** [comment]
Ready for approval on the blog by Nuke

**Comment by MichaelKohler** [comment]
This is now done: https://blog.mozilla.org/mozillareps/2016/06/16/repsnext-introduction-video/

Discourse: https://discourse.mozilla-community.org/t/repsnext-blogpost-with-video/9270

Mail sent to reps-general as well.
