### ISSUE TITLE
SLA  & CPG Best Practices &  Standards

### ISSUE THREAD

**Issue by omudongo** [mozilla/Reps#350]
## Goal: 
Develop a strategy to support communities in their comprehension process to implement each agreement in a way that suits local needs and cultural context (that which translates and can be shared with the Reps community and beyond)

## Related Issues & Links: 
1. [Reps are Aligned with the Shared Leadership Agreements and the Onboarding Aligned with Community Participation  Guidelines (CPG) ](https://docs.google.com/document/d/18ZwJxURpkmwrQfUrhm3vT6IdZJLk1lXgcKqbzanCvSk/edit?usp=sharing)

2. [SLA  & CPG Best Practices &  Standards](https://docs.google.com/document/d/1zwAZ4xPUi4vmxefI-onI1dD-AOkz2V9az1Le1_x4onI/edit?usp=sharing)

## Roles:

Responsible: @omudongo 

Accountable:

Supporting:

Consulted: @couci @Mte90 @yomanpatil @irvin @prathameshchavan 

Informed: 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Oct 12th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by MichaelKohler** [comment]
Closing this as it doesn't seem relevant anymore given the goals for the first half of 2019. Please feel free to reopen if it still is and update the timeline, description and current status.
