### ISSUE TITLE
Oarabile - Schedule meetings 1:1/1:2/1:3 with mentors 

### ISSUE THREAD

**Issue by omudongo** [mozilla/Reps#351]
## Goal: 
Schedule meetings 1:1/1:2/1:3 with Mentors and council members

## Related Issues & Links: 
https://github.com/mozilla/Reps/issues/337

## Roles:

Mentors Scheduled For Meeting: 

@Dinesh Mv  > Oarabile Mudongo
@Diwanshi Pandey > Oarabile Mudongo
@Trishul Goel mayur > Oarabile Mudongo

Responsible: @omudongo

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Oct 31st) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by MichaelKohler** [comment]
@Mte90 why did you close this? I think this is a good way to track progress here. I don't care if it's an issue per Council member or we keep everything in here, but somehow it should be tracked?

**Comment by MichaelKohler** [comment]
@omudongo what is the status here? is this done and can be closed?

**Comment by omudongo** [comment]
1:1 Call w/ Mentors Status

@dinesh Mv > No Reply
@diwanshi Pandey > Complete
@trishul Goel mayur > Pending

**Comment by omudongo** [comment]
Current Update on 1:1 Call w/ Mentors Status for @Mte90 

@dinesh Mv > No Reply
@diwanshi Pandey > Complete
@trishul Goel > Schedule (Friday 11, 2019)
