### ISSUE TITLE
Reps Weekly call survey

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/Reps#352]
## Goal: 
We gathered a set of data around reps weekly call in terms of timing, cadence, topic, and value.

## Related Issues & Links: 
#232, #48 

## Roles:

Responsible: @kelimuttu 

Accountable: @kelimuttu 

Supporting: @couci 

Consulted: @ioana-chiorean 

Informed: The rest of Reps council

## Required: 
- [x] Create the survey (owner: @kelimuttu , Due: Oct 11th) 
- [x] Review the survey (owner: @couci @ioana-chiorean , Due: Oct 12th) 
- [x] Launch & share thes survey (owner: @kelimuttu , Due: Oct 17th)
- [x] Gathered data from the past 3 months call (owner: @kelimuttu , Due: Oct 17th)
- [x] Gathered the data and wrap up [owner: @kelimuttu , Due: Oct 29th)

**Comment by MichaelKohler** [comment]
I suppose this supersedes https://github.com/mozilla/Reps/issues/48 and https://github.com/mozilla/Reps/issues/232 so these could be closed?

**Comment by kelimuttu** [comment]
I would say, this will complement the data that derived from issue #48 . But I would gladly cover tasks from those 2 issues (so we can close them), only if the related assignee are ok.

**Comment by MichaelKohler** [comment]
Let's close the other two and continue here. I don't think @irvin will mind as that issue is not part of OKRs anyway and therefore better suited with you :)

**Comment by ioana-chiorean** [comment]
> I would say, this will complement the data that derived from issue #48 . But I would gladly cover tasks from those 2 issues (so we can close them), only if the related assignee are ok.

I am ok for #48 issue

**Comment by kelimuttu** [comment]
Data from Q1-Q3 has been gathered here https://docs.google.com/spreadsheets/d/18VJHUzIQdESJFK-7G3xggH-UkDw5ZAApZ7__8cfPFjk/edit#gid=0

**Comment by kelimuttu** [comment]
This is done as per https://discourse.mozilla.org/t/reps-weekly-call-survey/32636/2
