### ISSUE TITLE
 Publish RoM for October 2018 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#355]
## Goal: 
The RoM for October 2018 is published.

## Roles:

Responsible: @MichaelKohler / @ioana-chiorean
Accountable: Reps Council
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@ioana-chiorean  Due:  October 29th) 
- [x] Review text (@MichaelKohler, Due October 30th)
- [x] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due:  October 30th)

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/rep-of-the-month-october-2018/33256
Blog post submitted for @couci's review.
Reps-general and Telegram done.

Asked @hmitsch to back-date the entry on the Reps Portal.

**Comment by MichaelKohler** [comment]
Blog post is published

**Comment by MichaelKohler** [comment]
Henrik has back-dated the entry on the Portal. All done, thanks everyone!
