### ISSUE TITLE
KR 2.1: Onboarding is completed successfully by 20% more applicants.

### ISSUE THREAD

**Issue by yofiesetiawan** [mozilla/Reps#357]
## Goal: 
O2: The program has a new onboarding that attracts community coordinators across the globe
KR 2.2 Onboarding is completed successfully by 20% more applicants

## Related Issues & Links: 
[Planification Document](https://docs.google.com/document/d/1LB-QETVFuMeWp3HT7b44LLw_39nCnEzhmd-jiFCi-Qc/edit?usp=sharing)
[Proposal KR2.1](https://docs.google.com/document/d/1hyZv2kY7glr0f7DwBxluM_VrbdPyy4PDvfiSt_ca1_Q/edit?usp=sharing)
[Reps Application 2018](https://docs.google.com/spreadsheets/d/1WcQJCo38pwEIktErFm8KQDhA4eFSM6T5AYDS-6Oz1Tg/edit#gid=1694124203)

## Roles:
Responsible: @yofiesetiawan 
Accountable:
Supporting: @Mte90 @mermi 
Consulted: @couci 
Informed: Reps Council

## Required: 

G1: Have a discussion with the current Screening Team and Reps Council to get feedbacks.
- [x] T1: Look up for feedbacks from current Screening Team and Reps Council. (D: 13/11/2018)
- [x] T2: Create proposal for Q4 O2 KR2.1  D: 16/11/2018)

G2: Make a post on Discourse to explain the new approach and collect feedback from Reps.
- [x] T1: Produce a Discourse message regarding Final Proposal (D: 14/12/2018)
- [x] T2: Wait a week and involve the council in the discussion  (D: 21/12/2018)

G3: Produce a Final proposal and cast the vote on the Council
- [x] T1: Finalizing Proposal  (D: 28/12/2018)
- [x] T2: Ask Feedback at the Council  (D: 04/01/2019)

G4: Modify the information on Mozilla Wiki
- [x] T1: prepare a new text to explain the proposal in the Wiki  (D: 11/01/2019)
- [x] T2: Ask Feedback at the Council (D: 18/01/2019)
- [ ] T3: Modify the Wiki & Reps Portal (D: 25/01/2019)

**Comment by MichaelKohler** [comment]
Closing this as it doesn't seem relevant anymore given the goals for the first half of 2019. Please feel free to reopen if it still is and update the timeline, description and current status.
