### ISSUE TITLE
KR 2.2: Onboarding duration is reduced by 30%.

### ISSUE THREAD

**Issue by edovio** [mozilla/Reps#358]
## Goal: 
KR 2.2: Onboarding duration is reduced by 30%.

## Related Issues & Links: 
This is part of the OKR4
 - Plan Doc : [Link](https://docs.google.com/document/d/1O7nSgdQeCw8OgrHJIXWMcl83pi1qDKdHE8W5mnM5IhI/edit#)

## Roles:

Responsible: Edoardo(@edovio)

Accountable: Kostantina (@couci), Ruben (@nukeador)

Supporting: Daniele (@Mte90) & Manel (@mermi)

Consulted:

Informed: 

## Required (Changed on 11/12/2018): 
- [x] G1: Have an open discussion with the other inside the council with a new proposed approach
    - [x] T1: Determine a new proposal to reduce the duration by 30% (@edovio, Due: 10/11/2018)
    - [x] T2: Have an open discussion collect feedback and produce a final proposal (@edovio, Due: 08/12/2018)

- [x] G2: Send an Email at all the Onboarding team with a proposal for evaluating the calc of the final vote 
    - [x] T1: A simplify proposal (@edovio, Due: 11/12/2018)
    - [x] T2: Send the Email at the Onboarding Team (@edovio, Due: 14/12/2018)

- [ ] G3: G3: Write a final proposal
    - [ ] T1: Write the proposal (@edovio, Due: 29/12/2018)

- [ ] G4: Modify the information on Mozilla Wiki
    - [ ] T1: prepare a new text to explain the proposal in the Wiki  (@edovio, Due: 05/01/2019)
    - [ ] T2: Ask Feedback at the Council (@edovio, Due: 08/01/2019)
    - [ ] T3: Modify the Wiki Page on the Mozilla Wiki (@edovio, Due: 15/01/2019)

**Comment by edovio** [comment]
G1 T1: deliverable [LINK](https://docs.google.com/document/d/1TuWHKWpOfEO5tSsTAaBDiY2y5rYUPnBlP3QvGPQYgxI/edit#)

**Comment by edovio** [comment]
G1 T2: Made during the All Hands in the Council Meeting

**Comment by edovio** [comment]
G2 T1: deliverable [LINK](https://docs.google.com/document/d/13PkHH7c7sCXN9YQOzWYdsSzx01-lwDqsXy3FDD7_C58/edit)

**Comment by edovio** [comment]
Updated the plan and Gantt Diagram about the KR2.2 after the feedback reached during the ALL HANDS.
[Plan Doc](https://docs.google.com/document/d/1O7nSgdQeCw8OgrHJIXWMcl83pi1qDKdHE8W5mnM5IhI/edit)
[Gantt Diagram Doc](https://docs.google.com/spreadsheets/d/12DjT80-TtG0Rz6t4wq6d4ExePQJocKhp0axzxKJGTHM/edit#gid=0)

**Comment by edovio** [comment]
sent the email today!

**Comment by edovio** [comment]
Document shared with the Onboarding Team: [Link](https://docs.google.com/document/d/1vDOgWLBv96X4RLy4nSlLH1Cdw0yhflHLmZve8MbhTP8/edit)

**Comment by MichaelKohler** [comment]
Closing this as @mermi is working on her OKR for the first half of the year. Please feel free to reopen if it still is and update the timeline, description and current status.
