### ISSUE TITLE
Reps call LATAM pilot

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/Reps#359]
## Goal: 
Run Reps call pilot call in Latin America timezone

## Related Issues & Links: 
This is a follow up from #352

## Roles:

Responsible: Kiki

Accountable: Kiki

Supporting: Konstantina

Consulted: Reps Council

Informed: Airmo team

## Required: 
- [x] Call for host announcement (@kelimuttu , Due: Nov 27th) 
- [x] Choose the host and lock the date (@kelimuttu , Due: Dec 7th) 
- [x] Inform the Airmo team (@couci , Due: Dec 7th)
- [x] 1st call prep (@kelimuttu , Due: Jan 7th, 2019)
- [x] 1st call (the host , Due: Jan 10th, 2019)
- [x] 2nd call prep (@kelimuttu , Due: Jan 21st, 2019)
- [x] 2nd call (the host , Due: Jan 24th, 2019)

**Comment by lasr21** [comment]
happy to collaborate

**Comment by MichaelKohler** [comment]
@kelimuttu given that the pilot is done, can we close this?

**Comment by kelimuttu** [comment]
yes, for sure..

**Comment by ioana-chiorean** [comment]
Do we have somewhere the results?

**Comment by kelimuttu** [comment]
there's only 1 person filled out the survey. But overall, I would say that the experiment went great, although it's hard to sustain it for now.
