### ISSUE TITLE
Publish missing Council meeting notes on Wiki

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#36]
## Goal:

All missing Council meeting notes since the end of 2015 are added to the Wiki: https://wiki.mozilla.org/ReMo/Meetings#Remo_Council_Weekly_Meetings . It seems this has been forgotten to mention to transfer in knowledge along our way. Since we're all human, this can happen, but we need to update this since this was a request some time ago. Discourse is nice for discussion, but not for archiving meeting notes.
## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
## Required:
- [ ] Create a draft for a survey to find out whether this is still needed or Discourse is enough (@MichaelKohler, Due: Aug 28th) 
- [ ] Analyze responses from Reps and come up with a proposal towards Reps Council (@MichaelKohler, Due: Sep 3rd)
- [ ] Decide within Reps Council on how to proceed (@MichaelKohler, Due: Sep 9th)
- [ ] Communicate decision (@MichaelKohler, Due: Sep 10th)
- [ ] if necessary - Publish missing notes and communicate necessity of wiki notes to new Council members (@MichaelKohler, Due: Sep 30rd)

**Comment by MichaelKohler** [comment]
I will start to transfer the notes to the Wiki starting this weekend. I've updated the dates in the initial description to reflect that.

**Comment by ioana-chiorean** [comment]
I think that will be nice to know moving further if we need them on wiki too ( it requires a lot of work and not sure how many people still read them there )

**Comment by MichaelKohler** [comment]
I have updated the initial description to a new timeline to reflect Ioana's comment regarding finding out whether we still need this or not. For now the Wiki page links to the Discourse category, so we should be fine. Let's find out if Reps actually look at this instead of Discourse and why (or what information is missing in Discourse)

**Comment by hmitsch** [comment]
I have Google Analytics access for Discourse and should be able to provide data for this question. Will look at this later.

@michaelkohler feel free to ping me in case I have not come back to this thread by Tuesday next week.

**Comment by hmitsch** [comment]
Google Analytics speaks a clear language ...

* [Discourse Analytics - Page Views - Reps Weekly Calls - 20160101-20160811.pdf](https://github.com/mozilla/Reps/files/414702/Discourse.Analytics.-.Page.Views.-.Reps.Weekly.Calls.-.20160101-20160811.pdf)
   * Reps Weekly Call minutes have a constant and significant audience.
   * 1.900 views by 1.200 people in the past 7 months.
* [Discourse Analytics - Page Views - Council Meeting Notes - 20160101-20160811.pdf](https://github.com/mozilla/Reps/files/414701/Discourse.Analytics.-.Page.Views.-.Council.Meeting.Notes.-.20160101-20160811.pdf)
   * Council meeting notes are barely accessed at all.
   * 27 views by 16 people in the past 7 months.
   * I guess this is mainly because these meeting minutes have only been made available recently, right?

@ioana-chiorean and @MichaelKohler your input/interpretation on my last point would be highly appreciated. Tobe honest, any other feedback is of course also appreciated.

**Comment by ioana-chiorean** [comment]
Well... 
Not really @hmitsch . The reps gets more attention as I also add nicknames in the texts, I share them more than the council and maybe event to a broader audience.  

My curiosity is for wiki pages - is anyone still looking at those notes? Cause the effort to publish them in both parts is considerable big. IMHO

**Comment by MichaelKohler** [comment]
Thanks @hmitsch for the numbers. There should be more pages for the Council meeting notes though, since we've published all of them on Discourse. I think the URL should not need to include "reps", then we can get all of them (for example: /council-meeting-notes-30-03-2016). Further it seems that not all views are counted (this could have different reasons: lazy loading, DNT, tracking protection, etc). The total view counts from Discourse range between 50 and 280. This is nothing compared to the Weekly Reps Call Notes though indeed. For that Ioana is right in terms of sharing. Here is the category sorted by view counter (these are not unique views though!): https://discourse.mozilla-community.org/c/reps/meetings?order=views

So I think we have one (or more) of the following questions to answer:
* Is there a general lack of interest or do we have a problem with visibility of those notes?
* Did Reps at the beginning check the notes, but didn't gain anything from it and stopped reading them?
* Is Discourse the wrong format and the wiki pages would have been read more than Discourse? (this is probably only possible via survey since we haven't published on the wiki after 2015)

For 2015 it would be nice to have the wiki view counters for each sub page. The wiki provides only the total views, but has Google Analytics as well, so we might be able to get all the data for all pages that match "https://wiki.mozilla.org/ReMo/Meetings/*".

I've gone through several of these pages and here are the total view counts:

Council-2015-12-23: 175
Council-2015-11-11: 282
Council-2015-11-04: 227
Council-2015-10-21: 285
Council-2015-10-14: 335
Council-2015-10-07: 295
Council-2015-09-30: 300
Council-2015-09-23: 273
Council-2015-09-16: 281
Council-2015-09-09: 308
Council-2015-09-02: 299
Council-2015-08-26: 348

One improvement we could make for the time being is to also publish the attendence on Discourse, as we have done with the wiki pages. What do you think?

Another thought of mine: the Wiki provides more visibility inside the organization since not everyone is using Discourse (or checking the Reps meetings category). For that reason we might want to keep the wiki pages around and double-post.

@hmitsch @ioana-chiorean what would you suggest should be the next step?

**Comment by hmitsch** [comment]
@ioana-chiorean and @MichaelKohler I am still trying to get access to the Google Analytics property for the wiki. Will let you know as soon as I have it.

**Comment by hmitsch** [comment]
@ioana-chiorean and @MichaelKohler, I have to admit I am a little confused of what kind of info you would like me to come up with ... 
However, I got access to the Google Analytics property for wiki.mozilla.org. This way I was able to do what @MichaelKohler asked above:
> get all the data for all pages that match "https://wiki.mozilla.org/ReMo/Meetings/*".

Here we go ...
[Wiki Analytics - Page Views - Meeting Notes - 20160101-20160814.pdf](https://github.com/mozilla/Reps/files/418068/Wiki.Analytics.-.Page.Views.-.Meeting.Notes.-.20160101-20160814.pdf)

**Interpretation:**
Almost nobody takes a look at meeting notes on the wiki.

Is this helpful? Should I provide any different data?

**Comment by MichaelKohler** [comment]
Thanks Henrik. What I'm really confused about is the difference between the numbers that are shown on the Wiki page and those in the report. Are those robots that the wiki is counting, but Google Analytics not? Let me try to figure that out. If the numbers from to Google report are accurate (plus the usual suspects like tracking blocking addons and tracking protection), I don't think there is a real value in publishing them. In that case I'd rather do a survey on how we could improve our communication regarding our meetings on Discourse.

**Comment by hmitsch** [comment]
Can you post a screenshot of the wiki numbers to make sure I understand what you mean?

-- 
Henrik Mitsch

**Comment by MichaelKohler** [comment]
Looks like this is not that easy to find out actually:

* It seems like MediaWiki is counting every visit (even bots) if they are not explicitely disallowed through detection mechanisms
* Google Analytics is counting the views from bots as well, if they are crawling with JavaScript enabled (which Google bots do to some extend nowadays). They could filter it out though, so I don't really know.
* 4 out of 285 (for the meeting on 2015-11-11) seems very low to me, that would mean that only roughly 1.4% would have not used any tracking blocker. On the other hand, this is mostly Mozillians visiting that page I'd guess..

Is there any other way we could find out about that?

@hmitsch every wiki page has its access count on the bottom of the page (in the footer), like "This page has been accessed 288 times." for https://wiki.mozilla.org/ReMo/Meetings/Council-2015-11-11. I don't have the numbers as a nice sheet, I just hand-compiled them from the pages and posted it in https://github.com/mozilla/Reps/issues/36#issuecomment-239395100 .

**Comment by hmitsch** [comment]
Ack ... and argh ...
@MichaelKohler I can confirm that I also see the diverging numbers. This is an issue. Not sure how to progress from here ... need to sleep over this ...

**Comment by MichaelKohler** [comment]
@hmitsch do you agree that it would make sense to get out a general survey on the following questions (and maybe missing ones) before continuing here?

* What do you like about the Council notes?
* What are you missing from the Council notes published to Discourse?
* Choose one
** I rather look at the Council notes in Discourse
** I rather look at the Council notes in the Wiki
** I rather look at the Council notes in both systems -> if so, field to explain why

**Comment by MichaelKohler** [comment]
Let's see what the survey of https://github.com/mozilla/Reps/issues/73 will bring to the table and the following work on communication channels and content and then we can decide here.

**Comment by MichaelKohler** [comment]
Closing this one since there is already a link to the Discourse category and we are currently discussing the channels over in #73. This is okay for now.
