### ISSUE TITLE
Iterate on Reps Peers Role to all Reps

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#360]
## Goal: 
We have published https://discourse.mozilla.org/t/reps-peers-update-to-role-description-council-accountability-update/31241 before. However, we are not sure if everyone actually knows what we do. We should enforce this communication.

## Related Issues & Links: 
https://discourse.mozilla.org/t/reps-peers-update-to-role-description-council-accountability-update/31241
https://wiki.mozilla.org/ReMo/Peers

## Roles:

Responsible: @ioana-chiorean 
Accountable: @ioana-chiorean 
Supporting: Reps Peers
Informed:  Reps

## Required: 
- [ ] Join Reps Call to iterate on Peers role (@ioana-chiorean, Due: 09.05.2019)
- [ ] Ask Reps to ask questions for Peers / tell what they would like to see Peers doing more (@ioana-chiorean , Due: 09.05.2019)

**Comment by MichaelKohler** [comment]
Discussed in today's Peer meeting, added the required steps.

**Comment by MichaelKohler** [comment]
Informed Kiki about us joining the Reps Call on the 2nd of May.

**Comment by Timmaks** [comment]
do we need this again or shall we close this issue
