### ISSUE TITLE
Reps are Contributing to MDM Campaigns - Spreadsheet

### ISSUE THREAD

**Issue by omudongo** [mozilla/Reps#364]
## Goal: 
Share spreadsheet to collect campaign ideas from Mozilla Reps. 

## Related Issues & Links: 
Campaign ideas will be collected via [spreadsheet](https://docs.google.com/spreadsheets/d/1yEtHMjBTWoY3UYCok-sc2UQgqp-CoBQ8za76ZNp8x6A/edit?usp=sharing)

## Roles:

Responsible: @Gute @omudongo 

Accountable:

Supporting: @couci 

Consulted: @couci 

Informed: 

## Required: 
- [ ] Collect campaign ideas from Mozillians (owner @omudongo @Gute , Due: Feb 1st)

**Comment by MichaelKohler** [comment]
Closing this as it doesn't seem relevant anymore given the goals for the first half of 2019. Please feel free to reopen if it still is and update the timeline, description and current status.
