### ISSUE TITLE
 Publish RoM for November 2018 

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#365]
## Goal: 
The RoM for November 2018 is published (we know, we are late with this).

## Roles:

Responsible: @MichaelKohler / @ioana-chiorean
Accountable: @ioana-chiorean 
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@ioana-chiorean  Due: January 12th) 
- [x] Review text (@MichaelKohler, Due January 13th)
- [x] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due:  January 14th)

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/rep-of-the-month-november-2018/36599
reps-general, Telegram are done as well.

@couci please approve the blog post (already submitted) and then close this issue here. Thanks!

**Comment by couci** [comment]
approved
