### ISSUE TITLE
Council Elections - H1 2019

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#366]
## Goal:
Hold the Council elections in order to occupy the spots that are free after the term of one year is ending for:

🎓 Daniele
🎓 Edoardo
🎓 Irvin
🎓 Manel
🎓 Oarabile

We have 5 open spots, one of them is limited to 6 months, see https://discourse.mozilla.org/t/proposal-balancing-out-open-spots-for-reps-council-elections/32961 for more details.

## Success:
The elections take place and we have 5 Council members

## Related Issues & Links:
- Previous Elections #15, #114, #208, #284, #327
 
## Roles:
Owner: @ioana-chiorean 
Involved: @couci, Reps Peers 
Informed: @nukeador, Reps

## Required:
(format of the dates is DD.MM.YYYY)

### Planning
- [x] 10.03.2019 - Plan Town Halls (@MichaelKohler)
- [x] 21.03.2019 - Timeline presentation and announcement in Reps Call / Discourse / Mailing list (@ioana-chiorean)
- [ ] 21.03.2019 - FAQ (@ioana-chiorean)

### Nomination & Campaigning
- [x] 23.03.2019 - Call for Nominees starts (1 week) (@ioana-chiorean) [DISCOURSE POST HERE.](https://discourse.mozilla.org/t/important-council-elections-h1-2019-please-read/37299)
- [x] 23.03.2019 - Share invitation for candidating on Mailing List (@ioana-chiorean)
- [x] 23.03.2019 - Share invitation for candidating on Telegram (@ioana-chiorean)
- [x] 29.03.2019 - Call for Nominees closes (@ioana-chiorean)
- [x] 01.04.2019 - Q&A starts on Discourse (1 week) (@ioana-chiorean)
- [x] 02.04.2019 - Nominees Q&A Town Hall Timezone 1 (@ioana-chiorean)
- [x] 04.04.2019 - Nominees Q&A Town Hall Timezone 2 (@ioana-chiorean)
- [x] 07.04.2019 - Deadline for answers in Discourse Q&A (@ioana-chiorean)

### Voting
- [x] 08.04.2019 - Voting starts (1 week) (@ioana-chiorean)
- [x] 08.04.2019 - Tweet about voting (@MichaelKohler)
- [x] 15.04.2019 - Voting closes (@ioana-chiorean)
- [x] 16.04.2019 - Voting results published (@ioana-chiorean)
- [x] 16.04.2019 - Voting Analysis is published (@MichaelKohler)

### Onboarding
- [ ] TBD - Call with Nominees & Peers to make sure they understand accountability (@anknite )
- [x] 16.04.2019 - Wiki Pages are updated (@MichaelKohler)
- [x] 18.04.2019 - New Council members have write access to GitHub Reps repo (@MichaelKohler)
- [x] 18.04.2019 - New Council members are in the OI Mozillians group (@couci)
- [x] 23.04.2019 - Onboarding begins (@couci)
- [x] 23.04.2019 - New Council members are in the Council Mozillians group (@couci)
- [x] 23.04.2019 - New Council members are in the Telegram group (@couci)
- [x] 23.04.2019 - New Council members are in the reps-council alias (@couci)
- [x] 23.04.2019 - New Council members have access to Slack / #oi-team channel (@MichaelKohler)
- [x] 07.05.2019 - Onboarding is done and new Council is operational - new council members have confirmed they all have access to everything (@couci)
- [ ] 07.05.2019 - Old Council members are removed from Telegram group (@couci)
- [x] 07.05.2019 - Old Council members are removed from OI Mozillians group (@couci)
- [x] 07.05.2019 - Old Council members are removed from Council Mozillians group (@couci)
- [x] 07.05.2019 - Old Council members are removed from Reps GitHub collaborators (@MichaelKohler)
- [x] 07.05.2019 - Reps Portal is updated with new Council members in Council group (@couci)
- [ ] 07.05.2019 - Blog announcement for new members + outgoing members is published (@couci)
- [x] 07.05.2019 - Mozilla Leadership Page is updated (@MichaelKohler)

## Updates required:
- [x] Create [14th entry](https://wiki.mozilla.org/ReMo/Council/History)

## Dependencies:
- [x] Verify if there are any regional holidays/festivities during the election period (e.g. Catholic Easter).
- [x] All Hands invites: Check with Konstantina or Brianna about invitation deadline for next All Hands (Whistler in June 2019).

**Comment by MichaelKohler** [comment]
Town Halls "Reserve the dates" planning: https://discourse.mozilla.org/t/reserve-the-dates-council-elections-spring-2019-town-halls/36765

**Comment by ioana-chiorean** [comment]
Reps Nominee event created: https://reps.mozilla.org/e/reps-council-elections-h1-2019-nominees/ 
Discourse post created: https://discourse.mozilla.org/t/important-council-elections-h1-2019-please-read/37299
Mail sent to Reps-General Mailing List 
Written and pin message in Telegram

_* corrected **ALL** 2018 to 2019_
_* replaced Spring to H1_

**Comment by MichaelKohler** [comment]
Town Halls:
https://discourse.mozilla.org/t/reps-council-elections-spring-2019-town-hall-1-tuesday-14-00-utc/37683/2
https://discourse.mozilla.org/t/reps-council-elections-spring-2019-town-hall-2-thursday-18-00-utc/37684/2

Comms for candidates + Q&A thread on Discourse is ready to be published, once we get the eligibility finished.

**Comment by MichaelKohler** [comment]
**Nominees:**

1. [Prathamesh Chavan](https://reps.mozilla.org/u/prathamesh/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2019-nominee-q-a/37700/7?u=ioana)
  - [ ] Video (optional)
  - [x] Townhall 1  (preferred, but optional due to timezones/personal life)
  - [x] Townhall 2 (preferred, but optional due to timezones/personal life)

2. [Vishal Chavan](https://reps.mozilla.org/u/vi5halc/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2019-nominee-q-a/37700/6?u=ioana)
  - [ ] Video (optional)
  - [x] Townhall 1  (preferred, but optional due to timezones/personal life)
  - [ ] Townhall 2 (preferred, but optional due to timezones/personal life)

3. [Irvin Chen](https://reps.mozilla.org/u/Irvin/)
  - [x] Answers
  - [ ] Video (optional)
  - [x] Townhall 1  (preferred, but optional due to timezones/personal life)
  - [ ] Townhall 2 (preferred, but optional due to timezones/personal life)

4. [Felipe Do Espirito Santo](https://reps.mozilla.org/u/felipez3r0/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2019-nominee-q-a/37700/2?u=ioana)
  - [ ] Video (optional)
  - [ ] Townhall 1  (preferred, but optional due to timezones/personal life)
  - [x] Townhall 2 (preferred, but optional due to timezones/personal life)

5. [Shahid Ali Farooqui](https://reps.mozilla.org/u/shahidfarooqui/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2019-nominee-q-a/37700/4?u=ioana)
  - [ ] Video (optional)
  - [x] Townhall 1  (preferred, but optional due to timezones/personal life)
  - [x] Townhall 2 (preferred, but optional due to timezones/personal life)

6. [Mayur Patil](https://reps.mozilla.org/u/yomanpatil/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2019-nominee-q-a/37700/5?u=ioana)
  - [ ] Video (optional)
  - [x] Townhall 1  (preferred, but optional due to timezones/personal life)
  - [ ] Townhall 2 (preferred, but optional due to timezones/personal life)

7. [Yuliana R Jimenez](https://reps.mozilla.org/u/Tuxxy/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2019-nominee-q-a/37700/8?u=ioana)
  - [ ] Video (optional)
  - [ ] Townhall 1  (preferred, but optional due to timezones/personal life)
  - [x] Townhall 2 (preferred, but optional due to timezones/personal life)

8. [Luis A Sanchez](https://reps.mozilla.org/u/lasr21/)
  - [x] [Answers](https://discourse.mozilla.org/t/important-council-elections-spring-2019-nominee-q-a/37700/3?u=ioana)
  - [ ] Video (optional)
  - [x] Townhall 1  (preferred, but optional due to timezones/personal life)
  - [x] Townhall 2 (preferred, but optional due to timezones/personal life)

**Comment by ioana-chiorean** [comment]
- Checklist updated
- Voting created https://reps.mozilla.org/v/reps-council-elections-h1-2019-5-spots/
- Q&A discourse post - https://discourse.mozilla.org/t/important-council-elections-spring-2019-nominee-q-a/37700/9

**Comment by MichaelKohler** [comment]
https://michaelkohler.github.io/reps-voting-analysis

**Comment by MichaelKohler** [comment]
* Mail for access to slack/mozillians council group is drafted and ready -> will be sent out soon
* Asked new Council members for GitHub account handles and profile pictures for the leadership page

**Comment by couci** [comment]
E-mail to decide on the time for the onboarding call has been sent.

**Comment by couci** [comment]
Onboarding call will happen on Thursday 16:30 UTC

**Comment by MichaelKohler** [comment]
PR for the leadership page opened here: https://github.com/mozilla/bedrock/pull/7104

**Comment by couci** [comment]
actions that were due for the 23rd done, waiting for new council members to confirm invitations

**Comment by MichaelKohler** [comment]
Sent a list with oi-team Slack channel and OI Team Access Group changes to Henrik

**Comment by couci** [comment]
groups are updated I only have the blogpost pending
