### ISSUE TITLE
OKR 4, non-Mozilla entities identify the Reps program as a connector to the broader Mozilla community

### ISSUE THREAD

**Issue by Mte90** [mozilla/Reps#369]
## Goal: 
https://docs.google.com/document/d/1mitS1b6-v9u-nsubmxsz_qeKLF-sJoFgbmfEMiq2pA0/edit

## Roles:

Responsible: @mte90

Accountable: Peers

Supporting: Peers

Consulted:

Informed: 

## Required: 
- [x] Write proposal about publications (owner, Due: Feb 12th) 
- [x] Write first draft to review (owner, Due: Feb 20th) 
- [x] Send to Hacks blog for approval (owner, Due: Feb 25th)
- [x] Rewritten from scratch for another blog (owner)
- [ ] Review from Alex (owner)
- [ ] Looking for a new blog to publish our article (owner, Due: Mar 26th)

**Comment by ioana-chiorean** [comment]
Any status here?

**Comment by Mte90** [comment]
I am not following anymore and since my las update in may I don't see any updates in the doc (that I have still the access on it).
