### ISSUE TITLE
Publish RoM for February 2019

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#372]
## Goal: 
The RoM for February 2019 is published.

## Roles:

Responsible: @MichaelKohler / @ioana-chiorean
Accountable: @ioana-chiorean 
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@MichaelKohler  Due: March 15th) 
- [x] Review text (@ioana-chiorean , Due March 16th)
- [x] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due:  March 17th)

**Comment by MichaelKohler** [comment]
Telegram and reps-general done.
Discourse: https://discourse.mozilla.org/t/rep-of-the-month-february-2019/36947/2

@couci please close this issue once you have approved the blog post, thx! :)

**Comment by couci** [comment]
done
