### ISSUE TITLE
OKR5 - Existing Reps and new applicants understand the resources we provide

### ISSUE THREAD

**Issue by mermi** [mozilla/Reps#374]
## Goal: 
we have fewer questions by new Reps on understanding the community coordinator role. So we need to make Existing/New Reps ask questions about their role via the resources we provide to them.

## Plan:
[Here is the current plan](https://docs.google.com/document/d/1kXhdh3hVErK8570ZWqtKacSOqNO0VAvBkTb8LQ9NNv8/edit?usp=sharing) 

## Roles:

Responsible: @mermi 

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [x] Prepare presentation and two surveys (@mermi , Due: March 21th) 
- [ ] First communication is to send the Presentation and say that we are waiting for his/her impression (so they can fill the first Survey) (@mermi , Due: March 30th) 
- [ ] Gather result of the first survey and analyze it (@mermi , Due: April 7th)
- [ ] Gather impressions of the presentation and analyze it (@mermi, Due: April 15th)

**Comment by ioana-chiorean** [comment]
Any status here?

**Comment by asdofindia** [comment]
I believe a lot of people (reps and non-reps) aren't aware of this community coordinator role. Has this particular issue been finished? Can it be closed or updated?
