### ISSUE TITLE
Plan to move inactive rep to Alumni (Q2 2019)

### ISSUE THREAD

**Issue by irvin** [mozilla/Reps#375]
Goal: Seasonal moving inactive rep (no report more than 12M) to Alumni

## Related Issues & Links: 
- https://discourse.mozilla.org/t/inactive-reps-to-be-moved-as-alumni/34090/
- #348 
- #362 
- https://reps.mozilla.org/dashboard/stats/
- list of NDA renewal https://docs.google.com/spreadsheets/d/1x5YfxZSINc6pUuJTJSJ3A8EiZwsxYxXGW6850jYCvlQ/edit#gid=1623115867

## Roles:

Responsible: @irvin 
Accountable: 
Supporting:
Consulted: @couci 
Informed: 

## Required: 
- [x] [list of inactive rep](https://docs.google.com/spreadsheets/d/1x5YfxZSINc6pUuJTJSJ3A8EiZwsxYxXGW6850jYCvlQ/edit#gid=2085532218) (Due: , Done: Irvin) 
- [x] send out [notice email](https://docs.google.com/document/d/1zEs5YnHjiurgPgBq5hd7NEuBw8Qth38yZZZnJgQuAvo/edit) (owner: Irvin, Done: Apr 9)
- [x] (4 weeks later) [announce the preliminary list on Discourse](https://discourse.mozilla.org/t/inactive-reps-who-will-be-graduated-to-alumni-after-mid-may/40024) (owner: Irvin, Due: May 2, Done:5/7)
- [x] get final list of inactive rep (owner, Due: 5/17, Done: 7/9)
- [x] move inactive list to Alumni (owner: irvin, Done: 7/9)
- [x] send out alumni certification (owner: Irvin, Done: 7/9)
- [x] remove alumni from Mozillians NDA group (owner: Konstantina Due: )

**Comment by irvin** [comment]
blocked by https://github.com/mozilla/remo/pull/1507 for now

**Comment by irvin** [comment]
This is the preliminary list of Reps who will be graduate after May 16 if no update
https://discourse.mozilla.org/t/inactive-reps-who-will-be-graduated-to-alumni-after-mid-may/40024

**Comment by ioana-chiorean** [comment]
Can this be closed then?

**Comment by irvin** [comment]
No, we haven't move them due to latest Firefox Preview campaign before All Hands. 
I will proceed later this week.

**Comment by irvin** [comment]
Totally moved 25 reps to alumni

**Comment by irvin** [comment]
over to @couci for NDA removal

**Comment by irvin** [comment]
the list is here https://docs.google.com/spreadsheets/d/1x5YfxZSINc6pUuJTJSJ3A8EiZwsxYxXGW6850jYCvlQ/edit?pli=1#gid=2085532218 (sheet 2 line 21-45)

**Comment by irvin** [comment]
Konstantina done removing NDA access. I will close this issue once I create task for Q4.

**Comment by irvin** [comment]
closed with https://github.com/mozilla/Reps/issues/385
