### ISSUE TITLE
Reps Applications Screening Round - Week of April 7th

### ISSUE THREAD

**Issue by mermi** [mozilla/Reps#378]
## Goal: 
All open and ready applications are screened and informed.

## Related Issues & Links: 
[Screening Application](https://docs.google.com/spreadsheets/d/1emlgepTFHDWZ6MLg2xAYdFsAlhPnheun_c3gSQY1Dyk/edit?usp=sharing)
it's a private document as the decision concerns certain people.

## Roles:

Responsible: @Mermi

Accountable:

Supporting:

Consulted:

Informed: 

## Required: 
- [ ] Add applicants to the screening sheet (@mermi, Due: Apr 7th)
- [ ] Reach out to rest of screening group and ask them to screen (@mermi, Due: Apr 7th)
- [ ] Screen applications (@mermi, Due: Apr 8th)
- [ ] Respond back to applicants (@mermi, Due: Apr 17th)
- [ ] Proceed with Webinar for those who got approved (@mermi, Due: Apr 17th)

**Comment by ioana-chiorean** [comment]
Updates here?
