### ISSUE TITLE
Review Team Reshuffle

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/Reps#380]
## Goal: 
Renew volunteer positions in the current Review Team formation.

## Related Issues & Links: 
- https://wiki.mozilla.org/Reps/Review_Team 

## Roles:

Responsible: @kelimuttu @couci 

Accountable: @kelimuttu 

Supporting: Reps Review team

Consulted: Reps Council

Informed: CDT

## Required: 
- [x] List of candidates from the Reps Resources list (@kelimuttu) 
- [x] Send the candidates to The Reps Council 
- [x] Final announcement

**Comment by ioana-chiorean** [comment]
Updates here?

**Comment by kelimuttu** [comment]
The shadowing process just started this week. We will officially announce the new Review Team next week.

**Comment by couci** [comment]
@kelimuttu should we close this one?

**Comment by kelimuttu** [comment]
Yep. This was done.
