### ISSUE TITLE
Publish RoM for April 2019

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#381]
https://reps.mozilla.org/v/rep-of-the-month-for-april-3/

## Goal: 
The RoM for April 2019 is published 

## Roles:

Responsible: @MichaelKohler / @ioana-chiorean
Accountable: @ioana-chiorean 
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@ioana-chiorean  Due: 8th of May 2019) 
- [x] Review text (@MichaelKohler, Due 10th of May 2019)
- [ ] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due:  15th of May 2019)

**Comment by MichaelKohler** [comment]
Portal done, Discourse: https://discourse.mozilla.org/t/rep-of-the-month-april-2019/40229, reps-general and Telegram done.

@couci please approve the blog post

Date-back on the Portal is pending.

**Comment by MichaelKohler** [comment]
Henrik has back-dated the portal entry. @couci please close this issue once the blog post is live. Thanks everyone!

**Comment by couci** [comment]
published https://blog.mozilla.org/mozillareps/2019/05/13/rep-of-the-month-april-2019/

**Comment by ioana-chiorean** [comment]
Thank you everyone!
