### ISSUE TITLE
Add historical program information to Wikipedia

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#382]
## Goal: 
Currently we only list a description of the Program on Wikipedia. We should re-write this text and incorporate

1) Historical context
2) Goals of the program

## Related Issues & Links: 
#379 

## Roles:

Responsible: tbd
Accountable: @MichaelKohler
Supporting: Reps, Tanner

## Required: 
- [ ] Initial draft of text (tbd, Due: June 15th) 
- [ ] Review of text done (tbd, Due: June 25th) 
- [ ] Text is updated on Wikipedia (Tanner, Due: June 30th)

**Comment by MichaelKohler** [comment]
@irvin as you were doing some historical research in the past, would you like to work on this? I'm happy to support.

**Comment by irvin** [comment]
@MichaelKohler I may not have time for writing but the history and reference link are in this post,
https://discourse.mozilla.org/t/how-old-is-mozilla-rep-program-a-brief-timeline/37722

**Comment by ioana-chiorean** [comment]
@MichaelKohler how do u want to proceed here?

**Comment by MichaelKohler** [comment]
That's a very good question. I'd love for somebody to step up here and take the lead, I'll spread it on telegram.

**Comment by Ruwan-Ranganath** [comment]
Hi, 
I've just created a draft base on @irvin discourse post here : https://docs.google.com/document/d/1-YthCR1c2fAlmxVpJa2e-H03lR00LiOs_G6b4pt4U1A/edit#heading=h.6fs2rey2ac9t

we need details about reps program highlights after 2015.and any historical photos of reps program,
maybe such as first video call screen capture if someone have. or first meetup. 
related people photos. 

I'm not sure how larger this document will be , but better fill all the things we can find and they remove irrelevant details. or keep most important parts. 

Thank you.

**Comment by irvin** [comment]
Hi Ruwan,

How do you think if we just add those info to Wikipedia first, so not to be
blocked by lack of newer information?

Irvin


Ruwan Ranganath <notifications@github.com> 於 2019年7月4日 週四 下午3:52寫道：
