### ISSUE TITLE
Publish RoM for June 2019

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#383]
https://reps.mozilla.org/v/rep-of-the-month-for-june-3/

## Goal: 
The RoM for May 2019 is published 

## Roles:

Responsible: @MichaelKohler / @ioana-chiorean
Accountable: @ioana-chiorean 
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@ioana-chiorean  Due: End of June 2019) 
- [x] Review text (@MichaelKohler, Due End of June 2019)
- [x] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due:  End of June 2019)

**Comment by MichaelKohler** [comment]
Discourse, reps-general, Telegram are done.

Reps Portal needs to be backdated.

And @couci needs to publish the blog post. Thanks!

**Comment by couci** [comment]
blogpost added :)

**Comment by MichaelKohler** [comment]
thanks!
