### ISSUE TITLE
Plan to move inactive rep to Alumni (Q1 2020)

### ISSUE THREAD

**Issue by irvin** [mozilla/Reps#385]
Goal: Seasonal moving inactive rep (no report more than 12M) to Alumni, keep list of rep updated and have accurate numbers for resource management.

## Related Issues & Links: 
- #390 , #348, #362 
- https://discourse.mozilla.org/t/inactive-reps-to-be-moved-as-alumni/34090/
- https://discourse.mozilla.org/t/inactive-reps-who-will-be-graduated-to-alumni-next-month/35419/5
- #375, https://discourse.mozilla.org/t/inactive-reps-who-will-be-graduated-to-alumni-after-mid-may/40024
- list of NDA renewal https://docs.google.com/spreadsheets/d/1x5YfxZSINc6pUuJTJSJ3A8EiZwsxYxXGW6850jYCvlQ/edit#gid=1623115867
- Rep numbers - https://reps.mozilla.org/dashboard/stats/

## Roles:

Responsible: @irvin 
Accountable: 
Supporting:
Consulted: @couci 
Informed: 

## Required: 
- [x] [list of inactive rep](https://docs.google.com/spreadsheets/d/1x5YfxZSINc6pUuJTJSJ3A8EiZwsxYxXGW6850jYCvlQ/edit#gid=2085532218) (owner: Irvin, Due: , Done: Jan 9) 
- [x] send out [notice email](https://docs.google.com/document/d/1mnpajQLEqxta5JgYNl6YxiQtvTBFA_J9fvKtMmYX5S4/edit?usp=sharing) (owner: Irvin, Due: Jan 10, Done: Jan 9)
- [ ] (2 weeks later) [announce the preliminary list on Discourse]() (owner: Irvin, Due: Feb 1 , Done:)
- [x] get final list of inactive rep (owner, Due: Feb 1, Done: )
- [x] move inactive list to Alumni (owner: irvin, Done: )
- [x] send out alumni certification (owner: Irvin, Done: )
- [x] remove alumni from Mozillians NDA group (owner: Konstantina Due: )

**Comment by irvin** [comment]
blocked by https://github.com/mozilla/Reps/issues/390

**Comment by irvin** [comment]
31 people is inactive > 12M and still not response on #390 

I will give them a notice, and move to alumni after two weeks (Feb 1)

Here is mail draft - https://docs.google.com/document/d/1mnpajQLEqxta5JgYNl6YxiQtvTBFA_J9fvKtMmYX5S4/edit?usp=sharing

**Comment by irvin** [comment]
We had move 28 reps into Alumni last day (out of 31 reps, 5 reps responded, 2 additional step down), and we have 215 reps now.

**Comment by irvin** [comment]
@couci we will need you to help remove them from NDA, sheet 1 from Line 113 to 140 https://docs.google.com/spreadsheets/d/1x5YfxZSINc6pUuJTJSJ3A8EiZwsxYxXGW6850jYCvlQ/edit?usp=sharing

**Comment by Mte90** [comment]
There is a list of those Reps?
Just to be sure that no one of my mentee is involved (I checked now just for control) .

**Comment by irvin** [comment]
- Edoardo Viola
- Marcia Knous
- Yonggang Zhang
- ARKODYUTI SAHA
- Adriano Cupello
- Guillaume Dauvin
- Asma Islam SWAPNA
- Rezaul Huque Nayeem
- Ziggy Maes
- Tshepo Tamajobe
- Florian Merz
- Mubiru Jonathan
- Ernest Chiang
- Eduardo Enrique Gomez Valencia
- Faye Tandog
- Cynthia Pereira
- Gauthamraj Elango
- Shubham Geete
- Luigui Delyer
- Ednah Kiome
- Rutuja Surve
- Liza Duron
- Lebron Brian Ssekalegga
- Vigneshwer Dhinakaran
- Sumanth Damarla
- Alejandro Gomez
- Viorela Ioia
- Richard Armuelles Zeballos

**Comment by couci** [comment]
all necessary steps are done
