### ISSUE TITLE
 Publish RoM for July 2019 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#386]
https://reps.mozilla.org/v/rep-of-the-month-for-july-4/

## Goal: 
The RoM for July 2019 is published 

## Roles:

Responsible: @MichaelKohler / @ioana-chiorean
Accountable: @ioana-chiorean 
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@ioana-chiorean  Due: 25th of July 2019) 
- [x] Review text (@MichaelKohler, Due 30th of July 2019)
- [x] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due:  5th of Aug 2019)

**Comment by couci** [comment]
@MichaelKohler what is the status here?

**Comment by MichaelKohler** [comment]
As far as I know we haven't gotten any text yet. @ioana-chiorean right?

**Comment by ioana-chiorean** [comment]
We did not/ I 've contacted the mentor via mail and facebook - but no reply.

**Comment by ioana-chiorean** [comment]
Wrote him on Telegram too. If we get no reply I suggest to write something generic related to his activities

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/rep-of-the-month-july-2019/44885
Reps General and Telegram done
Blog post submitted for review, @couci please review and post it. Thanks!

**Comment by couci** [comment]
published https://blog.mozilla.org/mozillareps/2019/09/11/rep-of-the-month-july-2019/
