### ISSUE TITLE
Publish RoM for August 2019

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#396]
https://reps.mozilla.org/v/rep-of-the-month-for-august-4/

## Goal: 
The RoM for August 2019 is published.

## Roles:

Responsible: @MichaelKohler / @ioana-chiorean
Accountable: @ioana-chiorean 
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@Michael Kohler, Due: September 10th) 
- [x] Review text (@ioana-chiorean, Due: September 11th)
- [x] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due:  September 20th)

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/rep-of-the-month-august-2019/45815
reps-general, Telegram and Reps Portal done

@nukeador could you please approve the blog post on the Reps portal as K is out? Thanks!

**Comment by ioana-chiorean** [comment]
Thanks MK!

**Comment by couci** [comment]
published https://blog.mozilla.org/mozillareps/2019/09/30/rep-of-the-month-august-2019/
