### ISSUE TITLE
Publish RoM for September 2019

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#397]
## Goal: 
The RoM for September 2019 is published.

## Roles:

Responsible: @MichaelKohler / @ioana-chiorean
Accountable: @ioana-chiorean 
Supporting: @couci

## Required: 
- [x] Let mentors write a text about RoM (@ioana-chiorean , Due: September 25th) 
- [x] Review text (@MichaelKohler, Due: October 10th)
- [x] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due:  October 15th)

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/rep-of-the-month-september-2019/46955
Telegram and reps-general done as well.

@couci please approve the blog post and then close this issue, thanks!

**Comment by couci** [comment]
done
