### ISSUE TITLE
 Publish RoM for October 2019

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#398]
https://reps.mozilla.org/v/rep-of-the-month-for-october-4/

## Goal: 
The RoM for OCtober 2019 is published 

## Roles:

Responsible: @MichaelKohler / @ioana-chiorean
Accountable: @ioana-chiorean 
Supporting: @couci

## Required: 
- [x] Let Mentor write a text about RoM (@ioana-chiorean  Due: 25th of October 2019) 
- [x] Review text (@MichaelKohler, Due 30th of October 2019)
- [x] Publish blog post, discourse, reps-general and Telegram (@MichaelKohler/@couci, Due:  5th of October 2019)

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla.org/t/rep-of-the-month-october-2019/48003
reps-general, Telegram and Portal (apart from date-back) is done.

@couci please approve the blog post and close this issue, thanks! :)

**Comment by couci** [comment]
published https://blog.mozilla.org/mozillareps/2019/11/04/rep-of-the-month-october-2019/
