### ISSUE TITLE
Alignment proposal implemented

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#4]
## Goal: 
Update and implement [Alignment proposal](https://docs.google.com/document/d/1hCdemwo5-ZQzzRPQe8MREbvzK9J2wBO34wKfzfZA89g/edit#)

## Success:
The proposal is in place and the processes are being used.

## Related Issues & Links: 
[WG] mozilla/participation-org#348

## Roles:
Owner: @MichaelKohler @couci 
Involved: 

## Required: 
- [x] Update Document to reflect decisions (@MichaelKohler, Due: April 21)
- [x] Add relevant communication brainstorming parts from Sunday session (@MichaelKohler, Due: April 25)
- [x] Review before sending to all Participation Team members (@Konstantina, Due: April 26) 
- [ ] Final decision regarding implementation (Participation Team members, Due: April 30)

**Comment by MichaelKohler** [comment]
Updated the issue to reflect the necessary steps we need to take

**Comment by MichaelKohler** [comment]
I've updated the Proposal with our discussions in Berlin: https://docs.google.com/document/d/1hCdemwo5-ZQzzRPQe8MREbvzK9J2wBO34wKfzfZA89g/edit#

The communication piece from the Sunday session is still missing, since I'm relying on getting the pictures of the flipcharts.

I've changed the dates above slightly to reflect the current delay.

**Comment by MichaelKohler** [comment]
I've updated the doc to have everything from Berlin in it including the communication piece. @couci  will look at it on Monday to make sure I haven't forgotten anything and then we are ready to send this for final approval and implementation: https://docs.google.com/document/d/1hCdemwo5-ZQzzRPQe8MREbvzK9J2wBO34wKfzfZA89g/edit

**Comment by MichaelKohler** [comment]
Final vote for Council created: https://reps.mozilla.org/v/alignment-proposal-final-vote/

**Comment by MichaelKohler** [comment]
We still have some missing votes from @bacharakis @shahidfarooqui @Faisalaziz @rosanardila @rara79

**Comment by bacharakis** [comment]
Apologies for not replying earlier!
Great work guys! +1 from me!
-C

On Fri, May 6, 2016 at 7:46 PM, Michael Kohler <notifications@github.com>
wrote:

> We still have some missing votes from @bacharakis
> <https://github.com/bacharakis> @shahidfarooqui
> <https://github.com/shahidfarooqui> @Faisalaziz
> <https://github.com/Faisalaziz> @rosanardila
> <https://github.com/rosanardila> @rara79 <https://github.com/rara79>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/Reps/issues/4#issuecomment-217495152>
>



-- 
Christos Bacharakis
bacharakis.com

**Comment by MichaelKohler** [comment]
This is approved, so let's use the processes defined there!
