### ISSUE TITLE
Activity Campaign

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#40]
## Goal: 
Set up an activity campaign to support a small list of prioritized initiatives delivered by Participation team, and work with coaching efforts to deliver a first iteration quickly through new mentors.

## Roles:

* Responsible: @nukeador
* Accountable: @nukeador
* Supporting: @rosanardila @gapsonTM @brianking 
* Consulted: @bacharakis @deimidis 
* Informed: 

## Required: 
- [x] Get a clear set of initiatives and actions
- [x] Sync with coaching efforts on how to incorporate this
- [ ] Sync with new mentors to have this as part of the on boarding

**Comment by nukeador** [comment]
This depends on the work we are doing at Participation team level defining these initiatives 

https://discourse.mozilla-community.org/t/defining-focus-activities/9474/

**Comment by nukeador** [comment]
We need to do a big push on this campaign for Reps.

Ping @brianking to have this on our radar and coordinate next week

**Comment by nukeador** [comment]
@deimidis Did we incorporated something about this in the coaching sessions?

**Comment by Mte90** [comment]
I think that for the European part we already started with the Makerparty/Changecopyright campaign.
In Italy we already started to create stuff in Italian and get engagement from people but this is not the right ticket to leave updated about this.

**Comment by nukeador** [comment]
Closing this one. We'll do a second phase support in the next weeks.
