### ISSUE TITLE
Council Elections H1 2020

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#400]
## Goal:
Hold the Council elections in order to occupy the spots that are free after the term of one year is ending for:

🎓Shahid
🎓Prathamesh
🎓Mayur
🎓Irvin

We have 4 open spots.

## Success:
The elections take place and we have 4 Council members

## Related Issues & Links:
- Previous Elections #15, #114, #208, #284, #327, #366, #389

## Roles:
Owner: @ioana-chiorean 
Involved: @couci, Reps Peers
Supporting: @nukeador
Informed: Reps

## Required:
(format of the dates is DD.MM.YYYY)

### Planning
- [x] 12.03.2020 - Timeline presentation and announcement in Reps Call / Discourse / Mailing list (@ioana-chiorean)

### Nomination & Campaigning
- [x] 16.03.2020 - Call for Nominees starts (1 week) (@ioana-chiorean)
- [x] 16.03.2020 - Share invitation for candidating on Mailing List (@ioana-chiorean)
- [x] 16.03.2020 - Share invitation for candidating on Telegram/Matrix (@ioana-chiorean)
- [x] 20.03.2020 - Plan AMA on Matrix (@MichaelKohler)
- [x] 22.03.2020 - Call for Nominees closes (@ioana-chiorean)
- [x] 23.03.2020 - CPG check (@ioana-chiorean)
- [x] 23.03.2020 - Q&A starts on Discourse (1 week) (@ioana-chiorean)
- [x] 26.03.2020 - Nominees Q&A in Matrix (whole day) (@MichaelKohler )
- [x] 29.03.2020 - Deadline for answers in Discourse Q&A (@ioana-chiorean)

### Voting
- [x] 30.03.2020 - Voting starts (1 week) (@ioana-chiorean)
- [x] 30.03.2020 - Tweet about voting (@MichaelKohler)
- [x] 06.04.2020 - Voting closes (@ioana-chiorean)
- [x] 07.04.2020 - Voting results published (@ioana-chiorean)
- [x] 07.04.2020 - Voting Analysis is published (@MichaelKohler)
- [x] 07.04.2020 - Wiki Pages are updated (@MichaelKohler)

### Onboarding
- [x] 08.04.2020 - Onboarding begins - Schedule meeting with new Council members (@couci)
- [x] TBD - Call with Nominees & Peers to make sure they understand accountability (@anknite )
- [x] 11.04.2020 - New Council members have write access to GitHub Reps repo (@MichaelKohler)
- [x] 15.04.2020 - New Council members are in the OI Mozillians group (@couci)
- [x] 15.04.2020 - New Council members are in the Council Mozillians group (@couci)
- [x] 15.04.2020 - New Council members are in the Telegram/Matrix group (@couci)
- [x] 15.04.2020 - New Council members are in the reps-council alias (@couci)
- [x] 15.04.2020 - New Council members have access to Slack / #oi-team channel (@couci)
- [x] 29.04.2020 - Onboarding is done and new Council is operational - new Council members have confirmed they all have access to everything (@couci)
- [ ] 29.04.2020 - Old Council members are removed from Telegram/Matrix group (@couci)
- [x] 29.04.2020 - Old Council members are removed from OI Mozillians group (@couci)
- [x] 29.04.2020 - Old Council members are removed from Council Mozillians group (@couci)
- [x] 29.04.2020 - Reps Portal is updated with new Council members in Council group (@couci)
- [ ] 29.04.2020 - Blog announcement for new members + outgoing members is published (@couci)
- [x] 29.04.2020 - Mozilla Leadership Page is updated (@MichaelKohler)

## Updates required:
- [x] Create [16th entry](https://wiki.mozilla.org/ReMo/Council/History)

**Comment by MichaelKohler** [comment]
@ioana-chiorean @couci does this timeline work for you?

**Comment by ioana-chiorean** [comment]
Done:
- Posted for details and visibility in [Friends of the tree. ](https://wiki.mozilla.org/WeeklyUpdates/2020-03-23#Friends_of_Mozilla) 
- Q&A for nominees: https://discourse.mozilla.org/t/important-council-elections-h1-2020-nominee-q-a/56418
- Mail sent to nominees with next steps

Nominees: 

* [Bala Subramaniyan](https://reps.mozilla.org/u/balapandu222/)
* [Bhuvana Meenakshi Koteeswaran](https://reps.mozilla.org/u/bhuvanameenakshi/)
* [Faisal Aziz](https://reps.mozilla.org/u/FaisalAziz/)
* [Manel Rhaiem](https://reps.mozilla.org/u/manel_rhaiem92/)
* [Pranshu Khanna](https://reps.mozilla.org/u/pransh15/)
* [Ram Dayal Vaishnav](https://reps.mozilla.org/u/Ram/)
* [Shina Dhingra](https://reps.mozilla.org/u/shina_dhingra/)
* [Tim Maks van den Broek](https://reps.mozilla.org/u/Mad_Maks/)

**Comment by ioana-chiorean** [comment]
Here is the tracking list: 

* [Bala Subramaniyan](https://reps.mozilla.org/u/balapandu222/)
- [x] Replied to email to confirm
- [x] Answers  
- [ ] Video (optional)
- [ ] Townhall (optional)
* [Bhuvana Meenakshi Koteeswaran](https://reps.mozilla.org/u/bhuvanameenakshi/)
- [x] Replied to email to confirm
- [x] Answers  
- [ ] Video (optional)
- [ ] Townhall (optional)
* [Faisal Aziz](https://reps.mozilla.org/u/FaisalAziz/)
- [ ] Replied to email to confirm
- [x] Answers  
- [ ] Video (optional)
- [ ] Townhall (optional)
* [Manel Rhaiem](https://reps.mozilla.org/u/manel_rhaiem92/)
- [x] Replied to email to confirm
- [x] Answers  
- [ ] Video (optional)
- [ ] Townhall (optional)
* [Pranshu Khanna](https://reps.mozilla.org/u/pransh15/)
- [x] Replied to email to confirm
- [x] Answers  
- [ ] Video (optional)
- [ ] Townhall (optional)
* [Ram Dayal Vaishnav](https://reps.mozilla.org/u/Ram/)
- [x] Replied to email to confirm
- [x] Answers  
- [ ] Video (optional)
- [ ] Townhall (optional)
* [Shina Dhingra](https://reps.mozilla.org/u/shina_dhingra/)
- [x] Replied to email to confirm
- [x] Answers  
- [ ] Video (optional)
- [ ] Townhall (optional)
* [Tim Maks van den Broek](https://reps.mozilla.org/u/Mad_Maks/)
- [ ] Replied to email to confirm
- [x] Answers  
- [ ] Video (optional)
- [ ] Townhall (optional)

**Comment by MichaelKohler** [comment]
I've received the GitHub username and a picture from each of the new members. I will add all new Council members to the repo tomorrow, and I will also create a PR for the leadership page this week.

**Comment by MichaelKohler** [comment]
All new Council members now have write permission on this repo (they need to accept the invite). Additionally I've created the Leadership update PR: https://github.com/mozilla/bedrock/pull/8776

**Comment by MichaelKohler** [comment]
Leadership page is updated: https://www.mozilla.org/en-US/about/leadership/#reps-council

**Comment by Timmaks** [comment]
And the portal?

**Comment by couci** [comment]
Portal also updated (both community and reps portal). Old council members will remain in the matrix channel for giving the new council members advice

**Comment by ioana-chiorean** [comment]
Anything else to be done here?

**Comment by MichaelKohler** [comment]
@couci is there a blog post planned?
