### ISSUE TITLE
Onboarding Screening Team 2020-2 applications

### ISSUE THREAD

**Issue by Timmaks** [mozilla/Reps#408]
## Goal: 
The current onboarding team is all ready 2 years in this configuration
As mentioned on https://wiki.mozilla.org/Reps/Webinar/Screening this should be renewed every 6 months

## Roles:

Responsible: @Timmaks 

Accountable: @Timmaks 

Supporting: current onboarding team

Consulted: 

Informed: 

## Required: 
- [x] Post on Discource and gather applications (@Timmaks , Due: Jun 7th)
- [x] Discuss with Council about the applications (@Timmaks , Due: Jun 9th)
- [x] Published new team members (@Timmaks , Due: Jun 16th)
- [ ] Publish blogpost about previous and new team (@Timmaks , Due: Jun 24th)

**Comment by Timmaks** [comment]
discource post: https://discourse.mozilla.org/t/join-the-onboarding-screening-team-2020-2/60699

**Comment by gaby2300** [comment]
Hello. I am applying again because I love this role! I understand almost every other applicant will be chosen instead of me, but just in case you need one more, I will be available!

**Comment by tanzeelkhan** [comment]
Hi Tim,
I'm available for next 6 months and would love to be a part of this team to help onboard the new reps. :)

**Comment by cseas** [comment]
Hi! I'd love to help with the onboarding of new Reps and am available for the following 6 months.

**Comment by Ruwan-Ranganath** [comment]
Hi Team, 
Will be available for the role next 6 month period and so on. 

Thank you.

**Comment by rtsayles** [comment]
Hi everyone, 
I would love to rejoin and continue to cover the North America region. 

Robby :)

**Comment by abhiaecs** [comment]
Hello,
I'm interested in being a part of this team and I'll be available for the coming 6 months.
Thank you :)

**Comment by daviddagb2** [comment]
Hello, my name is David Gonzalez Blanchard, i am from Nicaragua (Central America), and i am interested in being part of the onboarding team. I am available for the coming 6 months. I want to apply because i undertand that this role is very important for the Reps program and i want to help.

cheers.

**Comment by fernandofedora** [comment]
Hello, I am Fernando Espinoza, I am from Nicaragua, I am available for 6 months, I know that it is a very important role for the community and I would like to support, I am willing to dedicate as much time as necessary for this role

Cheers

**Comment by thehashrocket** [comment]
Hi! I'm Jason Shultz and from the Desert Southwest of the United States. I have availability over the next six months and would appreciate the opportunity to help out with this work.

**Comment by siddhartharao17** [comment]
Hello Team! I'm Siddhartha and I'd love to take on this role and help out from the North America region. I'm currently based in California, US. I'm available for the next 6 months and also have experience with reviewing (conference talk) applications. So, I could use some of the common skills that would be required for onboarding review work in this role.

**Comment by Timmaks** [comment]
Thanks all, the council will review this coming week

**Comment by gaby2300** [comment]
Hello,

Will the Council consider genre diversity among other criteria? If I'm not
mistaken, all applicants are men.

**Comment by Timmaks** [comment]
The new team is there, congrats to the new onboarding team:

David Gonzalez Blanchard (rep)
Tanzeel Khan (rep)
Siddhartha Rao (rep)
Robby Sayles (rep)
Manel Rhaiem (council)
