### ISSUE TITLE
O1KR1:M7: Work with localizers and designers on helping with the guideline marketing side

### ISSUE THREAD

**Issue by shahbaz17** [mozilla/Reps#414]
## Goal: 
Work with localizers and designers on helping with the guideline marketing side

## Related Issues & Links: 
https://github.com/mozilla/Reps/issues/413
https://docs.google.com/document/d/1nweZ_WIFXDULk0VRZqon7dfeS39BKFWey4KjFej5srg/edit#

## Roles:

Responsible: @shahbaz17 

Accountable: @shahbaz17 

Supporting: @shinadhingra18 

Consulted: @couci 

Informed: Council

## Required: 
- [x] Get guideline from [O1KR1:M6](https://github.com/mozilla/Reps/issues/413)
- [x] Write comms to recruit localizers and designers
- [ ] Open “open design” issue to get help from designers, give a deadline
- [x] Identify major locals we want this to be localized at
- [x] Recruit localizers, give a deadline
- [x] Gather work from designers
- [x] Gather work from localizers
- [x] Announce to Reps for the new resources via reps-general and discourse
- [x] Share resources in social media and matrix

**Comment by shinadhingra18** [comment]
Closing this issue as all tasks are completed.

**Comment by shinadhingra18** [comment]
https://discourse.mozilla.org/t/help-localize-the-guide-for-activities-and-campaigns/67083
