### ISSUE TITLE
Decide on Voting Tool for Elections

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#418]
## Goal: 
We have a voting tool for the next Council elections.

## Related Issues & Links: 
#417 

## Roles:

Responsible: @MichaelKohler 
Accountable: Reps Peers
Supporting: Tim, Shahbaz, Luis
Consulted: Reps Peers
Informed: Reps

## Required: 
- [x] Brainstorm voting tools (Sep 10th, Tim, Shahbaz, Luis)
- [ ] Finish analysis (Sep 13th, Michael)
- [ ] Decide on tool (Sep 20th, Reps Peers)
- [ ] Prepare for new tool to be used (Sep 25th, Michael)

**Comment by MichaelKohler** [comment]
From initial brainstorming:

# Matrix Bot

* No good bot found so far
* Unclear if integrity and confidentiality can be kept
* How would we avoid double votes?

# moderator.mozilla.org

* We could use an access group (no new login needed)
* We could use questions as nominees, and then everyone can vote anonymously on them
* However this leaks the current status of the voting to anyone who hasn't voted yet

# Google Form

* Needs a Google account on the email we have for Reps, otherwise we need to gather an account from every single Rep
* At least the creator of the form has access to the data how each individual Rep voted

# Discourse

* Likes on Discourse, same as Mozillian of the Month (no new login needed)
* Same issue as moderator.mozilla.org + votes wouldn't be anonymous
* Not sure how we could potentially lock it down to only Reps
* Alternatively there is also a poll function, but that is not anonymous either

# PollUnit

https://pollunit.com/en/tutorials/range_voting

* Has Range Voting
* Costs, but not much
* Email verification with Business plan, probably needed if we want to ensure only Reps can vote
* With the Premium plan participants and votes can be hidden
* Random option sorting with Premium plan

# Simplevote

https://simplevote.tk/#/
https://github.com/dessalines/simple-vote

* No real ACL?

# BlueOrion

https://blueorion.cc/votehome

* Completely anonymized and transparent voting
* Confirmation that vote was counted, and written to blockchain (maybe one of the few actual nice use cases? :))
* Unfortunately has a public link to see the current results - this gets shown to users after voting, and anyone can open it if somebody knows the link, so might have the same issue as moderator.mozilla.org
* Not even the creator can see who voted for which candidate - or even the fact that person X voted

# HeliosVoting

https://vote.heliosvoting.org

* Used by PyLadies
* Anonymous voting including ballot ID track to make sure it was submitted encrypted
* Allows to randomly sort voting options and we can also add a link for each option
* Bulk import by username, email, name combination - we can use random values for usernames and name.. and the email is used for sending the password
* The email for sending the link, user id and password can be adjusted - but needs to be triggered manually on the website
* Multi step process wizard, we might want to do a video to explain (goes for other options as well..)
* Multiple votes can be submitted until deadline - only last one counts.. Shouldn't be an issue as results are nowhere to be seen.
* Voting verification tools on various levels
* When releasing the results we can email (templated) all voters
* Public doesn't see how people voted or who voted
* Final result page is not public - but everyone can log in with their username/password and see the results - same as it was with the Reps Portal
* Creator can't see single votes, but still can see fact that somebody voted (with the mapping to the bulk import info) (not different from the Reps Portal - even better as it's not all Reps seeing it?) - see point below
* We should probably define > 1 trustee, so we can have the bot, and maybe the Peers all be trustees, and then neither HeliosVoting nor all Peers together can decrypt the results (if we don't include the bot, all Peers might in theory be able to decrypt the votes)

# Honorable mentions

## Existing Reps Portal Voting infra

* Highly coupled to profiles and everything else, can't easily be stripped out

## New tool

* Testing voting tools is a pain and very hard to do in that timeframe
* -> prefer existing tools

**Comment by rzr** [comment]
Should the tool be opensource and/or decentralized ?

**Comment by Mte90** [comment]
I know that other projects use Helios

**Comment by MichaelKohler** [comment]
> Should the tool be opensource and/or decentralized ?

Preferable, but definitely not a hard requirement.

**Comment by gaby2300** [comment]
How did we vote until now? Did we use a tool?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MichaelKohler** [comment]
> How did we vote until now? Did we use a tool?

We've used the voting functionality integrated into the Reps Portal. Now after the move to the Community Portal we need to find something else we can use.

**Comment by gaby2300** [comment]
Sure, thanks for your answer!










<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MichaelKohler** [comment]
We have tested HeliosVoting, here's the summary so far (waiting to hear back from a few people on this):

* Generally we liked it
* It's not super nice design, but it does what it's supposed to do
* Some of the security features make the voting more confidential than it was on the Reps Portal
* We can easily provide a quick "how to vote" tutorial, including information for verification and all the other features at the end for people who do not just want to vote but also to verify their vote was counted
* It doesn't support range voting, but this is not a crucial criteria

**Comment by felipez3r0** [comment]
I have used the HeliosVoting on another occasion and I believe it is a good choice for the elections :smiley:

**Comment by MichaelKohler** [comment]
Thanks everyone for the help! As the test was successful we're gonna go with HeliosVoting for this election. I'll write a tutorial and will publish it on time before the election voting starts.
