### ISSUE TITLE
Update onboarding wiki pages to reflect the changes on Onboarding, reps program and the Portal

### ISSUE THREAD

**Issue by Timmaks** [mozilla/Reps#419]
## Goal: 
All the onboardingpages updated

## Related Issues & Links: 
#416 

## Roles:

Responsible: @Timmaks 

Accountable: @Timmaks 

Supporting: @francesca

Consulted: Reps-council

Informed: 

## Required: 
- [x] https://wiki.mozilla.org/Reps/Webinar/Screening
- [x] https://wiki.mozilla.org/Reps/Application_Process/Selection_Criteria
- [x] https://wiki.mozilla.org/Reps/Webinar
- [x] https://wiki.mozilla.org/Reps/SOPs/Joining
- [x] https://wiki.mozilla.org/Reps/SOPs/Mentoring/Orientation
- [ ] https://wiki.mozilla.org/Reps/SOPs/
- [ ] https://wiki.mozilla.org/Reps/Structure_Governance

**Comment by Timmaks** [comment]
https://wiki.mozilla.org/Reps/Application_Process/Selection_Criteria 
=>
https://docs.google.com/document/d/1UVwFMuedWFBRrkqKuq5_hFdekDsmg8egq7rH1DvqHFE/edit

the google doc need some edits => change to people.mozilla.org

**Comment by Timmaks** [comment]
do we make new pages and let the webinarpages live as the are and make new pages with /teachable/screening or are we replacing the text?

**Comment by Timmaks** [comment]
![Reps+Onboarding+Process+v2](https://user-images.githubusercontent.com/9842548/93712310-5b410080-fb55-11ea-847a-ea939eae6113.png)

https://docs.google.com/document/d/1RIh_cog22X3HF4XDVsljO2Ebkxd_zV3NyKGrIKP3tcY/edit#heading=h.gyx5yihnc7z5

**Comment by MichaelKohler** [comment]
> do we make new pages and let the webinarpages live as the are and make new pages with /teachable/screening or are we replacing the text?

I guess the teachable is a kind of webinar, so that would fit. I'd suggest to replace the text, then we don't need to change links to it.

**Comment by MichaelKohler** [comment]
Also https://wiki.mozilla.org/Reps/SOPs/Joining will need an update (or remove content and just link to the sub pages so we do not need to maintain two versions of the same content).

**Comment by Francescaminelli** [comment]
This page has now been updated: **https://wiki.mozilla.org/Reps/Webinar/2017-04-25**

**Comment by Timmaks** [comment]
the page is renamed to  https://wiki.mozilla.org/Reps/Webinar/Teachable

**Comment by couci** [comment]
should we redirect the /webinar to /webinar/teachable? Or should the /webinar get a banner on top saying that was the old procedure for the new one check the /webinar/teachable?

I am inclining to the second one so we keep the historic data. @Timmaks thoughts?

**Comment by Timmaks** [comment]
i like the idea of a banner.

**Comment by couci** [comment]
updated @Timmaks let me know what you think https://wiki.mozilla.org/Reps/Webinar

**Comment by couci** [comment]
https://wiki.mozilla.org/Reps/Webinar/2017-04-25 was moved back on old structure and banner was added as well as for https://wiki.mozilla.org/Reps/Webinar/2017-04-04

**Comment by MichaelKohler** [comment]
https://wiki.mozilla.org/Reps/Webinar now has a banner that links to https://wiki.mozilla.org/Reps/Webinar/Teachable. However https://wiki.mozilla.org/Reps/Webinar/Teachable redirects to https://wiki.mozilla.org/Reps/Webinar/2017-04-25, which then itself has the note on top. At this point clicking on the teachable link in the note is basically a loop to the same page.

Did https://wiki.mozilla.org/Reps/Webinar/Teachable have the content we want? If so, @couci can you remove the wrong redirect?

Also note that on the following three pages, there is a typo in the yellow note, it should be "Teachable", not "Teachalbe":

* https://wiki.mozilla.org/Reps/Webinar
* https://wiki.mozilla.org/Reps/Webinar/2017-04-25
* https://wiki.mozilla.org/Reps/Webinar/2017-04-04

And since we're on it, I'd suggest the following text for the note:

> This page contains outdated information. This workflow that has been replaced by a Teachable course. If you are interested in the new workflow, read the Teachable page.

**Comment by couci** [comment]
Banners and redirects were fixed. On the teachable page, there is an overlap with the /joining page. I will look into it and make it more clear

**Comment by Timmaks** [comment]
Need to update https://wiki.mozilla.org/Reps/Structure_Governance to reflect the changes in the mentor program

**Comment by Francescaminelli** [comment]
Page updated
