### ISSUE TITLE
Conflict Resolution / Community Playbook

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#42]
## Goal:

[One line goal description] 
## Related Issues & Links:

[Reference meta issues and past issues] #
## Roles:

Responsible:

Accountable:

Supporting:

Consulted:

Informed: 
## Required:
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

![photo171905228960016894](https://cloud.githubusercontent.com/assets/330324/16151689/afc916d8-349e-11e6-885d-60cb1cf6a67c.jpg)

**Comment by Mte90** [comment]
As Italian we translated that playbook to use in our ff club and yeah that part it's missing.

**Comment by lasr21** [comment]
Is there any news on this issue?

**Comment by nukeador** [comment]
We didn't have time to advance here. In any case @deimidis and @emmairwin are working on learning resources, and conflict resolution is something that keeps coming as a need for volunteers.

**Comment by Mte90** [comment]
Two resources by @nukeador shared to the regional coaches about that:
* http://ctb.ku.edu/en/table-of-contents/implement/provide-information-enhance-skills/conflict-resolution/main
* http://ctb.ku.edu/en/table-of-contents/culture/cultural-competence/transform-conflicts/main

Now they are in my reading list and i can try to do a recap with my experience

**Comment by Mte90** [comment]
I write a page about it after the reading of this links with my point of view https://docs.google.com/document/d/1tmkFUP0GX5HK1lcpHUZtcFw0R6QlEkQafA3wfEuAPDA/edit maybe it's not very good or complete but I think that something is missing in that links shared.
The human part and the facts gathering with a "tutorial".

**Comment by couci** [comment]
Is this still ongoing? Please leave a comment or this will be closed in 24h

**Comment by Mte90** [comment]
We can close because there is no interest or priority on that also if a draft of a document exist
