### ISSUE TITLE
Decide future of Reps Planet

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#420]
## Goal: 
We know what to with the the Reps Planet:  http://planet.mozillareps.org/

## Roles:

Responsible: @MichaelKohler 

## Required:
- [x] Write discourse post 
- [x] Wait for feedback in Discourse post
- [x] Remove if not major objections (Website + SOP)

**Comment by MichaelKohler** [comment]
So, it's not only the links to the Reps Portal being broken, the whole process is broken now. This was queried through the Reps Portal. We also do not have the URLs for the blogs anywhere to query, so this is definitely not an easy fix.

Honestly, the best way forward here is probably to tell Reps to get added to the normal Mozilla Planet.

**Comment by Mte90** [comment]
I am wondering if still makes sense.
I was following it (and not able to publish there, I don't remember why).
How many reps still have a blog? Since it is not mandatory anymore to write reports of events and other stuff I think that was unused and maybe not read at all.

**Comment by MichaelKohler** [comment]
> How many reps still have a blog?

The traffic in the first half of the year was quite low. I'd say moving these over to the normal Mozilla Planet (if Reps want to) would make sense. I honestly don't think figuring out a way to fix this is worth the effort.

**Comment by Mte90** [comment]
So if we let to add in the mozilla planet we need to add a way/SOP to remove from there when a rep is alumni.

**Comment by MichaelKohler** [comment]
> So if we let to add in the mozilla planet we need to add a way/SOP to remove from there when a rep is alumni.

No. The Mozilla Planet has rules - including providing a tagged feed: https://wiki.mozilla.org/Planet_Mozilla. If a Mozillian is not a Rep anymore, that doesn't mean that they should be removed from the Mozilla Planet, any Mozillian can be part of that as long as the tagged feed contains Mozilla related posts.

**Comment by MichaelKohler** [comment]
From Juli 2019 to Juli 2020 we had 18 posts on the Planet. 10 of these were from the official Reps blog.

**Comment by Mte90** [comment]
So I think that the needing of that tool is quite useless as today.

**Comment by Timmaks** [comment]
> > How many reps still have a blog?
> 
> The traffic in the first half of the year was quite low. I'd say moving these over to the normal Mozilla Planet (if Reps want to) would make sense. I honestly don't think figuring out a way to fix this is worth the effort.

totally agree

**Comment by MichaelKohler** [comment]
https://discourse.mozilla.org/t/deprecation-of-reps-planet/68703

**Comment by MichaelKohler** [comment]
There was no objection on Discourse, so I marked the SOP as deprecated and updated the Discourse post: https://discourse.mozilla.org/t/deprecation-of-reps-planet/68703/3?u=mkohler. I'll tell tasos that he can shut it down.
