### ISSUE TITLE
Figure out how to handle Alumni

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#421]
## Goal: 
We know how to handle Alumni and update https://wiki.mozilla.org/Reps/Alumni.

## Roles:

Responsible: tbd

Accountable: Reps Council

Supporting: tbd

Consulted: tbd

Informed: tbd

## Required: 
- [ ] tbd

**Comment by MichaelKohler** [comment]
Might be as easy as to create an Alumni group on the Community Portal and move from the Reps Group to that one?

**Comment by Francescaminelli** [comment]
I copied a list of alumni from the archived website, and added those that have been become alumni after the website shutdown. I am not sure about maintaining a community portal group that would be essentially inactive. But let me know if/where you think we should share the list of alumni.

**Comment by Mte90** [comment]
A list of alumni should be reachable somewhere, maybe in the wiki with a link to mozillians/people?

**Comment by MichaelKohler** [comment]
Thanks for the input. We also have a list at https://github.com/mozilla/reps-archive/tree/gh-pages/people/alumni.

I'll take this up after the elections.
