### ISSUE TITLE
Define Future for Rep of the Month

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#422]
## Goal: 
We know what we're gonna do with Rep of the Month in the future.

## Roles:

Responsible: tbd

Accountable: tbd

Supporting: tbd

Consulted: tbd

Informed: tbd

## Required: 
- [ ] tbd

**Comment by ioana-chiorean** [comment]
Can we add this to our table after elections? 
Opening for discussion on discourse? 
Debate in Thursday's call? 
Check other rewards program?
