### ISSUE TITLE
Update Reporting Wiki Pages

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#423]
## Goal: 
Reporting Wiki pages are up to date with the current process: 

https://wiki.mozilla.org/Reps/SOPs/Reports
https://wiki.mozilla.org/Reps/SOPs/Reports/Recruitment

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:

Responsible: Francesca

Accountable: Reps Council

## Required: 
- [x] Pages are updated to reflect new process

**Comment by Francescaminelli** [comment]
Reps report is now updated: https://wiki.mozilla.org/Reps/SOPs/Reports

**Comment by MichaelKohler** [comment]
Thanks @Francescaminelli. I've updated https://wiki.mozilla.org/Reps/SOPs/Reports/Recruitment to include a banner with a link to the general updated Reports SOP. I think we can close this issue then. Thanks for your efforts!

**Comment by Francescaminelli** [comment]
Great, thanks!
