### ISSUE TITLE
decommission https://mozilla.github.io/Reps/newreps/

### ISSUE THREAD

**Issue by Timmaks** [mozilla/Reps#424]
## Goal: 
The page on https://mozilla.github.io/Reps/newreps/ is really outdated. 

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:

Responsible: Tim

Accountable: reps council

**Comment by Timmaks** [comment]
do we remove the page or do we add a banner to show it is not maintained anymore?

**Comment by MichaelKohler** [comment]
Let's add a banner

**Comment by Timmaks** [comment]
https://github.com/mozilla/Reps/pull/425

made something quick, feel free to make it better, cleaner

**Comment by MichaelKohler** [comment]
Thank you!
