### ISSUE TITLE
Reps Council Elections H1 2021

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#426]
## Goal:
Hold the Council elections in order to occupy the spots that are free after the term of one year is ending for:

🎓Shina
🎓Tim
🎓Faisal

We have 3 open spots.

## Success:
The elections take place and we have 3 Council members

## Related Issues & Links:
- Previous Elections #15, #114, #208, #284, #327, #366, #389, #400, #417

## Roles:
Owner: @ioana-chiorean 
Involved: @couci, Reps Peers
Supporting: @
Informed: Reps

## Required:
(format of the dates is DD.MM.YYYY)

### Nominees
- [x] 11.03.2021 - Timeline presentation and announcement in Reps Call / Discourse / Mailing list (@ioana-chiorean)
- [x] 15.03.2021 - Call for Nominees starts (1 week) (@ioana-chiorean)
- [x] 28.03.2021 - Call for Nominees closes (@ioana-chiorean)
- [x] 01.04.2021 - Q&A starts on Discourse (1 week) (@ioana-chiorean) // was previous 29.03
- [x] 07.04.2021 - Deadline for answers in Discourse Q&A (@ioana-chiorean) // was previous 04.04

### Voting
- [x] 08.04.2021 - Voting starts (@ioana-chiorean)
- [x] 15.04.2021 - Voting closes (@ioana-chiorean)
- [x] 16.04.2021 - Voting Analysis is published (@MichaelKohler)
- [x] 17.04.2021 - Wiki Pages are updated (@MichaelKohler)

### Onboarding
- [x] 19.04.2021 - Onboarding begins (@couci)
- [x] 21.04.2021 - New Council members have write access to GitHub Reps repo (@MichaelKohler)
- [x] 21.04.2021 - New Council members are in the reps_leadership p.m.o group (@couci)
- [x] 21.04.2021 - New Council members are in the Matrix channel (@couci)
- [x] 21.04.2021 - New Council members are in the reps-council Google Group to have access for documents (@couci)
- [x] 21.04.2021 - New Council members have access to Slack (@Francescaminelli)
- [x] 10.05.2021 - Onboarding is done and new Council is operational - new council members have confirmed they all have access to everything (@couci)
- [x] 13.05.2021 - Outgoing Council members are removed from Matrix channel (@couci)
- [x] 13.05.2021 - Outgoing Council members are removed from reps_leadership / OI Mozillians group (@couci)
- [x] 13.05.2021 - Outgoing Council members are removed from reps-council Google group (@couci)
- [x] 13.05.2021 - Community Portal is updated with new Council members in Council group (@couci)
- [x] 13.05.2021 - Blog announcement for new members + outgoing members is published (@couci)
- [x] 13.05.2021 - Mozilla Leadership Page is updated (@MichaelKohler)

## Updates required
- [x] Create [18th entry](https://wiki.mozilla.org/ReMo/Council/History)

**Comment by MichaelKohler** [comment]
Timeline adjusted for delay in nomination period due to not enough nominees in the first week

**Comment by ioana-chiorean** [comment]
Q&A posted [here](https://discourse.mozilla.org/t/important-council-elections-h1-2021-nominees-q-a/78059).

**Candidates:**

 @jayeshkattar
- [ ] Q&A 
@Timmaks 
- [ ] Q&A 
 @hossainalikram
- [ ] Q&A 
@rowdymehul
- [ ] Q&A 
@lasr21
- [ ] Q&A

**Comment by MichaelKohler** [comment]
Leadership Page PR: https://github.com/mozilla/bedrock/pull/10190

**Comment by ioana-chiorean** [comment]
@couci can we close this one? 
Results: https://discourse.mozilla.org/t/important-council-elections-h1-2021-results-and-next-steps/78734

**Comment by couci** [comment]
All done except the blogpost. I have postponed it since I want to also write about the 10y of the program

**Comment by ioana-chiorean** [comment]
Oke.

**Comment by couci** [comment]
all items have been now completed

**Comment by ioana-chiorean** [comment]
Cool! Thanks for the update!
