### ISSUE TITLE
Publish Reps of the Month for May and June

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#44]
## Goal: 
Organized the voting for May ( needs manual input ) and publish the resutls for both may and June to keep this on track 

## Roles:

Responsible: @ioana-chiorean
Accountable: @ioana-chiorean
Supporting: @MichaelKohler, @akatsoulas (to set the date back on the portal)

## Required: 
- [x] Create [manual voting](https://reps.mozilla.org/v/rep-of-the-month-for-may-1/) for May 2016 on Portal ( @ioana-chiorean, Due: June 22th)
- [x] Create reasons pad for June 2016 for easier understanding of the work of the rep  ( @ioana-chiorean, Due: June 22th)
- [x] Publish RoM for May 2016 on Portal/Blog (@MichaelKohler / @ioana-chiorean, Due: June 28th) 
- [ ] Publish RoM for June 2016 on Portal/Blog (@MichaelKohler / @ioana-chiorean, Due: July 5th)

**Comment by MichaelKohler** [comment]
Can we have sub-tasks for the creation of the text itself? I'm not that good of a writer, but I can definitely publish them (and help out) :)

**Comment by elioqoshi** [comment]
I can help out here if needed

**Comment by MichaelKohler** [comment]
Since both RoM already know about it, I can share the etherpad here: https://public.etherpad-mozilla.org/p/rom-may-june-2016-drafts

**Comment by MichaelKohler** [comment]
@elioqoshi the general structure is
* Intro text
* Picture
* Things this Rep has done in the past months

**Comment by MichaelKohler** [comment]
@elioqoshi maybe you could help me to phrase correctly and maybe add a few more sentences for both? Also we need to find a picture for both :)

**Comment by ioana-chiorean** [comment]
@MichaelKohler I've added some more text and we have the pictures too - pls review them.

**Comment by MichaelKohler** [comment]
@ioana-chiorean thanks a lot! r+

I will start to publish this tonight.

**Comment by MichaelKohler** [comment]
Portal for May is done, Discourse as well (thanks Ioana): https://discourse.mozilla-community.org/t/rep-of-the-month-may-2016/9749

Blog post for May is submitted for review, @nukeador could you please approve it?

**Comment by ioana-chiorean** [comment]
👏🎉🙌🍾 
Should we post the second one in a week or on 25th?

**Comment by MichaelKohler** [comment]
Let's do it in a week so we can always publish at the middle of the next month.

BTW, Portal and blog post is live (with correct dates)

**Comment by ioana-chiorean** [comment]
Can we do it Thursday before the call - so we can announce them in the Reps Call?

**Comment by MichaelKohler** [comment]
Yes, that sounds good to me!

**Comment by ioana-chiorean** [comment]
Secodn discourse here - https://discourse.mozilla-community.org/t/rep-of-the-month-june-2016/9845

**Comment by MichaelKohler** [comment]
Portal for June is done. Also the blog post is in review with @nukeador now.

Discourse (thanks Ioana): https://discourse.mozilla-community.org/t/rep-of-the-month-june-2016/9845
