### ISSUE TITLE
Discourse Category are closed

### ISSUE THREAD

**Issue by couci** [mozilla/Reps#440]
## Goal: 
Discourse categories are closed and no longer used

## Required: 
- [x] Add on the announcement that Reps is no longer an active program (owner @couci @plwt ) 
- [x] Add banner on the subcategories that the program is no longer working (owner @couci )

**Comment by plwt** [comment]
I am not sure I have the access to do this.  All I think that needs to happen is to have this thread pinned - https://discourse.mozilla.org/t/important-announcement-decommissioning-of-the-mozilla-reps-program/122291/

**Comment by couci** [comment]
pinned category and change the post rights to only admin
