### ISSUE TITLE
Put note on matrix groups about Reps decomission

### ISSUE THREAD

**Issue by couci** [mozilla/Reps#446]
## Goal: 
Add a note on all matrix groups that the reps program is decomissioned

## Required: 
- [x] #449
- [x] Add note on reps review (owner @couci ) 
- [x] Add note on reps group (owner @plwt )
- [x] Add note on council group (owner @plwt )
- [x] Add note on reps announcement (owner @couci )

**Comment by Timmaks** [comment]
I all ready did for the mentor, reps and announce group: The Reps program is retired at 01-09-2023, see https://discourse.mozilla.org/t/important-announcement-decommissioning-of-the-mozilla-reps-program/122291 for more info

**Comment by Timmaks** [comment]
Did not meant to open a new issue, I am on mobile and did something wrong...

**Comment by plwt** [comment]
Council room updated.

**Comment by couci** [comment]
Thanks everyone
