### ISSUE TITLE
Reps Weekly Call - Analyze Notes posting engagement

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#47]
## Goal:
- Asses if the notes time invested is worthy 
## Roles:

Responsible: @ioana-chiorean
Accountable: @ioana-chiorean
Supporting: @couci 
Consulted: @MichaelKohler 
Informed: @couci , @nukeador , @ all Reps 
## Required:
- [ ] Check on Discourse the rate of views in the thread
- [ ] Check on Discourse the rate of links opened from the notes
- [ ] Make a nice graph

**Comment by couci** [comment]
@ioana-chiorean Is this still ongoing? Please leave a comment or this will be closed in 24h

**Comment by ioana-chiorean** [comment]
Give me one more week

**Comment by ioana-chiorean** [comment]
Status:
- will discourse about it with some data as backup
- decision already made and included in the tasks

**Comment by MichaelKohler** [comment]
I'm closing this as we're not posting the notes separately anymore.
