### ISSUE TITLE
Gather insights about the Reps Weekly Call

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#48]
## Goal:
- analyze the attendee growth and engagement for the Reps Call 
## Description

We would like to see the progress of the engagement of reps in the weekly call in the last 4 months 
- No of attendees in the call/pad
- No of watchers on airmo
- No of views of discourse topic
- No of views on links in discourse 
## Roles:

Responsible: @ioana-chiorean
Accountable: @couci
Supporting: @
Consulted: @MichaelKohler 
Informed:  Reps, Participation Team,
## Timeline
- [ ] Gather data from ethepads, wikis, discourse (@ioana-chiorean, [large], Due: )
  *\* Data will be recorded [here](https://docs.google.com/spreadsheets/d/1lR6XqEbjFRY7GP5Lt6EMtL60WvkzFd4iqC-mEslgqHo/edit?usp=sharing)
- [ ] Build up a nice display - charts, pies etc (@ioana-chiorean, [medium],  Due: )
- [ ] Share the learnings in the council call(@ioana-chiorean, [small],  )
- [ ] Share the learnings in the reps call (@ioana-chiorean, [small],  )
- [ ] Open discourse/blog for feedback (@ioana-chiorean, [medium],  )

**Comment by couci** [comment]
@ioana-chiorean Is this still ongoing? Please leave a comment or this will be closed in 24h

**Comment by ioana-chiorean** [comment]
i did started a spreadsheet long ago but it is a very manual work not sure hoe to improve progress. Give me one more week

**Comment by MichaelKohler** [comment]
Survey has been done in #352. I'm closing this.
