### ISSUE TITLE
Gather insights about the ROM

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#55]
## Goal:
- improve the participation of engaged people in the ROM process 
## Related Issues & Links:
- none
## Roles:

Responsible: @ioana-chiorean
Accountable: Council
Supporting: 
Consulted: Mentors, Reps
Informed: Reps
## Required:
- [x] Update wiki to reflect the process (@ioana-chiorean, Due: July 24th) 
- [ ] Mail mentors with a reminder about the process (@ioana-chiorean, Due: July 31st) 
- [x] Mail Reps with the form for their input (@ioana-chiorean, Due: July 20th)
- [x] Mail Mentors with the form for their input (@ioana-chiorean, Due: July 20th)
- [x] Present this to the Reps Call (@ioana-chiorean, Due: July 21st)
- [ ] Make publicly the results  (@ioana-chiorean, Due: Aug 7th)

**Comment by nukeador** [comment]
@ioana-chiorean we have been using P1 for the things Council wanted to focus during the next month. How important is this? ;-)

**Comment by ioana-chiorean** [comment]
Extremely important for me but maybe a Pinfinite for council. 
Sorry - i did not remember we had a legend  for the tags  as for council.- Thanks!

**Comment by MichaelKohler** [comment]
@ioana-chiorean do you need any help with this? if so, what exactly?

**Comment by ioana-chiorean** [comment]
I am ok - I am gathering opinions now ( the surveys were send out  around 2 weeks now). 
I will close the surveys next week and analyses the results.

**Comment by MichaelKohler** [comment]
@ioana-chiorean is still still in progress? What are the next steps?

**Comment by MichaelKohler** [comment]
@ioana-chiorean Given the discussion here and in the Discourse thread, the main topic here is to open it up for everyone (to nominate and vote). Do we want to do an experiment out of that? The code changes should be fairly straightforward to open this up to anyone.

**Comment by ioana-chiorean** [comment]
I want to ask first if there are any concerns from our side here and if the implementation means anything we might miss here. I will ask in mentors/council groups at first.

@akatsoulas will this be ok from dev side? To open nominations for all Reps?

**Comment by akatsoulas** [comment]
@ioana-chiorean yes, it should be super easy.

**Comment by MichaelKohler** [comment]
@ioana-chiorean I don't think we have identified any blockers are? Do we want to continue with this?

The participation of votings has improved in the last few months, which is good. But I think we can go further than just mentors :)

**Comment by MichaelKohler** [comment]
@ioana-chiorean any recent thoughts on this? I think I could do a possible PR for the Portal if we want to go down that road. Just would need to have a clear spec.

**Comment by ioana-chiorean** [comment]
I would open it up for everyone to nominate.

@akatsoulas  how should I proceed?

**Comment by Mte90** [comment]
any updates for this?

**Comment by couci** [comment]
@ioana-chiorean Is this still ongoing? Please leave a comment or this will be closed in 24h

**Comment by ioana-chiorean** [comment]
I was waiting for @akatsoulas replied. 
Give me one more week.

**Comment by akatsoulas** [comment]
Sorry I completely missed this. If you have already decided on this, we can proceed with the changes in the portal asap. To be clear, all we need to do is open the nomination process and the voting to all the Reps and not just the mentors, right?

**Comment by MichaelKohler** [comment]
If this doesn't need to be done by tomorrow, I'm happy to work on this. @ioana-chiorean can you create a bugzilla ticket for it?

**Comment by Mte90** [comment]
there is a ticket about add a rom motivation field for nomination that is blocking this ticket, maybe we can change the priority on that.

**Comment by ioana-chiorean** [comment]
Documentation for why and how: https://discourse.mozilla.org/t/rep-of-the-month-rom-process-updates-and-opinions/9860?u=ioana

**Comment by Timmaks** [comment]
is this issue still active/relevant

**Comment by MichaelKohler** [comment]
Closing this in favor of #422
