### ISSUE TITLE
Publish Council Meeting Notes 20/07/2016

### ISSUE THREAD

**Issue by rara79** [mozilla/Reps#57]
## Goal: 
The 20/07/16 Council meeting notes are published.

## Roles:
Responsible: @rara79
Accountable: Reps Council
Supporting: Reps Council for Review

## Required: 
- [x] Draft notes (@rara79, Due: July 28th) 
- [x] Open up for review (@rara79, Due: July 28th) 
- [x] Publish it on Discourse/Wiki (@rara79, Due: July 30th)

**Comment by MichaelKohler** [comment]
@rara79 do you need any help here? If so, for which parts exactly?

**Comment by rara79** [comment]
Done, and published: https://discourse.mozilla-community.org/t/reps-council-meeting-notes-20-07-2016/10297
