### ISSUE TITLE
Publish Council Meeting Notes 27/07/2016

### ISSUE THREAD

**Issue by rara79** [mozilla/Reps#58]
## Goal: 
The 27/07/16 Council meeting notes are published.

## Roles:
Responsible: @rara79
Accountable: Reps Council
Supporting: Reps Council for Review

## Required: 
- [ ] Draft notes (@rara79, Due: Aug 1st) 
- [ ] Open up for review (@rara79, Due: Aug 1st) 
- [ ] Publish it on Discourse/Wiki (@rara79, Due: Aug 2nd)

**Comment by MichaelKohler** [comment]
@rara79 do you need any help here? If so, for which parts exactly?

**Comment by rara79** [comment]
Thank you for your concern, @MichaelKohler :) 
I'm working on these right now. Apologize for being super late :|

**Comment by rara79** [comment]
Done and published: https://discourse.mozilla-community.org/t/reps-council-meeting-notes-27-07-2016/10298/1
