### ISSUE TITLE
Provide training around GitHub issues to Council/Peers

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#6]
## Goal: 
Provide training around GitHub issues to Council/Peers

## Success:
All Council and Peers are able to use github issues without problems

## Roles:
Owner: @nukeador
Involved: 

## Required: 
- [x] Email council/peers about this repo and ask them if they need support (April 17)
- [ ] Gather all questions about using issues (May 1st)
- [ ] Deliver material/training to cover these questions (May 5th)

**Comment by nukeador** [comment]
Waiting for feedback if this is really needed.

**Comment by MichaelKohler** [comment]
Doesn't seem to be needed, therefore closing it. Feel free to reach out to Nuke or me if you need any help :)
