### ISSUE TITLE
Publish Council Meeting Notes 03/08/2016 - 07/09/2016

### ISSUE THREAD

**Issue by rara79** [mozilla/Reps#60]
## Goal: 
The 03/08/16 - 07/09/2016 Council meeting notes are published.

## Roles:
Responsible: @rara79
Accountable: Reps Council
Supporting: Reps Council for Review

## Required: 
- [ ] Draft notes (@rara79 / @MichaelKohler, Due: Sep 10th) 
- [ ] Review (@Nukeador, Due: Sep 12th) 
- [ ] Publish it on Discourse/Wiki (@rara79, Due: Sep 13th)

**Comment by MichaelKohler** [comment]
I've updated the title and description to reflect the new reality.

**Comment by rara79** [comment]
August 3rd and 10th is up on Discourse.

http://discourse.mozilla-community.org/t/reps-council-meeting-notes-03-08-2016/10872/1
http://discourse.mozilla-community.org/t/reps-council-meeting-notes-10-08-2016/10873/1

**Comment by MichaelKohler** [comment]
https://discourse.mozilla-community.org/t/reps-council-meeting-notes-17-08-2016/10878/1
https://discourse.mozilla-community.org/t/reps-council-meeting-notes-24-08-2016/10992
https://discourse.mozilla-community.org/t/reps-council-meeting-notes-31-08-2016/10993
https://discourse.mozilla-community.org/t/reps-council-meeting-notes-07-09-2016/10994/1

The meeting of last week we did not have. so the next one will be from today's meeting. @rara79 could you please open a new issue for today?
