### ISSUE TITLE
Publish Reps Q3 OKRs

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#62]
## Goal: 
We have published our Q3 OKRs on the blog and on Discourse/reps-general as well as a link to it on Telegram to inform all Reps about the current objectives.

## Related links
OKR document: https://docs.google.com/document/d/1UXkjVPyvzdjIdJ3VuMMXAABAhqklKwGCQVDnLI6vAOE/edit?usp=sharing

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @hmitsch 

## Required: 
- [x] Write some lines to 'why' to not only have dry OKRs (@MichaelKohler, Due: Aug 22nd) 
- [ ] Review the text (@hmitsch, Due: Aug 25th) 
- [ ] Publish text on blog / Discourse / reps-general (@MichaelKohler, Due: Aug 26th)

**Comment by MichaelKohler** [comment]
Wrote a small text in the same document: https://docs.google.com/document/d/1UXkjVPyvzdjIdJ3VuMMXAABAhqklKwGCQVDnLI6vAOE/edit#

@hmitsch could you please review this within the next 3 days since you're always doing such a great job? :)

**Comment by hmitsch** [comment]
Hi @MichaelKohler,

are you asking for:
- only review of the first paragraph (introduction) 
- review the whole document, including Objectives & Key Results

Additionally, I just requested editing access to the document. ;-)

**Comment by MichaelKohler** [comment]
Hi Henrik, sorry I always forget that you're Google Doc email is not the one you use for the alias. You should have permission now. 

It would be great if you could review everything apart from the tables (intro and the outro). If you see something in the table that is not clear at all please raise it as well, but the content itself is voted.

Thanks!

**Comment by hmitsch** [comment]
@MichaelKohler: I am done with the review. Please have a look and accept/decline at your discretion.

**Comment by MichaelKohler** [comment]
Thanks a lot @hmitsch ! I've accepted your suggestions, great as always! I also responded to your comments. This is taking great shape.

**Comment by MichaelKohler** [comment]
I've posted it on Discourse: https://discourse.mozilla-community.org/t/reps-program-goals-q3-2016/10520

.. and submitted it for review on the blog. @nukeador, @brianking, @couci please publish it once you get time to do it :)

**Comment by hmitsch** [comment]
Another important piece of work done. Congrats, @michaelkohler!

-- 
Henrik Mitsch

**Comment by couci** [comment]
published :)

**Comment by MichaelKohler** [comment]
Perfect, thanks a lot!
