### ISSUE TITLE
Mid-term planning communication

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#66]
## Goal: 
The mid-term planning status is communicated to all Reps to make sure that we're all on the same level of knowledge. All communities currently working on a mid-term planning or planning to do so are informed about our intentions. 

## Related Issues & Links: 
Mid-term planning Indonesia: #5 

## Roles:

Responsible: @rosanardila @nukeador 
Accountable: Reps Council
Supporting: Reps Council
Consulted: Indonesia community
Informed: 

## Required: 
- [x] Gather general points that are not specific to Indonesia community (@nukeador, Due: Sep 5th) 
- [x] Communicate those points to all Reps (@nukeador (@MichaelKohler as backup if needed), Due: Sep 10th)

**Comment by nukeador** [comment]
Done https://discourse.mozilla-community.org/t/clarification-on-midterm-plans-reps-and-communities/10635
