### ISSUE TITLE
List of Applicants to have as new coachees

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#67]
## Goal: 
We have a list of about 20 new applicants we can use as coachees for our new coaches.

## Related Issues & Links: 
#10 

## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @deimidis 

## Required: 
- [x] Come up with a list of potential coachees (@MichaelKohler, Due: Aug 28th) 
- [x] Send list to Council for final review and concerns (@MichaelKohler, Due: Aug 29th) 
- [x] Review list and sign off (Reps Council, Due: Sep 1st)

**Comment by nukeador** [comment]
@MichaelKohler Status update? ;-)

**Comment by MichaelKohler** [comment]
Working on it. I've started a list here: https://docs.google.com/spreadsheets/d/1wA4NONRzOgBh5EwtEBOGUdHca7abJUJNm3Yc4XIu-YU/edit (only shared to Council and Peers due to my personal ranking inside it)

This might be too "down to the point", but I think it is what we currently need since we have that many applicants.

**Comment by MichaelKohler** [comment]
Sent my recommendation to the Council and Guillermo for a final look. After that we can go ahead and assign them to the new coaches.

**Comment by MichaelKohler** [comment]
I've sent the list to the Coaches group as well for a quick look on it. So far there is no concern on the Council side, so we will be able to move ahead within the next days.

**Comment by MichaelKohler** [comment]
There are no concerns, we can move ahead with assignment once the onboarding is fully done. For that we can open a new issue since that is further than the scope of this one.
