### ISSUE TITLE
Publish RoM for August

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#69]
## Goal: 
RoM of August is published on the portal, blog and discourse.

## Roles:
Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @ioana-chiorean 

## Required: 
- [x] Draft text (@MichaelKohler/@ioana-chiorean, Due: Sep 7th) 
- [x] Review text (??, Due: Sep 9th) 
- [x] Publish on portal, blog, Discourse and reps-general (@MichaelKohler, Due: Sep 12th)

**Comment by ioana-chiorean** [comment]
https://reps.mozilla.org/v/rep-of-the-month-for-august-1/ - I am gonna ping his mentor.

**Comment by MichaelKohler** [comment]
Discourse: https://discourse.mozilla-community.org/t/rep-of-the-month-august-2016/10703 (thanks Ioana)

Portal is added as well. The blog post is in review.

**Comment by MichaelKohler** [comment]
Blog post: https://blog.mozilla.org/mozillareps/2016/09/06/rep-of-the-month-august-2016/

Also a lot of thanks to Priyanka who wrote most of the text :)
