### ISSUE TITLE
Onboard New Council Members

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#71]
## Goal: 
The new selected council members are onboarded and they start working as a team

## Related Issues & Links: 
✔️ #15 
🔛 [Process details here](https://wiki.mozilla.org/ReMo/SOPs/Council_onboarding).

## Roles:
Responsible: @nukeador
Accountable: @ioana-chiorean @nukeador
Supporting: Peers Council
Consulted: Council 
Informed: Council, Peers & Participation team

## Required: 
- [x] Send mail to check availability for new members (@nukeador)
- [x] Hold the video call (@nukeador)
- [x] Assign the buddy council (@nukeador, Due: Aug 7th)
- [x] New council added to mailing list and alias (@nukeador)
- [x] Admin gives permissions on the portal to new and revoke to old ones. (@nukeador)
- [x] At the end of this week former Council is removed from alias and list. (@nukeador)
- [x] Chair emails former Council announcing their duties are over as Council members.
- [x] Chair emails new members and reps-general announcing the new ones start their duties.

**Comment by nukeador** [comment]
Meeting happening tomorrow.

**Comment by nukeador** [comment]
This is now completed.
