### ISSUE TITLE
Publish RoM for September

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/Reps#72]
## Goal: 
RoM of September is published on the portal, blog and discourse.

## Related Issues & Links: 
- [Link for voting](https://reps.mozilla.org/v/rep-of-the-month-for-september-1/). 

## Roles:
Responsible: @ioana-chiorean
Accountable: Reps Council
Supporting: @MichaelKohler
Consulted: - 
Informed: All Reps

## Required: 
- [x] Draft text (@ioana-chiorean, Due: Sept 30th)
- [x] Review text (@MichaelKohler, Due: Sept 30th)
- [x] Publish on portal, blog, Discourse and reps-general (@ioana-chiorean, @MichaelKohler, Due: Sept 30th)

**Comment by MichaelKohler** [comment]
Started the etherpad and reached out to the mentor to help us draft the text.

**Comment by MichaelKohler** [comment]
Added some of their mentor's parts to the etherpad and added a few more information to it. @ioana-chiorean could you please review?

**Comment by ioana-chiorean** [comment]
Review Done ✅

**Comment by MichaelKohler** [comment]
- Added on the Portal and asked tasos to date it back to September
- Discourse post: https://discourse.mozilla-community.org/t/rep-of-the-month-september-2016/11581
- Mail to reps-general sent with link to the Discourse topic
- Blog post submitted for review, @nukeador @couci @brianking could one of you approve it please?

**Comment by MichaelKohler** [comment]
Thanks to @ioana-chiorean for the review and several additions to the text btw :)

**Comment by couci** [comment]
blogpost done :)

**Comment by MichaelKohler** [comment]
Thanks! I'll leave this open until I have the confirmation that the portal entry has been backdated.

**Comment by ioana-chiorean** [comment]
Thank you @MichaelKohler for driving this!

**Comment by MichaelKohler** [comment]
This is done now, great work everyone!
