### ISSUE TITLE
Blog post about the future of the program

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#74]
## Goal:

Have a blog post about the vision for the future of the program
## Roles:

Responsible: @nukeador
Accountable: @nukeador
Supporting:
Consulted: Reps Council
Informed: 
## Required:
- [ ] Create draft
- [ ] Circulate with Council and Peers
- [ ] Publish blog post

**Comment by MichaelKohler** [comment]
related issue #20 for context

@nukeador could you please explain what exactly this blog post would include? Would that be the follow up to https://blog.mozilla.org/mozillareps/2016/08/11/repsnext-improvements-overview/ ? If so, let's create a list of questions to answers together.

**Comment by Mte90** [comment]
For the #20 during the european gathering I talked about that ticket.
I think that we can promote the fact that we have a github repo and also the discussion is opened to everyone. 
During the gathering itself many reps doesn't know the repsnext initiative itself but I think that we can talk about the proposal in pending state.

**Comment by hmitsch** [comment]
@michaelkohler, what about doing as @nukeador proposed: he will draft something and circulate it with Council and Peers?

**Comment by MichaelKohler** [comment]
Would this covered for now by

1) releasing a new communication about the current RepsNext status
2) communicating the Comm Dev team strategy and our part in it in 2017

@nukeador ^

**Comment by nukeador** [comment]
@couci can guide you here since she's owning comms.

**Comment by couci** [comment]
I think for the comm dev part we need to wait first @LucyeoH communicated the strategy so we can refer on their part. Everything else seems good to me

**Comment by MichaelKohler** [comment]
I agree, I will open a new issue once we know what and how we communicate this.

The Reps status is covered in #106, therefore I'm closing this for now.
