### ISSUE TITLE
Publish Council Meeting Notes 21/09/2016 and 27/09/2016

### ISSUE THREAD

**Issue by rara79** [mozilla/Reps#76]
## Goal: 
21/09/2016 and 27/09/2016 Council meeting notes are published.

## Roles:
Responsible: @rara79
Accountable: Reps Council
Supporting: Reps Council for Review

## Required: 
- [ ] Draft notes (@rara79, Due: Oct 6th) 
- [ ] Review (Reps Council, Due: Oct 7th) 
- [ ] Publish it on Discourse/Wiki (@rara79, Due: Oct 8th)

**Comment by MichaelKohler** [comment]
@rara79 do you need any help here?

**Comment by rara79** [comment]
Currently in progress, editing this issue according the current situation.

**Comment by rara79** [comment]
Reps Council meeting notes 21/09/2016: http://discourse.mozilla-community.org/t/reps-council-meeting-notes-21-09-2016/

**Comment by rara79** [comment]
Reps Council meeting notes 28/09/2016: http://discourse.mozilla-community.org/t/reps-council-meeting-notes-28-09-2016/11703

**Comment by rara79** [comment]
All the meeting notes are up until the end of September. Thank you for your patience :)
