### ISSUE TITLE
Update pending Reps applications

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#77]
## Goal:

All Reps applications are updated and applicants know about their current status.
## Related Issues & Links:
#10
## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: @deimidis 
## Required:
- [x] Update all selected applicants' bugs (whiteboard) (@MichaelKohler, Due: Sep 22nd) 
- [ ] Link Guillermo's blog post (to be written) in the still open application bugs and inform people about their status (@deimidis / @MichaelKohler, Due: Sep 30th)

**Comment by MichaelKohler** [comment]
All selected applicants' bugs are up to date now (status, assignee and whiteboard tag).

**Comment by deimidis** [comment]
Hi @MichaelKohler what is the blog post that should be linked here?

**Comment by MichaelKohler** [comment]
@nukeador mentioned something like that in yesterday's meeting. Or did I misunderstood you, Ruben?

**Comment by deimidis** [comment]
ok, that blog post. Yes I know about it :)

**Comment by MichaelKohler** [comment]
@deimidis any update on this?

**Comment by MichaelKohler** [comment]
Here's Guillermo's blog post: http://unojoenelcielo.com.ar/remo/2016/10/21/new-reps-mentors-a-history-and-roadmap/

My suggestion would be to link to this blog post in all open applications and be clear that we are most probably talking about several months of waiting time for new Rep applications. This is bad since some of them are already open for several months, but IMHO the only thing we can do right now since Round 2 of the onboarding will be existing mentors. I do not think that existing mentors will have the capability to take on new Reps as coachees.

@nukeador do you have initial thoughts on this?

**Comment by nukeador** [comment]
Agree, but let's link better here:

https://discourse.mozilla-community.org/t/new-reps-mentors-a-history-and-roadmap/11616/1

So people can provide feedback we can follow.

Thanks!

**Comment by MichaelKohler** [comment]
@couci  and I will screen the currently open applications for references so we can prepare it to be shared more broadly to move this forward. One idea is to have this voted on by Reps Council and Reps Regional Coaches/Mentors.

**Comment by MichaelKohler** [comment]
All pending applications have been tagged with either "Pending references" or "ONHOLD" as well as the two-letter country code.

**Comment by MichaelKohler** [comment]
Further, we will screen the 33 applications that are ONHOLD to move forward here. This will likely happen in the next two weeks.

**Comment by MichaelKohler** [comment]
I will create a spreadsheet for Council review tomorrow. A group of us (Alex, Faisal, Brian and me) will evaluate all pending applications so we can move forward. I will update this issue with further information once we did that.

**Comment by MichaelKohler** [comment]
Further I have closed all applications with missing references/vouches that were older than one month. The spreadsheet is created and open for evaluation.

**Comment by MichaelKohler** [comment]
Quick update since we linked to this for several open applications: we're still screening all applications, we will update all bugs with the latest update by the end of the weekend.

**Comment by MichaelKohler** [comment]
Screening is done, final review is ongoing in Council.

**Comment by MichaelKohler** [comment]
Last steps:
* Adriano will review the Brazil applicants
* We will send out an update for all applicants after that

**Comment by MichaelKohler** [comment]
All applications have been updated with the decision.
