### ISSUE TITLE
Leadership track proposal draft

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#8]
## Goal:

Get a proposal for the leadership track moving forward
## Success:

A proposal is delivered
## Roles:

Owner: @rara79 
Involved: @nukeador @emmairwin
## Required:
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by emmairwin** [comment]
Can you explain what the track is, and how it relates to https://github.com/mozilla/participation-org/issues/410

**Comment by nukeador** [comment]
They are the same efforts, the "track" is just the implementation or the official name we will give it inside Reps.

**Comment by MichaelKohler** [comment]
@nukeador since this will be highly influenced by the leadership toolkit and how we will do coaching on a higher level inside the org, can this be closed for now? We can still open a new issue for the work to be done in Q1 according to the OKR and then go from there with new issues?

**Comment by nukeador** [comment]
Yep
