### ISSUE TITLE
Create Council Vote for non-EU Maker Parties

### ISSUE THREAD

**Issue by brianking** [mozilla/Reps#82]
## Goal: 
Decide is we want to support non-EU Maker Parties with budget

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:

Responsible: @brianking

Accountable: @nukeador 

Supporting: @couci  

Consulted: Council

Informed: 

## Required: 
- [x] Setup the vote (@brianking, Due: Aug 7th) 
- [x] Share vote url with council, prompt voting (@brianking, Due: Aug 7th) 
- [x] Document decision and policy (@couci, Due: Aug 7th)

**Comment by MichaelKohler** [comment]
@brianking we don't need Tasos to set up the vote here. You should be able to create a vote on https://reps.mozilla.org/voting/new/ with your Council permissions.

**Comment by brianking** [comment]
Ok great thanks. Tasks updated accordingly.

**Comment by MichaelKohler** [comment]
Pending task here is the documentation part. Where do we want to document this for now, @couci?

**Comment by couci** [comment]
well I would suggest to leave it on github on now since the official announcement is not there yet. i also added the phrasing at today's council meeting

**Comment by couci** [comment]
btw following steps on comms here https://github.com/mozilla/part-MakerParty/issues/20

**Comment by couci** [comment]
Decision has been documented in both [discourse](http://discourse.mozilla-community.org/t/resources-for-maker-party-2016/11440) and [wiki](https://wiki.mozilla.org/ReMo/SOPs/Budget/Special_Cases/Maker_Party_EU_2016)
I'm closing this one
