### ISSUE TITLE
Document Decision Making in Bugzilla

### ISSUE THREAD

**Issue by brianking** [mozilla/Reps#84]
## Goal:

Document 2 Council decisions in Bugzilla as part of the Council of the Chair experiment
## Related Issues & Links:
- Planning Doc: https://docs.google.com/a/mozilla.com/document/d/1JUhbErUylIESPOn0PXMT_0SxQbtIh_eKkskPfdCXtd0/edit?usp=sharing
## Roles:

Responsible: Council

Accountable: @brianking

Supporting:

Consulted:

Informed: 
## Required:
- [x] Brainstorm decisions to choose, and select 2 (@brianking, Due: Oct 6th) 
- [x] Write out decision and seek review by council (@brianking, Due: Aug 7th) 
- [ ] Post to BZ (@nukeador, Due: Aug 7th)

**Comment by brianking** [comment]
Draft of first decision, 'Maker Party Vote', sent to council for review. Discussing still what second decision will be.

**Comment by brianking** [comment]
+ @hmitsch 

The 'Maker Party Vote' has been documented [here](https://docs.google.com/document/d/1JUhbErUylIESPOn0PXMT_0SxQbtIh_eKkskPfdCXtd0/edit#heading=h.6nex8i306p6k), and approved by council. The next step if to transfer it to bugzilla.

The 2nd decision is a WIP

**Comment by hmitsch** [comment]
Niiiice, thanks a lot!

**Comment by MichaelKohler** [comment]
I will start documenting the second decision tomorrow.

**Comment by brianking** [comment]
First decision documented:

https://bugzilla.mozilla.org/show_bug.cgi?id=1316628

Discussion thread:

https://discourse.mozilla-community.org/t/decision-making-experiment/11982

**Comment by MichaelKohler** [comment]
Second decision is drafted in the draft doc and currently being reviewed.

**Comment by MichaelKohler** [comment]
Second decision documented:

https://bugzilla.mozilla.org/show_bug.cgi?id=1318073

Same discussion thread.
