### ISSUE TITLE
Alignment with the L10n team on goals

### ISSUE THREAD

**Issue by couci** [mozilla/Reps#86]
## Goal:

Align our L10n events with l10n goals and inform our Reps about them
## Roles:

Responsible: council, @couci

Accountable: council

Supporting:

Consulted: the l10n team

Informed: participation tem
## Required:
- [ ] Ask l10n team to publish a local hackathon template 
- [ ] Work with l10n team on publishing their event goals
- [ ] Agree on a process to get l10n team review local hackathon budget requests.
- [ ] Work on comms with l10n team to Reps

**Comment by ioana-chiorean** [comment]
I am curious if there was any feedback back from L10n Team about participants:
- their involvement in the event 
- their goal progress - I know some had big  goals for their locals, it will be good to see the progress made and impact

**Comment by MichaelKohler** [comment]
Could somebody report back from the l10n talk they had in Hawaii?

**Comment by couci** [comment]
@Flore-mozfr has the meeting notes we've asked them for the local hackathon template, once we have the notes on a doc format we can share next steps and contact them again

**Comment by brianking** [comment]
Notes from Hawaii posted:

https://docs.google.com/a/mozilla.com/document/d/14rfEG-LJT8Za4F5I5hrQ9aryDN2XdJvQzJlEPOLr0oo/edit?usp=sharing

**Comment by MichaelKohler** [comment]
Let's discuss this once we have the finalized CDT OKRs for 2017. @Flore-mozfr could you please take that up again then and follow up on the discussion?

**Comment by couci** [comment]
@Flore-mozfr as far as I know you've replied back to the l10n team, right?

**Comment by MichaelKohler** [comment]
Closing this as it has been done and we will talk to them regarding MozActivate.
