### ISSUE TITLE
Reps Program OKRs Q4

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#87]
## Goal:

Create a document with the Reps program OKRs for the last quarter of 2016 and share them with Reps.
## Roles:

Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: Reps Council
Consulted: -
Informed: Participation Team
## Required:
- [x] Create a draft based on the Participation Q4 OKRs (@MichaelKohler, Due: October 22th) 
- [x] Review and discuss the draft (and add missing pieces) within Council (@MichaelKohler, Due: October 25th) 
- [x] Publish OKRs on the Wiki, create Discourse topic, write blog post (@MichaelKohler, Due: October 29th)

**Comment by MichaelKohler** [comment]
Draft is up for discussion (Council only for now): https://docs.google.com/document/d/1k_R-78WGz2mFDchckEA5TINvoVggwJWUtycaHpFVLNc/edit#

**Comment by MichaelKohler** [comment]
The draft has been reviewed. I've just published it on Discourse: https://discourse.mozilla-community.org/t/reps-program-okrs-goals-q4-2016/11849 . Link has been sent to reps-general as well.

The blog post is under review, @couci @brianking @nukeador please review and publish, thanks!

@couci would you also like to tweet that? Or is a tweet enough when the blog post goes online?

**Comment by couci** [comment]
Published :)
I think the blogpost is connected with twitter so it will go out soon. If not I will tweet about it manually :)
