### ISSUE TITLE
Communication & engagement plan for RepsNext

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#9]
## Goal: 
Find a way to communicate effectively about RepsNext vision and engage Reps

## Success:
We communicate at least bi-weekly about the current status of RepsNexts, and we have posted at least 2 introductory blog posts to bring Reps up to speed.

## Roles:
Owner: @rosanardila, @MichaelKohler
Involved: @umeshagarwal @nukeador @timmaks @gapsonTM

## Required: 
- [ ] Draft second blog post going into further detail about RepsNext (@MichaelKohler @nukeador Due: TBD)
- [ ] Published second blog post after review from Council (@MichaelKohler, Due: June 30th)
- [ ] Update timeline of communication (@MichaelKohler, Due: July 1st) 
- [x] Have a list of "TODO" communications (see comments below) (@MichaelKohler, Due: June 22nd)
- [ ] Comic about RepsNext (@rosanardila @nukeador, Due: July 20th)

**Comment by nukeador** [comment]
@MichaelKohler is there something here overlapping with the identity group?

**Comment by MichaelKohler** [comment]
Not necessarily, we're gonna mostly look into general outreach and communications, not specifically for RepsNext.

**Comment by MichaelKohler** [comment]
Do you think it would make sense to set up a small website which explains all changes in a short format? Obviously we need to get more creative than that, but that would be a good solution for people that like to read, but not that much IMHO. If so, we could ask the Community Creative to design something for us.

**Comment by nukeador** [comment]
@rosanardila idea was to create a comic about it.

**Comment by nukeador** [comment]
@rosanardila  please update the details in this issue. Thanks! :)

**Comment by nukeador** [comment]
@rosanardila we need to update this one with next steps.

**Comment by MichaelKohler** [comment]
I think it would beneficial to come up with a communication plan and timeline before London, so we can just it slightly if needed in London and then go for it! Also after the initial communication as described in #35 we should regularly give updates on what we're working on. A plan on what exactly we want to tackle in London would IMHO be the next step, followed by London results after the All Hands.

The same goes for the engagement plan I guess.

**Comment by MichaelKohler** [comment]
As we have just discussed, we will need to follow up with a more detailed communication around RepsNext. IMHO this should include the following pieces (as we already partly discussed):

* General structure schema
* Table with a comparison of improvements
* Summary of implemented alignment strategy
* Current status of the other working groups (short explanation of what will be improved there)

I could take on the Alignment summary part. @nukeador @Faisalaziz @umeshagarwal @rosanardila @rara79 @bacharakis @ThePhoenixBird @shahidfarooqui what do you think?

**Comment by MichaelKohler** [comment]
![photo171905228960016893](https://cloud.githubusercontent.com/assets/330324/16151624/5c9f0d78-349e-11e6-8d46-eed935bae1b5.jpg)

**Comment by MichaelKohler** [comment]
Some consolidated ideas here:

* A blog post about the comparison before <-> after with a visual structural element to make it easy for everyone (Reps and staff) to understand the improvements
* Slides to catch these improvements splitted up by area and then weekly updates within them (living slide)
* The above 2 outputs could be presented in the Monday meeting call as well to get a broader reach about the improvements
* Comic, but this will take more time, the slides could be a good first steps towards that so we can involve the OpenDesign team

**Comment by MichaelKohler** [comment]
I'm going to draft a second blog post and send out for review until the end of the week, so we can have a second intro for Reps to get up to speed.

**Comment by MichaelKohler** [comment]
I'm sorry, I wasn't able to come up with a draft in the last days. I'll take care of this tomorrow evening!

**Comment by MichaelKohler** [comment]
Started here: https://docs.google.com/document/d/1Xnf8daDl1OzuTvK14gxQKNxwv9ZFZ0PdG_1vaFVbgqA/edit# ... Didn't get that far yet though..

**Comment by hmitsch** [comment]
@MichaelKohler I am suggesting a Lean Startup (validated learning) approach: We provide a rough overview of all impacted RepsNext areas. Additionally we ask for feedback which of these areas should be detailed in the next blog post. This way we make sure we produce articles of maximum interest.

What do you think about this idea?

**Comment by MichaelKohler** [comment]
@hmitsch I really like this idea! Should we open a Discourse topic as well for the questions we pose? Then we can link that for the discussion.

Apart from that, I think we're on a good way, thanks for your inputs! Do we have changes to the sketch? Otherwise we could create an issue in the OpenDesign repository to get a nice drawing for it.

**Comment by hmitsch** [comment]
Let's describe the pricture in words first. This will make OpenDesign's work much easier. 

+1 for the Discourse. 

-- 
Henrik Mitsch

**Comment by MichaelKohler** [comment]
@hmitsch I've added a few lines for the picture. Could you have a look and do your famous suggestion round? :) After that I'll create an issue in the OpenDesign repository with the picture and the text for it to come up with an illustration. Thanks!

**Comment by hmitsch** [comment]
@MichaelKohler sorry for the late feedback. Actually I had a look at the descriptive text. It is definitely a starting point. Unfortunately I am struggling to understand that text. Probably need to read it again with a rested mind. Sorry, I will try again soon (hopefully).

**Comment by MichaelKohler** [comment]
@hmitsch thanks for the initial feedback. I just re-read it, and I definitely agree with you. I will rephrase a few things tomorrow.

Additionally I just bumped the OpenDesign team issue regarding the visual.

**Comment by MichaelKohler** [comment]
The text is final, will be reviewed by Ioana and Nuke to make sure the message is clear (https://docs.google.com/document/d/1Xnf8daDl1OzuTvK14gxQKNxwv9ZFZ0PdG_1vaFVbgqA/edit#). For the visual I asked the OpenDesign team to change a small piece (https://github.com/mozilla/OpenDesign/issues/79#issuecomment-237289350) and then we can publish.

**Comment by MichaelKohler** [comment]
Submitted the blog post for review: https://blog.mozilla.org/mozillareps/wp-admin/post.php?post=445&action=edit .. would be great if somebody could approve it, maybe @rosanardila, @brianking or @ppapadeas have admin rights and could do that?

**Comment by brianking** [comment]
I get:

"You are not allowed to edit this item."

**Comment by MichaelKohler** [comment]
Next blog post published and announced on Telegram and reps-general:

https://blog.mozilla.org/mozillareps/2016/08/11/repsnext-improvements-overview/
https://discourse.mozilla-community.org/t/repsnext-improvements-overview/10251

I'm closing this one so we can open more specific issues for the future according to the feedback we get in the Discourse thread.
