### ISSUE TITLE
Plan for merging all RepsNext pieces

### ISSUE THREAD

**Issue by nukeador** [mozilla/Reps#93]
## Goal:

Plan for merging all moving pieces around RepsNext 
## Roles:
- Responsible: Council @couci 
- Accountable: @nukeador
- Supporting: @deimidis 
- Consulted:
- Informed: Participation
## Required:
- [ ] Capture status from each track/front
- [ ] Define a timeline and milestones for merging each piece 
- [ ] Blog about it.

**Comment by MichaelKohler** [comment]
Let's keep this in mind for Hawaii since we will tackle the timeframe there as well.

**Comment by MichaelKohler** [comment]
@nukeador How much different is this from https://github.com/mozilla/Reps/issues/106 ? Could this one be closed?

**Comment by nukeador** [comment]
Yes, let's just keep one.
