### ISSUE TITLE
Publish November budget breakdown

### ISSUE THREAD

**Issue by couci** [mozilla/Reps#96]
## Goal: 
Publish November budget breakdown for the Reps

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:

Responsible: @couci

Accountable: @couci

Supporting: review team

Consulted: @brianking council

Informed: Reps

## Required: 
- [x] Check if priorities have been changed 
- [x] Create the interactive Report for Reps 
- [x] Create the spreadsheet for council and Review Team
- [ ] Inform the Reps

**Comment by brianking** [comment]
For Activate, the activities to prioritise are WebVR Camp, Web Compatibility Sprint, and Dive Into Rust. The e10s and Addons activity [is closed](https://github.com/mozilla/activate.mozilla.community/issues/102).

**Comment by couci** [comment]
Everything has been updated. Once the official announcement about activities will go out, will point our Reps on the doc as well

**Comment by MichaelKohler** [comment]
@couci quick ping regarding update

**Comment by couci** [comment]
The doc is updated however I have to wait for @brianking on the activate announcements and add it as a follow up.
Also the doc for council-review team view is up to date as well

**Comment by MichaelKohler** [comment]
@couci what's your plan on moving forward here? I would suggest to just publish it "after the fact" and focus on Q1 (which is still pending)

**Comment by couci** [comment]
well now both November and December are updated along with all Q1 view. Do you think an article in discourse about what we've done on Q4 and a mention would be enough?

**Comment by MichaelKohler** [comment]
Yes, that would be enough. Can you then also create a new issue for Q1?

**Comment by couci** [comment]
that's a good suggestion, I will do so once we get the confirmation for 2017 budget.

**Comment by couci** [comment]
added as a comment on the FAQ https://discourse.mozilla-community.org/t/q4-budget-allocation-the-faq/11618

**Comment by MichaelKohler** [comment]
Thank you!
