### ISSUE TITLE
Links that contain non existing programs ( eg: wiki) 

### ISSUE THREAD

**Issue by dyvik100** [mozilla/Reps#97]
## Goal: 
[There are many links on wiki and other platforms which will talk about the non existing programs which creates a trouble where our goal is to Identify and remove them. ] 

## Related Issues & Links: 
[Here is an example : Link : [https://wiki.mozilla.org/Marketing_Collective] #

## Roles:

Responsible: @dyvik100

Accountable: Reps Council

Supporting: Staff

Consulted: @couci 

Informed: @couci 

## Required: 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th) 
- [ ] Put mittens on all of the kittens (owner, Due: Aug 7th)

**Comment by nukeador** [comment]
Please continue in this exiting issue:

https://github.com/mozilla/Reps/issues/17

Thanks! :D
