### ISSUE TITLE
Update Reps on which projects are no longer active

### ISSUE THREAD

**Issue by dyvik100** [mozilla/Reps#98]
## Goal: 
Reps are not able to identify programs/projects which are dead and what are still open for contribution. This is an issue to gather dead contribution projects and to inform fellow reps.

## Related Issues & Links: 
[Reference meta issues and past issues] #

## Roles:

Responsible: @dyvik100

Accountable: 

Supporting:

Consulted: @couci 

Informed: @couci 

## Required: 
- [ ] Identify the inactive programs or projects
- [ ] Classify them accordingly
- [ ] Put Information together
- [ ] Inform Reps about active/Inactive programs

**Comment by dyvik100** [comment]
https://wiki.mozilla.org/Marketing_Collective [Outdated,Program Shutdown]
https://wiki.mozilla.org/StudentAmbassadors/Recognition[needs update]
https://wiki.mozilla.org/CommSquared[Outdated,Program Shutdown]

**Comment by Mte90** [comment]
Can you add more information? Actually I am not sure if it is outdated because now in the weekly meetings we add updates from other program and on discourse it is easy to get updated.

**Comment by Mte90** [comment]
I think this ticket require an analysis about how to do it.
Maybe the better way is to maintain a list of active programs on a wiki page to use as reference?

**Comment by ioana-chiorean** [comment]
I think this is more on Mozilla Employees side - i think - to make a cleared process how to shut ddown a program and its afferent wikis. 

On Reps side I think we can ask and investigate on a certain request as we do not have the overview of all contributions path all mozillians take. 
As process - we can edit the wiki and add some notification. Opinions?

**Comment by Mte90** [comment]
the idea of a cleared process to shut down a program is not a bad idea.
We can involve in the process to reach the Reps Council to have more visibility and point of view from volunteers.

Actually the Reps Council is busy with the OKR, but I can try to do a draft for that (only if there is interest).

**Comment by ioana-chiorean** [comment]
I think this should go even upper than the council - OI team and more.

**Comment by couci** [comment]
No comment on this closing
