### ISSUE TITLE
End of year campaign

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/Reps#99]
## Goal: 
Organize a similar end of year campaign as we had last year.

Topics:
* Activate Campaign Push
* Yearbook

## Related Issues & Links: 
[last year] http://discourse.mozilla-community.org/t/end-of-year-activity-campaign/5671

## Roles:
Responsible: @MichaelKohler
Accountable: Reps Council
Supporting: 
Consulted:
Informed: 

## Required: 
- [ ] Create plan for end of year campaign with goals (@MichaelKohler, Due: November 20th) 
- [ ] Create communication piece (@MichaelKohler, Due: November 23rd)
- [ ] Create Yearbook template document (@MichaelKohler, Due: November 23rd)
- [ ] Council review (Reps Council, Due: November 27th)
- [ ] Publish communication to reps-general, Discourse, Twitter (@MichaelKohler, Due: November 30th)

**Comment by MichaelKohler** [comment]
I started the draft here: https://docs.google.com/document/d/1YxU7Mfa4CE3YebS_icycxQDoJGhbaTk7_RVnNGoecEo/edit#

**Comment by brianking** [comment]
Activate EOY outline [here](https://github.com/mozilla/activate.mozilla.community/issues/118). Let's make sure we don't duplicate.

**Comment by MichaelKohler** [comment]
Communication done on reps-general and Discourse: https://discourse.mozilla-community.org/t/end-of-the-year-campaign/12379

Mail to reps-mentors done as well.
